### ISSUE TITLE
Failed to build diff_gaussian_rasterization simple_knn

### ISSUE THREAD

**Issue by Ujjwal-Rohilla** [graphdeco-inria/gaussian-splatting#1019]
Hi there. Following [this video's](https://www.youtube.com/watch?v=UXtuigy_wYc) tutorial for Gaussian splatting and I get stuck in the `conda env create --file environment.yml` part. Throwing an error which is due to simple-knn

Error:
```
(base) C:\Users\rohil\gaussian-splatting>SET DISTUTILS_USE_SDK=1

(base) C:\Users\rohil\gaussian-splatting>conda env create --file environment.yml
Could not load conda plugin `anaconda-cloud-auth`:

cannot import name 'ChannelAuthBase' from 'conda.plugins.types' (C:\Users\rohil\anaconda3\lib\site-packages\conda\plugins\types.py)
WARNING conda.plugins.manager:load_entrypoints(84): Could not load conda plugin `anaconda-cloud-auth`:

cannot import name 'ChannelAuthBase' from 'conda.plugins.types' (C:\Users\rohil\anaconda3\lib\site-packages\conda\plugins\types.py)
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 24.9.2

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=24.9.2



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: - "By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"

done
Installing pip dependencies: / Ran pip subprocess with arguments:
['C:\\Users\\rohil\\anaconda3\\envs\\gaussian_splatting\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\rohil\\gaussian-splatting\\condaenv.pry8d3d7.requirements.txt', '--exists-action=b']
Pip subprocess output:
Processing c:\users\rohil\gaussian-splatting\submodules\diff-gaussian-rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Processing c:\users\rohil\gaussian-splatting\submodules\simple-knn
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: diff_gaussian_rasterization, simple_knn
  Building wheel for diff_gaussian_rasterization (setup.py): started
  Building wheel for diff_gaussian_rasterization (setup.py): finished with status 'error'
  Running setup.py clean for diff_gaussian_rasterization
  Building wheel for simple_knn (setup.py): started
  Building wheel for simple_knn (setup.py): finished with status 'error'
  Running setup.py clean for simple_knn
Failed to build diff_gaussian_rasterization simple_knn
Installing collected packages: simple_knn, diff_gaussian_rasterization
  Running setup.py install for simple_knn: started
  Running setup.py install for simple_knn: finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [89 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      creating build\lib.win-amd64-cpython-37\diff_gaussian_rasterization
      copying diff_gaussian_rasterization\__init__.py -> build\lib.win-amd64-cpython-37\diff_gaussian_rasterization
      running build_ext
      C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'diff_gaussian_rasterization._C' extension
      creating C:\Users\rohil\gaussian-splatting\submodules\diff-gaussian-rasterization\build\temp.win-amd64-cpython-37
      creating C:\Users\rohil\gaussian-splatting\submodules\diff-gaussian-rasterization\build\temp.win-amd64-cpython-37\Release
      creating C:\Users\rohil\gaussian-splatting\submodules\diff-gaussian-rasterization\build\temp.win-amd64-cpython-37\Release\cuda_rasterizer
      Emitting ninja build file C:\Users\rohil\gaussian-splatting\submodules\diff-gaussian-rasterization\build\temp.win-amd64-cpython-37\Release\build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/5] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\TH -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\Include -c C:\Users\rohil\gaussian-splatting\submodules\diff-gaussian-rasterization\ext.cpp /FoC:\Users\rohil\gaussian-splatting\submodules\diff-gaussian-rasterization\build\temp.win-amd64-cpython-37\Release\ext.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
      FAILED: C:/Users/rohil/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.win-amd64-cpython-37/Release/ext.obj
      cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\TH -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\Include -c C:\Users\rohil\gaussian-splatting\submodules\diff-gaussian-rasterization\ext.cpp /FoC:\Users\rohil\gaussian-splatting\submodules\diff-gaussian-rasterization\build\temp.win-amd64-cpython-37\Release\ext.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_Uninja: fatal: ReadFile: The handle is invalid.


      SE_CXX11_ABI=0 /std:c++14
      CreateProcess failed: The system cannot find the file specified.
      Traceback (most recent call last):
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1814, in _run_ninja_build
          env=env)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\subprocess.py", line 512, in run
          output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\rohil\gaussian-splatting\submodules\diff-gaussian-rasterization\setup.py", line 32, in <module>
          'build_ext': BuildExtension
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 747, in win_wrap_ninja_compile
          with_cuda=with_cuda)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1492, in _write_ninja_file_and_compile_objects
          error_prefix='Error compiling objects for extension')
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [84 lines of output]
      running bdist_wheel
      running build
      running build_ext
      C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'simple_knn._C' extension
      creating C:\Users\rohil\gaussian-splatting\submodules\simple-knn\build
      creating C:\Users\rohil\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-37
      creating C:\Users\rohil\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-37\Release
      Emitting ninja build file C:\Users\rohil\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-37\Release\build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/3] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\TH -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\Include -c C:\Users\rohil\gaussian-splatting\submodules\simple-knn\ext.cpp /FoC:\Users\rohil\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-37\Release\ext.obj /wd4624 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
      FAILED: C:/Users/rohil/gaussian-splatting/submodules/simple-knn/build/temp.win-amd64-cpython-37/Release/ext.obj
      cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\TH -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\Include -c C:\Users\rohil\gaussian-splatting\submodules\simple-knn\ext.cpp /FoC:\Users\rohil\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-37\Release\ext.obj /wd4624 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
      CreateProcess failed: The system cannot finninja: fatal: ReadFile: The handle is invalid.


      d the file specified.
      Traceback (most recent call last):
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1814, in _run_ninja_build
          env=env)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\subprocess.py", line 512, in run
          output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\rohil\gaussian-splatting\submodules\simple-knn\setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 747, in win_wrap_ninja_compile
          with_cuda=with_cuda)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1492, in _write_ninja_file_and_compile_objects
          error_prefix='Error compiling objects for extension')
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple_knn
  error: subprocess-exited-with-error

  × Running setup.py install for simple_knn did not run successfully.
  │ exit code: 1
  ╰─> [99 lines of output]
      running install
      C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      running build
      running build_ext
      C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'simple_knn._C' extension
      creating C:\Users\rohil\gaussian-splatting\submodules\simple-knn\build
      creating C:\Users\rohil\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-37
      creating C:\Users\rohil\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-37\Release
      Emitting ninja build file C:\Users\rohil\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-37\Release\build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/3] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\TH -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\Include -c C:\Users\rohil\gaussian-splatting\submodules\simple-knn\ext.cpp /FoC:\Users\rohil\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-37\Release\ext.obj /wd4624 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
      FAILED: C:/Users/rohil/gaussian-splatting/submodules/simple-knn/build/temp.win-amd64-cpython-37/Release/ext.obj
      cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\TH -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\include -IC:\Users\rohil\anaconda3\envs\gaussian_splatting\Include -c C:\Users\rohil\gaussian-splatting\submodules\simple-knn\ext.cpp /FoC:\Users\rohil\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-37\Release\ext.obj /wd4624 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
      CreateProcess failed: The system cannot finninja: fatal: ReadFile: The handle is invalid.


      d the file specified.
      Traceback (most recent call last):
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1814, in _run_ninja_build
          env=env)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\subprocess.py", line 512, in run
          output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\rohil\gaussian-splatting\submodules\simple-knn\setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\install.py", line 78, in run
          return orig.install.run(self)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\install.py", line 697, in run
          self.run_command('build')
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 747, in win_wrap_ninja_compile
          with_cuda=with_cuda)
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1492, in _write_ninja_file_and_compile_objects
          error_prefix='Error compiling objects for extension')
        File "C:\Users\rohil\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> simple_knn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

failed

CondaEnvException: Pip failed
```

I have tried some methods from the other issues like [this](https://github.com/graphdeco-inria/gaussian-splatting/issues/1014#issuecomment-2421791642) however to no avail.

Help is greatly appreciated.
Thanks!

**Comment by Ujjwal-Rohilla** [comment]
So upon looking further more of the git issues and also the comment section of the video I linked, I finally found a solution (which works for me, at least)

Comment thread from the YT Video:
```
@Musetrigger
Well, I ran the optimizer, and I got a problem.

Encountered error while trying to install package.
-> simple-knn

Further up it reads, ERROR: failed building wheel for simple-knn.

Very peculiar. Not sure where to go from here.

The NeRF Guru
Without seeing the whole error, it's hard to know exactly the problem. This has fixed most people's issue around building the project: https://github.com/graphdeco-inria/gaussian-splatting/issues/146
```

The git replies that helped:
First follow [this](https://github.com/graphdeco-inria/gaussian-splatting/issues/146#issuecomment-1701798506) then [this](https://github.com/graphdeco-inria/gaussian-splatting/issues/146#issuecomment-1697780349)

**Comment by Linkersem** [comment]
hi,
