### ISSUE TITLE
Pip Dependencies fail to install

### ISSUE THREAD

**Issue by JavanMa2024** [graphdeco-inria/gaussian-splatting#1026]
(base) C:\Users\A>cd gaussian-splatting

(base) C:\Users\A\gaussian-splatting>conda env create --file environment.yml
C:\ProgramData\anaconda3\Lib\argparse.py:2006: FutureWarning: `remote_definition` is deprecated and will be removed in 25.9. Use `conda env create --file=URL` instead.
  action(self, namespace, argument_values, option_string)
Channels:
 - pytorch
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:
- Ran pip subprocess with arguments:
['C:\\ProgramData\\anaconda3\\envs\\gaussian_splatting\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\A\]
Pip subprocess output:
Processing c:\users\a\gaussian-splatting\submodules\diff-gaussian-rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Processing c:\users\a\gaussian-splatting\submodules\simple-knn
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting opencv-python
  Using cached opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl (38.8 MB)
Collecting joblib
  Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Requirement already satisfied: numpy>=1.19.3 in c:\programdata\anaconda3\envs\gaussian_splatting\lib\site-packages (fro)
Building wheels for collected packages: diff_gaussian_rasterization, simple_knn
  Building wheel for diff_gaussian_rasterization (setup.py): started
  Building wheel for diff_gaussian_rasterization (setup.py): finished with status 'error'
  Running setup.py clean for diff_gaussian_rasterization
  Building wheel for simple_knn (setup.py): started
  Building wheel for simple_knn (setup.py): finished with status 'error'
  Running setup.py clean for simple_knn
Failed to build diff_gaussian_rasterization simple_knn
Installing collected packages: simple_knn, diff_gaussian_rasterization, opencv-python, joblib
  Running setup.py install for simple_knn: started
  Running setup.py install for simple_knn: finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
      running bdist_wheel
      C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning:.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      copying diff_gaussian_rasterization\__init__.py -> build\lib.win-amd64-cpython-310\diff_gaussian_rasterization
      running build_ext
      C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning:
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\A\gaussian-splatting\submodules\diff-gaussian-rasterization\setup.py", line 17, in <module>
          setup(
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 117, in p
          return distutils.core.setup(**attrs)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 1p
          return run_commands(dist)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 1s
          dist.run_commands()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 9s
          self.run_command(cmd)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 950, in run_d
          super().run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 9d
          cmd_obj.run()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\bdist_wheel.py", lin
          self.run_command("build")
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 31d
          self.distribution.run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 950, in run_d
          super().run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 9d
          cmd_obj.run()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.pyn
          self.run_command(cmd_name)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 31d
          self.distribution.run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 950, in run_d
          super().run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 9d
          cmd_obj.run()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", linen
          _build_ext.run(self)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_exn
          self.build_extensions()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 43s
          self._check_cuda_version(compiler_name, compiler_version)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 80n
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_vendor\packaging\version.pe
          return Version(version)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_vendor\packaging\version.p_
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
      running bdist_wheel
      C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning:.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_ext
      C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning:
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\A\gaussian-splatting\submodules\simple-knn\setup.py", line 21, in <module>
          setup(
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 117, in p
          return distutils.core.setup(**attrs)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 1p
          return run_commands(dist)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 1s
          dist.run_commands()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 9s
          self.run_command(cmd)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 950, in run_d
          super().run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 9d
          cmd_obj.run()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\bdist_wheel.py", lin
          self.run_command("build")
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 31d
          self.distribution.run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 950, in run_d
          super().run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 9d
          cmd_obj.run()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.pyn
          self.run_command(cmd_name)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 31d
          self.distribution.run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 950, in run_d
          super().run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 9d
          cmd_obj.run()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", linen
          _build_ext.run(self)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_exn
          self.build_extensions()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 43s
          self._check_cuda_version(compiler_name, compiler_version)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 80n
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_vendor\packaging\version.pe
          return Version(version)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_vendor\packaging\version.p_
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple_knn
  error: subprocess-exited-with-error

  × Running setup.py install for simple_knn did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
      running install
      C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDep.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      running build
      running build_ext
      C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning:.
        warnings.warn(msg.format('we could not find ninja.'))
      C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning:
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\A\gaussian-splatting\submodules\simple-knn\setup.py", line 21, in <module>
          setup(
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 117, in p
          return distutils.core.setup(**attrs)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 1p
          return run_commands(dist)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 1s
          dist.run_commands()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 9s
          self.run_command(cmd)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 950, in run_d
          super().run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 9d
          cmd_obj.run()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\install.py", line 9n
          return super().run()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\install.n
          self.run_command('build')
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 31d
          self.distribution.run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 950, in run_d
          super().run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 9d
          cmd_obj.run()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.pyn
          self.run_command(cmd_name)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 31d
          self.distribution.run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 950, in run_d
          super().run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 9d
          cmd_obj.run()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", linen
          _build_ext.run(self)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_exn
          self.build_extensions()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 43s
          self._check_cuda_version(compiler_name, compiler_version)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 80n
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_vendor\packaging\version.pe
          return Version(version)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_vendor\packaging\version.p_
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> simple_knn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

failed

CondaEnvException: Pip failed

**Comment by donggeunlee96** [comment]
How about installing WSL on your Windows environment and using gcc/g++ version 9?

**Comment by AsherJingkongChen** [comment]
I think you can try checking your CUDA development environment.

**Comment by rdesc** [comment]
~~Have you tried this? https://github.com/graphdeco-inria/gaussian-splatting/issues/1036#issuecomment-2446052962~~

Edit: nvm it looks like theres some other problem since in the link I sent it just points to the repo for simple_knn which I think should be downloaded fine
