### ISSUE TITLE
Failed to run train.py

### ISSUE THREAD

**Issue by sgcts** [graphdeco-inria/gaussian-splatting#1028]
When I tried to run `python train.py -s ~/workspace/tandt_db/tandt/truck`, I meet two errors:
```
Optimizing 
Output folder: ./output/a2d4bd1e-6 [25/10 19:57:51]
Tensorboard not available: not logging progress [25/10 19:57:51]
Traceback (most recent call last):
  File "/home/dzq/workspace/gaussian-splatting/scene/dataset_readers.py", line 136, in readColmapSceneInfo
    cam_extrinsics = read_extrinsics_binary(cameras_extrinsic_file)
  File "/home/dzq/workspace/gaussian-splatting/scene/colmap_loader.py", line 188, in read_extrinsics_binary
    num_reg_images = read_next_bytes(fid, 8, "Q")[0]
  File "/home/dzq/workspace/gaussian-splatting/scene/colmap_loader.py", line 81, in read_next_bytes
    return struct.unpack(endian_character + format_char_sequence, data)
struct.error: unpack requires a buffer of 8 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dzq/workspace/gaussian-splatting/train.py", line 219, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/home/dzq/workspace/gaussian-splatting/train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "/home/dzq/workspace/gaussian-splatting/scene/__init__.py", line 44, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval)
  File "/home/dzq/workspace/gaussian-splatting/scene/dataset_readers.py", line 141, in readColmapSceneInfo
    cam_extrinsics = read_extrinsics_text(cameras_extrinsic_file)
  File "/home/dzq/workspace/gaussian-splatting/scene/colmap_loader.py", line 249, in read_extrinsics_text
    with open(path, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dzq/workspace/tandt_db/tandt/train/sparse/0/images.txt'
```

How to deal with it?

**Comment by jaco001** [comment]
Train or truck? Do you convert both?

**Comment by sgcts** [comment]
> Train or truck? Do you convert both?

I trian the Train, but I have solved my problem. The reason is that my data have some problem because of the bad internet when I downloaded them, and I have re-downloaded  those data. Thanks for your help.
