### ISSUE TITLE
train.py run failed after repo update recently

### ISSUE THREAD

**Issue by yaoyutian** [graphdeco-inria/gaussian-splatting#1070]
Recently I update this repos,but  i can't run train.py with dataset which was trained successful with 3d gs output  , it now  failed,please help!

- error message
`(gaussian_splatting) D:\code\gaussian-splatting>python train.py -s data\test
Optimizing
Output folder: ./output/e0dd4006-3 [16/11 22:15:21]
Traceback (most recent call last):
  File "D:\code\gaussian-splatting\train.py", line 282, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "D:\code\gaussian-splatting\train.py", line 51, in training
    scene = Scene(dataset, gaussians)
  File "D:\code\gaussian-splatting\scene\__init__.py", line 44, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.depths, args.eval, args.train_test_exp)
AttributeError: 'GroupParams' object has no attribute 'depths'`

- Dateset:

![图片](https://github.com/user-attachments/assets/21ffbde8-e445-46a0-b602-ea4ed44d5435)

- failed:

![图片](https://github.com/user-attachments/assets/862f56ee-e47e-4ce5-9b08-c02f74f48c67)

**Comment by yaoyutian** [comment]
environment i used:
name: sega
channels:
  - nvidia/label/cuda-11.8.0
  - pytorch
  - conda-forge
dependencies:
  - cuda=11.8.0
  - pytorch-cuda=11.8
  - plyfile=0.8.1
  - python=3.9.18
  - pytorch=2.1.1
  - numpy=1.23.5
  - torchaudio=2.1.1
  - torchvision=0.16.1
  - pip=22.3.1
  - setuptools=66.0.0
  - tqdm

**Comment by yaoyutian** [comment]
maybe local files git conflict , resolved.

**Comment by yaoyutian** [comment]
close

**Comment by yaoyutian** [comment]
maybe local files git conflict , resolved.
