### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by HandsomeAozai** [graphdeco-inria/gaussian-splatting#1080]
(gaussian_splatting) aozai720@aozai720-MS-7E13:~/Research/gaussian-splatting$ python train.py -s Data/train
Optimizing 
Output folder: ./output/f07fb106-0 [22/11 10:59:06]
Tensorboard not available: not logging progress [22/11 10:59:06]
Reading camera 301/301 [22/11 10:59:06]
Loading Training Cameras [22/11 10:59:06]
Loading Test Cameras [22/11 10:59:10]
Number of points at initialisation :  182686 [22/11 10:59:10]
Training progress:   0%|                                                                                         | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 288, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 116, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg, use_trained_exp=dataset.train_test_exp, separate_sh=SPARSE_ADAM_AVAILABLE)
  File "/home/aozai720/Research/gaussian-splatting/gaussian_renderer/__init__.py", line 119, in render
    rendered_image = rendered_image.clamp(0, 1)
RuntimeError: CUDA error: an illegal memory access was encountered
Training progress:   0%|                                                                                         | 0/30000 [00:00<?, ?it/s]

How can I solve my problem?

**Comment by Iron486** [comment]
> (gaussian_splatting) aozai720@aozai720-MS-7E13:~/Research/gaussian-splatting$ python train.py -s Data/train Optimizing Output folder: ./output/f07fb106-0 [22/11 10:59:06] Tensorboard not available: not logging progress [22/11 10:59:06] Reading camera 301/301 [22/11 10:59:06] Loading Training Cameras [22/11 10:59:06] Loading Test Cameras [22/11 10:59:10] Number of points at initialisation : 182686 [22/11 10:59:10] Training progress: 0%| | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last): File "train.py", line 288, in training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from) File "train.py", line 116, in training render_pkg = render(viewpoint_cam, gaussians, pipe, bg, use_trained_exp=dataset.train_test_exp, separate_sh=SPARSE_ADAM_AVAILABLE) File "/home/aozai720/Research/gaussian-splatting/gaussian_renderer/**init**.py", line 119, in render rendered_image = rendered_image.clamp(0, 1) RuntimeError: CUDA error: an illegal memory access was encountered Training progress: 0%| | 0/30000 [00:00<?, ?it/s]
> 
> How can I solve my problem?

I have exactly the same issue

**Comment by alpergel** [comment]
I have this problem as well, its from the 3dgs_Acc branch of the rasterizer. If you switch over to main it works.

**Comment by chenqi13814529300** [comment]
I also have the same problem, this branch has issues

**Comment by HandsomeAozai** [comment]
> I have this problem as well, its from the 3dgs_Acc branch of the rasterizer. If you switch over to main it works.

how do I switch branch？

**Comment by BitCalSaul** [comment]
Hi did this branch 3dgs_acc get fixed?

**Comment by trancelestial** [comment]
Maybe you can try modifying setup.py of the renderer to use the following extra_compile_args instead of the original ones:
`extra_compile_args={"nvcc": ["-Xcompiler", "-fno-gnu-unique", "-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "third_party/glm/"), "-O3"]}`

**Comment by BitCalSaul** [comment]
> Maybe you can try modifying setup.py of the renderer to use the following extra_compile_args instead of the original ones: `extra_compile_args={"nvcc": ["-Xcompiler", "-fno-gnu-unique", "-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "third_party/glm/"), "-O3"]}`

 Thank you for your suggestion. However, it still does not work.

**Comment by symao** [comment]
I fix this problem by reinstall all submodules (diff-gaussian-rasterization, fused-ssim, simple-knn)
