### ISSUE TITLE
2060（12G） running 3DGS appears out of memory？

### ISSUE THREAD

**Issue by foooolish** [graphdeco-inria/gaussian-splatting#1120]
I only used 20 images，It works fine for me on my 4060（8G）.

**Comment by foooolish** [comment]
Number of points at initialisation :  18903 [25/12 15:04:54]
Traceback (most recent call last):
  File "train.py", line 277, in <module>
  File "train.py", line 35, in training
  File "scene\__init__.py", line 83, in __init__
  File "scene\gaussian_model.py", line 134, in create_from_pcd
MemoryError: bad allocation: cudaErrorMemoryAllocation: out of memory
