### ISSUE TITLE
_C.cpython-312-x86_64-linux-gnu.so: undefined symbol: __cxa_call_terminate

### ISSUE THREAD

**Issue by christinloehner** [graphdeco-inria/gaussian-splatting#1123]
I'm on Ubuntu 24.10 and the installation of everything and the conda environment with its dependencies went without problems.

I have a lot of images extracted from a video with the following command:

`ffmpeg -i <PATH to video file> -qscale:v 1 -qmin 1 -vf fps=2 %04d.jpg`

Then I have create the dataset with the command:

`python3 convert.py -s <PATH>/<Foldername>/`

**Everything has worked without any error messages.**

Then I try to do the training with this command:

`python3 train.py -s data/Custom_data`

This produces the following error:

```
Traceback (most recent call last):
  File "/home/christin/gaussian-splatting/train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "/home/christin/gaussian-splatting/gaussian_renderer/__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
  File "/home/christin/anaconda3/envs/gaussian_splatting/lib/python3.12/site-packages/diff_gaussian_rasterization/__init__.py", line 15, in <module>
    from . import _C
ImportError: /home/christin/anaconda3/envs/gaussian_splatting/lib/python3.12/site-packages/diff_gaussian_rasterization/_C.cpython-312-x86_64-linux-gnu.so: undefined symbol: __cxa_call_terminate
```

Any help would be really apprectiated!

``

**Comment by JuChi0807** [comment]
Hello, I encounter similar issue... Do you solve this problem then?

**Comment by kimitoinf** [comment]
I had the same issue on gcc-14, but I can solve this issue by using gcc-13.
If you are using gcc-14, then use gcc-13 and reinstall the submodules.
`CC=/usr/bin/gcc-13 CXX=/usr/bin/g++-13 pip install ./diff_gaussian_rasterization`
