### ISSUE TITLE
Issues installing 'diff_gaussian_rasterization'

### ISSUE THREAD

**Issue by Student204161** [graphdeco-inria/gaussian-splatting#126]
Hi there,

I have created a conda env on Linux (Redhat 7) using,

```
conda env create --file environment.yml
conda activate gaussian_splatting

```
& downloaded the submodules using,
```
git submodule sync --recursive
git submodule update --init --recursive --force
```

Then I try to install/build the submodules with `pip install submodules/diff-gaussian-rasterization` but I get the following errors,

```


(gaussian_splatting) [s204161@n-62-30-7 gaussian-splatting]$ pip install submodules/diff-gaussian-rasterization
Processing ./submodules/diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff-gaussian-rasterization
  Building wheel for diff-gaussian-rasterization (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [64 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/appl/cuda/11.8.0'
      running bdist_wheel
      running build
      running build_py
      running build_ext
      /work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'diff_gaussian_rasterization._C' extension
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/zhome/a7/0/155527/Desktop/Bachelor-Project/gaussian-splatting/submodules/diff-gaussian-rasterization/setup.py", line 32, in <module>
          'build_ext': BuildExtension
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 581, in unix_wrap_ninja_compile
          cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 480, in unix_cuda_flags
          cflags + _get_cuda_arch_flags(cflags))
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1694, in _get_cuda_arch_flags
          arch_list[-1] += '+PTX'
      IndexError: list index out of range
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
Installing collected packages: diff-gaussian-rasterization
  Running setup.py install for diff-gaussian-rasterization ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for diff-gaussian-rasterization did not run successfully.
  │ exit code: 1
  ╰─> [85 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/appl/cuda/11.8.0'
      running install
      /work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
      
              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.
      
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      
      !!
        self.initialize_options()
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-37
      creating build/lib.linux-x86_64-cpython-37/diff_gaussian_rasterization
      copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-37/diff_gaussian_rasterization
      running build_ext
      /work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'diff_gaussian_rasterization._C' extension
      creating /zhome/a7/0/155527/Desktop/Bachelor-Project/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-37
      creating /zhome/a7/0/155527/Desktop/Bachelor-Project/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-37/cuda_rasterizer
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/zhome/a7/0/155527/Desktop/Bachelor-Project/gaussian-splatting/submodules/diff-gaussian-rasterization/setup.py", line 32, in <module>
          'build_ext': BuildExtension
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/install.py", line 78, in run
          return orig.install.run(self)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/install.py", line 697, in run
          self.run_command('build')
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 581, in unix_wrap_ninja_compile
          cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 480, in unix_cuda_flags
          cflags + _get_cuda_arch_flags(cflags))
        File "/work3/s204161/miniconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1694, in _get_cuda_arch_flags
          arch_list[-1] += '+PTX'
      IndexError: list index out of range
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> diff-gaussian-rasterization

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

I use gcc version 11.3.0 and have tried with CUDA 11.8 (and also 11.7.1) ... I am not sure what to do, I've also tried building it from source for interactive viewing but I run into some build problems there also.

Thank you for your time.

**Comment by MichaelYu781** [comment]
i have met the same problem while my cuda version is 11.6

**Comment by Student204161** [comment]
So I contacted HPC support at my University and they were very helpful. It should be noticed that the setup/cloud solution is specific for my University, so the following method might not translate well for everyone.

After I requested a GPU for interactive work by writing `a100sh`, I ran the following commands from a shell script,

```

#!/bin/bash

set -e

# for installation:

module load nvidiamodulusbase/pytorch-2.0.0-python-3.11.3 # the HPC solution at my uni allows for loading in common modules like scipy, cuda, opencv... 
virtualenv gausssplatt
source gausssplatt/bin/activate
pip3 install sympy ninja2 networkx pillow plyfile tqdm
cd gausssplatt
git clone https://github.com/graphdeco-inria/gaussian-splatting --recursive
cd gaussian-splatting/submodules/diff-gaussian-rasterization
pip3 install .
cd ../simple-knn
pip3 install .
cd ..
cd ..
python3 train.py --scene path_to_data

exit

```
the submodules then seem to be installed properly & I get an error that I am 99% sure is because I have not formatted the data  properly yet,

![thumbnail_image](https://github.com/graphdeco-inria/gaussian-splatting/assets/97975723/4fa298c2-1ff8-4aaa-a9f5-0c3ce9d96e95)

Therefore I am closing this issue now, as my issue is seemingly solved. Will reopen if it is not the case but I'm crossing fingers.
