### ISSUE TITLE
diff_gaussian_rasterization error

### ISSUE THREAD

**Issue by shaysegal-xr** [graphdeco-inria/gaussian-splatting#137]
I'm having trouble with the training process. The error says "ModuleNotFoundError: No module named 'diff_gaussian_rasterization'", but the module is present in gaussian-splatting\submodules\diff-gaussian-rasterization. Do you have any ideas on how to resolve this?

(gaussian_splatting) C:\Users\shyse\gaussian-splatting>python train.py -s data/home
Traceback (most recent call last):
  File "C:\Users\shyse\gaussian-splatting\train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "C:\Users\shyse\gaussian-splatting\gaussian_renderer\__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

**Comment by grgkopanas** [comment]
If you have followed the instructions and pip install run successfully that
should not have happened. But something might went wrong.

Try to do "python setup.py install" while you have your python environment
activated and you are at the diff_gaussian_rasterization directory so you
can manually compile the submodule.

Best
-gk

**Comment by Snosixtyboo** [comment]
Hi,

just because the directory is there doesn't mean it was installed. Can you try running ```python setup.py install``` from the ```diff-gaussian-rasterization``` folder?

**Comment by shayse-xr** [comment]
**Here is the full process I followed. After starting training, I got stuck on "diff_gaussian_rasterization".**

(base) C:\Users\username>conda activate gaussian_splatting
(gaussian_splatting) C:\Users\username>cd gaussian-splatting
(gaussian_splatting) C:\Users\username\gaussian-splatting>python train.py -s data/roomTraceback (most recent call last):
  File "C:\Users\username\gaussian-splatting\train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "C:\Users\username\gaussian-splatting\gaussian_renderer\__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

(gaussian_splatting) C:\Users\username\gaussian-splatting>

**I then tried installing Python with setup.py:**

(gaussian_splatting) C:\Users\username\gaussian-splatting\submodules\diff-gaussian-rasterization>python setup.py install
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
running install
D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing diff_gaussian_rasterization.egg-info\PKG-INFO
writing dependency_links to diff_gaussian_rasterization.egg-info\dependency_links.txt
writing top-level names to diff_gaussian_rasterization.egg-info\top_level.txt
reading manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
writing manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "C:\Users\Shay Segal\gaussian-splatting\submodules\diff-gaussian-rasterization\setup.py", line 18, in <module>
    setup(
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\install.py", line 80, in run
    self.do_egg_install()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\command\install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
    _check_cuda_version(compiler_name, compiler_version)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\torch\utils\cpp_extension.py", line 383, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

**[The C++ compiler and Cuda 11.8 have been installed and the drivers have been updated]**

**Comment by shayse-xr** [comment]
Here is the full process I followed. After starting training, I got stuck on diff_gaussian_rasterization

```
(base) C:\Users\username>conda activate gaussian_splatting
(gaussian_splatting) C:\Users\username>cd gaussian-splatting
(gaussian_splatting) C:\Users\username\gaussian-splatting>python train.py -s data/roomTraceback (most recent call last):
  File "C:\Users\username\gaussian-splatting\train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "C:\Users\username\gaussian-splatting\gaussian_renderer\__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

(gaussian_splatting) C:\Users\username\gaussian-splatting>

```

I then tried installing Python with setup.py:

```

(gaussian_splatting) C:\Users\username\gaussian-splatting\submodules\diff-gaussian-rasterization>python setup.py install
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
running install
D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing diff_gaussian_rasterization.egg-info\PKG-INFO
writing dependency_links to diff_gaussian_rasterization.egg-info\dependency_links.txt
writing top-level names to diff_gaussian_rasterization.egg-info\top_level.txt
reading manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
writing manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "C:\Users\username\gaussian-splatting\submodules\diff-gaussian-rasterization\setup.py", line 18, in <module>
    setup(
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\install.py", line 80, in run
    self.do_egg_install()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\command\install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
    _check_cuda_version(compiler_name, compiler_version)
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\torch\utils\cpp_extension.py", line 383, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

```
[The C++ compiler and Cuda 11.8 have been installed and the drivers have been updated]

**Comment by Olgelta** [comment]
> Hi,
> 
> just because the directory is there doesn't mean it was installed. Can you try running `python setup.py install` from the `diff-gaussian-rasterization` folder?

OMG this worked, after I did the same with the simple-knn folder. Currently training!

**Comment by shayse-xr** [comment]
> > Hi,
> > just because the directory is there doesn't mean it was installed. Can you try running `python setup.py install` from the `diff-gaussian-rasterization` folder?
> 
> OMG this worked, after I did the same with the simple-knn folder. Currently training!

Can you explain what you did? The simple-knn folder is empty

**Comment by Olgelta** [comment]
> > > Hi,
> > > just because the directory is there doesn't mean it was installed. Can you try running `python setup.py install` from the `diff-gaussian-rasterization` folder?
> > 
> > 
> > OMG this worked, after I did the same with the simple-knn folder. Currently training!
> 
> Can you explain what you did? The simple-knn folder is empty

Mine is not empty now (not sure about before). After I ran the install from the diff-gaussian-rasterization folder, I got the same "missing modules" error for the simmple-knn folder. So I changed directory to that and ran the python install. I really don't know what I'm doing though...

**Comment by narendraadloid** [comment]
> > > Hi,
> > > just because the directory is there doesn't mean it was installed. Can you try running `python setup.py install` from the `diff-gaussian-rasterization` folder?
> > 
> > 
> > OMG this worked, after I did the same with the simple-knn folder. Currently training!
> 
> Can you explain what you did? The simple-knn folder is empty

same with were anyone able to solve this, PLs help me

**Comment by HOKINARI** [comment]
I had the same thing, and I found a solution - you need to check your python version, and if it's higher that 3.11 you can't activate and download PyThorch. So, uninstall python, and install 3.11.xx version( it's the highest version allowed for Pythorch in 11/1/2023) and after reboot pc, download PyThorch. This simple steps helps me to solve this issue.

**Comment by HOKINARI** [comment]
[henrypearce4D](https://github.com/henrypearce4D) gave a useful advise here, and it works for me - https://github.com/graphdeco-inria/gaussian-splatting/issues/146

**Comment by ShanChen-8** [comment]
I have this problem too, then I find out that I didn't clone the submodules,so I clone the submodules again and try to tun the setup.

> Hi,
> 
> just because the directory is there doesn't mean it was installed. Can you try running `python setup.py install` from the `diff-gaussian-rasterization` folder?

**Comment by aaaMsLIUfruit** [comment]
> 以下是我遵循的完整过程。开始训练后，我卡在了 diff_gaussian_rasterization 上
> 
> ```
> (base) C:\Users\username>conda activate gaussian_splatting
> (gaussian_splatting) C:\Users\username>cd gaussian-splatting
> (gaussian_splatting) C:\Users\username\gaussian-splatting>python train.py -s data/roomTraceback (most recent call last):
>   File "C:\Users\username\gaussian-splatting\train.py", line 16, in <module>
>     from gaussian_renderer import render, network_gui
>   File "C:\Users\username\gaussian-splatting\gaussian_renderer\__init__.py", line 14, in <module>
>     from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
> ModuleNotFoundError: No module named 'diff_gaussian_rasterization'
> 
> (gaussian_splatting) C:\Users\username\gaussian-splatting>
> ```
> 
> 然后我尝试使用 setup.py 安装 Python：
> 
> ```
> 
> (gaussian_splatting) C:\Users\username\gaussian-splatting\submodules\diff-gaussian-rasterization>python setup.py install
> No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
> running install
> D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
> !!
> 
>         ********************************************************************************
>         Please avoid running ``setup.py`` directly.
>         Instead, use pypa/build, pypa/installer or other
>         standards-based tools.
> 
>         See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
>         ********************************************************************************
> 
> !!
>   self.initialize_options()
> D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
> !!
> 
>         ********************************************************************************
>         Please avoid running ``setup.py`` and ``easy_install``.
>         Instead, use pypa/build, pypa/installer or other
>         standards-based tools.
> 
>         See https://github.com/pypa/setuptools/issues/917 for details.
>         ********************************************************************************
> 
> !!
>   self.initialize_options()
> running bdist_egg
> running egg_info
> writing diff_gaussian_rasterization.egg-info\PKG-INFO
> writing dependency_links to diff_gaussian_rasterization.egg-info\dependency_links.txt
> writing top-level names to diff_gaussian_rasterization.egg-info\top_level.txt
> reading manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
> writing manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
> installing library code to build\bdist.win-amd64\egg
> running install_lib
> running build_py
> running build_ext
> D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
>   warnings.warn(f'Error checking compiler version for {compiler}: {error}')
> Traceback (most recent call last):
>   File "C:\Users\username\gaussian-splatting\submodules\diff-gaussian-rasterization\setup.py", line 18, in <module>
>     setup(
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\__init__.py", line 107, in setup
>     return distutils.core.setup(**attrs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
>     return run_commands(dist)
>            ^^^^^^^^^^^^^^^^^^
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
>     dist.run_commands()
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
>     self.run_command(cmd)
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
>     super().run_command(command)
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>     cmd_obj.run()
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\install.py", line 80, in run
>     self.do_egg_install()
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\install.py", line 129, in do_egg_install
>     self.run_command('bdist_egg')
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>     self.distribution.run_command(command)
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
>     super().run_command(command)
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>     cmd_obj.run()
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
>     cmd = self.call_command('install_lib', warn_dir=0)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
>     self.run_command(cmdname)
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>     self.distribution.run_command(command)
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
>     super().run_command(command)
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>     cmd_obj.run()
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\install_lib.py", line 11, in run
>     self.build()
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\command\install_lib.py", line 111, in build
>     self.run_command('build_ext')
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>     self.distribution.run_command(command)
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
>     super().run_command(command)
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>     cmd_obj.run()
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
>     _build_ext.run(self)
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
>     self.build_extensions()
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
>     _check_cuda_version(compiler_name, compiler_version)
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\torch\utils\cpp_extension.py", line 383, in _check_cuda_version
>     torch_cuda_version = packaging.version.parse(torch.version.cuda)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
>     return Version(version)
>            ^^^^^^^^^^^^^^^^
>   File "D:\Anaconda\envs\gaussian_splatting\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
>     match = self._regex.search(version)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: expected string or bytes-like object, got 'NoneType'
> ```
> 
> [已安装C++编译器和Cuda 11.8，并更新驱动]

Have you solved the problem? I've met the same with you.

**Comment by StevenHong** [comment]
Hello, I'm having the same issue with this line.
```
match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

The way I fixed it is using the following combo
- python=3.10
- cudatoolkit=11.6
- pip=22.3.1
- pytorch=1.12.1
- torchaudio=0.12.1
- torchvision=0.13.1

I think the key is python3.10 version. I tried python3.7.13 and python3.9 but it gave me error.

My machine: Linux Ubuntu 22.04 with cuda 11.8 installed in /usr/local/cuda-11.8
