### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by CheungBH** [graphdeco-inria/gaussian-splatting#157]
Hello. Thanks for your great work. I have installed your env, however, I met a problem training using train.py when calculating ssim:

Training progress:   0%|                                                                                           | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 216, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 89, in training
    loss = (1.0 - opt.lambda_dssim) * Ll1 + opt.lambda_dssim * (1.0 - ssim(image, gt_image))
  File "/vol/datastore/zhangbh/gaussian-splatting/utils/loss_utils.py", line 41, in ssim
    return _ssim(img1, img2, window, window_size, channel, size_average)
  File "/vol/datastore/zhangbh/gaussian-splatting/utils/loss_utils.py", line 44, in _ssim
    mu1 = F.conv2d(img1, window, padding=window_size // 2, groups=channel)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [3, 1, 11, 11], but got 3-dimensional input of size [3, 800, 800] instead

Are there any suggestions for solving it?

**Comment by CheungBH** [comment]
Solved by using pytorch 2.0 instead of 1.x
