### ISSUE TITLE
simple-knn  installation, No CUDA runtime is found

### ISSUE THREAD

**Issue by emmbertelen** [graphdeco-inria/gaussian-splatting#168]
Ubuntu 20.04, gcc 9.4.0, I had CUDA 11.8 already installed. (also changed to - cudatoolkit=11.8 in the .yml) 
  The `$ conda env create --file environment.yml`  keeps failing at:
  
  `Processing ./submodules/simple-knn
    Preparing metadata (setup.py) ... error
    error: subprocess-exited-with-error
    
    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [6 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/mnt/peter/gaussian/gaussian-splatting/submodules/simple-knn/setup.py", line 13, in <module>
            from torch.utils.cpp_extension import CUDAExtension, BuildExtension
        ModuleNotFoundError: No module named 'torch'
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed
  
  × Encountered error while generating package metadata.
  ╰─> See above for output.
  
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.
  (base) ekecpet@azeuslx0357:/mnt/peter/gaussian/gaussian-splatting$ conda activate gaussian_splatting
  (gaussian_splatting) ekecpet@azeuslx0357:/mnt/peter/gaussian/gaussian-splatting$ pip install submodules/simple-knn
  Processing ./submodules/simple-knn
    Preparing metadata (setup.py) ... done
  Building wheels for collected packages: simple-knn
    Building wheel for simple-knn (setup.py) ... error
    error: subprocess-exited-with-error
    
    × python setup.py bdist_wheel did not run successfully.
    │ exit code: 1
    ╰─> [50 lines of output]
        No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
        running bdist_wheel
        running build
        running build_ext
        Traceback (most recent call last):
          File "<string>", line 36, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/mnt/peter/gaussian/gaussian-splatting/submodules/simple-knn/setup.py", line 33, in <module>
            'build_ext': BuildExtension
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 1233, in run_command
            super().run_command(command)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 364, in run
            self.run_command("build")
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 1233, in run_command
            super().run_command(command)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
            self.run_command(cmd_name)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 1233, in run_command
            super().run_command(command)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 88, in run
            _build_ext.run(self)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
            self.build_extensions()
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 434, in build_extensions
            self._check_cuda_version(compiler_name, compiler_version)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 808, in _check_cuda_version
            torch_cuda_version = packaging.version.parse(torch.version.cuda)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 52, in parse
            return Version(version)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 196, in __init__
            match = self._regex.search(version)
        TypeError: expected string or bytes-like object
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for simple-knn
    Running setup.py clean for simple-knn
  Failed to build simple-knn
  Installing collected packages: simple-knn
    Running setup.py install for simple-knn ... error
    error: subprocess-exited-with-error
    
    × Running setup.py install for simple-knn did not run successfully.
    │ exit code: 1
    ╰─> [65 lines of output]
        No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
        running install
        /mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************
        
        !!
          self.initialize_options()
        running build
        running build_ext
        Traceback (most recent call last):
          File "<string>", line 36, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/mnt/peter/gaussian/gaussian-splatting/submodules/simple-knn/setup.py", line 33, in <module>
            'build_ext': BuildExtension
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 1233, in run_command
            super().run_command(command)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/install.py", line 78, in run
            return orig.install.run(self)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/install.py", line 697, in run
            self.run_command('build')
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 1233, in run_command
            super().run_command(command)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
            self.run_command(cmd_name)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 1233, in run_command
            super().run_command(command)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 88, in run
            _build_ext.run(self)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
            self.build_extensions()
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 434, in build_extensions
            self._check_cuda_version(compiler_name, compiler_version)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 808, in _check_cuda_version
            torch_cuda_version = packaging.version.parse(torch.version.cuda)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 52, in parse
            return Version(version)
          File "/mnt/peter/anaconda/envs/gaussian_splatting/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 196, in __init__
            match = self._regex.search(version)
        TypeError: expected string or bytes-like object
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: legacy-install-failure
  
  × Encountered error while trying to install package.
  ╰─> simple-knn
  
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for output from the failure.`
  
  
  Any idea on this? I have check the cuda installation, `$which nvcc`, `$nvcc --version` working perfectly, even tried `$export CUDA_HOME=/usr/local/cuda`, didnt help.
  Thanks for the help in advance.

**Comment by williambittner1** [comment]
I have a very similar issue. Would be happy for any hints too.

**Comment by ang88myt** [comment]
# Possible Solutions for Python Build Errors

## 1. Verify CUDA Installation
Make sure CUDA is properly installed and environment variables are set. If your project doesn't need CUDA, check if you can build the project without it.

## 2. Check PyTorch Version
Make sure PyTorch is installed and its CUDA version is compatible with the installed CUDA toolkit. You can print PyTorch and CUDA versions with:
```python
import torch
print(torch.__version__)
print(torch.version.cuda)
```

## 3. Update Packages
Ensure `setuptools`, `wheel`, and `packaging` Python packages are up-to-date. You can update them using pip.
```bash
pip install --upgrade setuptools wheel packaging
```

## 4. Inspect `setup.py`
Look into the `setup.py` script especially at line 33. Check if any of the variables or settings there could be causing the issue.

## 5. Clean Build
Sometimes stale build files can cause issues. Try cleaning the build directory, usually you can do this with:
```bash
python setup.py clean --all
```

## 6. Check Compiler
Make sure that the compiler specified in your build script or environment is installed and in the PATH.

## 7. Detailed Error Log
Run the command with a higher verbosity level to get more details on the error.
```bash
python setup.py build_ext --verbose
```

## 8. Python Environment
Consider creating a new Anaconda environment specifically for this project to isolate dependencies.

## 9. Debugging
Use Python's built-in debugger to step through the code and inspect variables to identify exactly where the issue arises.

**Comment by williambittner1** [comment]
I was able to resolve this issue! 

1. It seemed that the cpu-only version of pytorch got installed when installing the dependencies through running "conda env create --file environment.yml" which I realized when running "conda list" and inspecting the package name of pytorch (pytorch-1.13.1-py3.7_cpu_0) which was the cpu-only version. 

2. I removed that environment, created a new environment with python 3.8 (!) 

3. and instead of directly installing the dependencies through the environment.yml, I first installed the cuda version of pytorch through "conda install pytorch==2.0.0 torchvision==0.15.0 torchaudio==2.0.0 pytorch-cuda=11.8 -c pytorch -c nvidia", 

4. and finally the other necessary dependencies: plyfile, tqdm. 

Et voilá: The installation of the submodules worked.

**Comment by Ryan-ZL-Lin** [comment]
@williambittner1  
Thanks for the solution to solve this issue, it also works for me to setup the conda environment.
However, when I start to train the model in that environment, I got the following error 
`ImportError: DLL load failed while importing _imaging: The specified module could not be found.`

Have you also encountered the same issue?

here is the full error message 
```
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "C:\Users\lzlal\gaussian-splatting\gaussian_renderer\__init__.py", line 15, in <module>
    from scene.gaussian_model import GaussianModel
  File "C:\Users\lzlal\gaussian-splatting\scene\__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "C:\Users\lzlal\gaussian-splatting\scene\dataset_readers.py", line 14, in <module>
    from PIL import Image
  File "C:\Users\lzlal\.conda\envs\gaussian-splatting\lib\site-packages\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.
```

**Comment by Snosixtyboo** [comment]
> @williambittner1 Thanks for the solution to solve this issue, it also works for me to setup the conda environment. However, when I start to train the model in that environment, I got the following error `ImportError: DLL load failed while importing _imaging: The specified module could not be found.`
> 
> Have you also encountered the same issue?
> 
> here is the full error message
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 16, in <module>
>     from gaussian_renderer import render, network_gui
>   File "C:\Users\lzlal\gaussian-splatting\gaussian_renderer\__init__.py", line 15, in <module>
>     from scene.gaussian_model import GaussianModel
>   File "C:\Users\lzlal\gaussian-splatting\scene\__init__.py", line 16, in <module>
>     from scene.dataset_readers import sceneLoadTypeCallbacks
>   File "C:\Users\lzlal\gaussian-splatting\scene\dataset_readers.py", line 14, in <module>
>     from PIL import Image
>   File "C:\Users\lzlal\.conda\envs\gaussian-splatting\lib\site-packages\PIL\Image.py", line 103, in <module>
>     from . import _imaging as core
> ImportError: DLL load failed while importing _imaging: The specified module could not be found.
> ```

Hi,

that should go into a separate issue.
