### ISSUE TITLE
train.py - ImportError: DLL load failed while importing _imaging: The specified module could not be found.

### ISSUE THREAD

**Issue by Ryan-ZL-Lin** [graphdeco-inria/gaussian-splatting#180]
Hi, thanks for the great work for this repo, I'm really excited to test out 3D gaussian-splatting.
After resolving the dependency issues, I finally got the conda environment up and running.
I intended to use my previous COLMAP processed dataset to train the model, however, I got the error  `ImportError: DLL load failed while importing _imaging: The specified module could not be found.` , and have no idea how to move on, I hope that it's not an duplicated issue on this repo. 

```
(gaussian-splatting) C:\Users\lzlal\gaussian-splatting>python train.py -s data/MBC50
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "C:\Users\lzlal\gaussian-splatting\gaussian_renderer\__init__.py", line 15, in <module>
    from scene.gaussian_model import GaussianModel
  File "C:\Users\lzlal\gaussian-splatting\scene\__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "C:\Users\lzlal\gaussian-splatting\scene\dataset_readers.py", line 14, in <module>
    from PIL import Image
  File "C:\Users\lzlal\.conda\envs\gaussian-splatting\lib\site-packages\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.
```

**Comment by zaferbozyer** [comment]
python -m pip install --upgrade pip

Then

pip install opencv-python
