### ISSUE TITLE
`args.data_device` missing in the pre-trained models

### ISSUE THREAD

**Issue by MCYang273730** [graphdeco-inria/gaussian-splatting#198]
When I was rendering the official pre-trained models following the instructions in `README.md`, this error occurred:
```
# In README.md:
# python render.py -m <path to pre-trained model> -s <path to COLMAP dataset>
$ python render.py -m truck -s tandt/truck
Looking for config file in truck/cfg_args
Config file found: truck/cfg_args
Rendering truck
Loading trained model at iteration 30000 [12/09 15:58:28]
Reading camera 251/251 [12/09 15:58:30]
Converting point3d.bin to .ply, will happen only the first time you open the scene. [12/09 15:58:30]
Loading Training Cameras [12/09 15:58:31]
Traceback (most recent call last):
  File "/content/gaussian-splatting/render.py", line 66, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test)
  File "/content/gaussian-splatting/render.py", line 40, in render_sets
    scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False)
  File "/content/gaussian-splatting/scene/__init__.py", line 73, in __init__
    self.train_cameras[resolution_scale] = cameraList_from_camInfos(scene_info.train_cameras, resolution_scale, args)
  File "/content/gaussian-splatting/utils/camera_utils.py", line 58, in cameraList_from_camInfos
    camera_list.append(loadCam(args, id, c, resolution_scale))
  File "/content/gaussian-splatting/utils/camera_utils.py", line 52, in loadCam
    image_name=cam_info.image_name, uid=id, data_device=args.data_device)
AttributeError: 'GroupParams' object has no attribute 'data_device'
```
It appears that `--data_device` is a required argument to `render.py`?

After browsing the commit history I found that `--data_device` was added one week after the release of the pre-trained models.  As a consequence, `args.data_device` is not found in `truck/cfg_args`.

And yeah, simply adding this option like the following does the job.
```
$ python render.py -m truck -s tandt/truck --data_device cuda
```

Now what should we do?  Add this option manually to the cfg_args of the pre-trained models?  Add `--data_device` to the instructions for evaluating the pre-trained models?  Or modify some of the code?

I only tested `render.py`, so I am not sure if the same issue arises in the other evaluation scripts.

**Comment by Aira-AY** [comment]
I have met the same problem. I tested metric.py on the pre-trained model, when the metric evaluation progress be 31%, the following ocurrs:
Unable to compute metrics for model xxx\playroom 
I don’t know how to solve it.

**Comment by JiatengLiu** [comment]
@Aira-AY it does work for adding args？

**Comment by Buffyqsf** [comment]
@MCYang273730 Hey, have you solved this problem? I've met a similar one. And I don't know how to solve it.

**Comment by Buffyqsf** [comment]
> @MCYang273730 Hey, have you solved this problem? I've met a similar one. And I don't know how to solve it.

I found it's related to python args. And add data_device in command line or add it in the related cfg_args would help. 
The reason may related to the params 'sentinel=True' of ModelParams.

**Comment by ivanpuhachov** [comment]
had the same error, fixed with `--data_device cuda`
```
python render.py -m models/bicycle/ -s mipnerf/360_v2/bicycle/ --data_device cuda
```

**Comment by MCYang273730** [comment]
@Aira-AY I just tested `metric.py` by myself, and there was no error.
You may try to remove the try-except clause from `metric.py` and observe the exception reported by Python.
(The original implementation simply suppresses all the errors, and it hinders debugging a lot.)
Hopefully this helps you solve your problem. Sorry for the late reply though.
@Buffyqsf I also noticed `sentinel=True`, and I have always doubted its existence.
Of course, simply removing it would be another solution,
but my issue originally had another purpose of raising the original authors' awareness and having them make the final decision.
This is probably not going to happen though, but I'm leaving the issue open anyways.

**Comment by Forest-Lee** [comment]
Now here's a new problem, which indicates missing `args.depths` when tesing pre-trained models for `render.py` as well as `full_eval.py`.
Did anyone know how to slove it?
```
python .\render.py -m .\pretrained_models\models\train\ -s ..\data\tandt_db\tandt\train\
Looking for config file in .\pretrained_models\models\train\cfg_args
Config file found: .\pretrained_models\models\train\cfg_args
Rendering .\pretrained_models\models\train\
Loading trained model at iteration 30000 [08/12 20:02:42]
Traceback (most recent call last):
  File ".\render.py", line 77, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test, SPARSE_ADAM_AVAILABLE)
  File ".\render.py", line 51, in render_sets
    scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False)
  File "E:\Project\gaussian-splatting\scene\__init__.py", line 44, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.depths, args.eval, args.train_test_exp)
AttributeError: 'GroupParams' object has no attribute 'depths'
```

**Comment by zouiner** [comment]
@Forest-Lee I got with your problem too. Can you fix out now?

I'm quite not sure how to set the --depths to be.

**Comment by Forest-Lee** [comment]
> [@Forest-Lee](https://github.com/Forest-Lee) I got with your problem too. Can you fix out now?
> 
> I'm quite not sure how to set the --depths to be.

After a few times attempting, I found that it can be solved by modifying the `cfg_args`  file in your pretrained models' path, including add args `data_device='cuda', depths='', train_test_exp=False`. And the fun fact is that the `args.depths` is just assigned to empty, then the render progress should be done.

**Comment by MCYang273730** [comment]
@Forest-Lee Thanks for your update to this issue.  I just want to add another comment that adding a command-line argument (such as the solution proposed by @ivanpuhachov) would not work for `train_test_exp` since it can not be "set" to `False` using `--no_train_test_exp` or `--train_test_exp False` or such.
