### ISSUE TITLE
New install fails at "conda env create --file environment.yml" - Collecting package metadata (repodata.json): failed

### ISSUE THREAD

**Issue by jblessinghne** [graphdeco-inria/gaussian-splatting#219]
Hi, I'm having trouble installing on a win 10 pc. I've followed along until the "Installing the Optimizer" step #2 of "conda env create --file environment.yml" I've tried multiple things suggested on here with adding env paths, "conda install -c anaconda vs2019_win-64",  multiple restarts, etc, with no luck. Here is the result of "conda env create --file environment.yml"

`(base) C:\Users\John\gaussian-splatting>conda env create --file environment.yml
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda_env\cli\main.py", line 56, in do_call
        exit_code = getattr(module, func_name)(arguments, parser)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\notices\core.py", line 124, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda_env\cli\main_create.py", line 162, in execute
        result[installer_type] = installer.install(
                                 ^^^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda_env\installers\conda.py", line 51, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\core\solve.py", line 154, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
                                   ^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\core\solve.py", line 215, in solve_for_diff
        final_precs = self.solve_final_state(
                      ^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\core\solve.py", line 358, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\common\io.py", line 84, in decorated
        return f(*args, **kwds)
               ^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\core\solve.py", line 572, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\core\solve.py", line 1286, in _prepare
        reduced_index = get_reduced_index(
                        ^^^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\core\index.py", line 291, in get_reduced_index
        push_record(record)
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\core\index.py", line 261, in push_record
        combined_depends = record.combined_depends
                           ^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\models\records.py", line 366, in combined_depends
        result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\models\match_spec.py", line 477, in merge
        name_groups = groupby(attrgetter("name"), match_specs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\common\iterators.py", line 18, in groupby_to_dict
        result[key].extend(group)
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\models\match_spec.py", line 436, in name
        return self.get_exact_value("name") or "*"
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\John\anaconda3\Lib\site-packages\conda\models\match_spec.py", line 213, in get_exact_value
        return v and v.exact_value
                     ^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute 'exact_value'

`$ C:\Users\John\anaconda3\Scripts\conda-env-script.py create --file environment.yml`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\John\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\John\anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\John\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\John\anaconda3\python.exe
               CONDA_ROOT=C:\Users\John\anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\John
               LD_PRELOAD=<not set>
 MAGICK_CODER_MODULE_PATH=C:\Program Files (x86)\X-Rite\i1Profiler\coders
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\Users\John\anaconda3;C:\Users\John\anaconda3\Library\mingw-
                          w64\bin;C:\Users\John\anaconda3\Library\usr\bin;C:\Users\John\anaconda
                          3\Library\bin;C:\Users\John\anaconda3\Scripts;C:\Users\John\anaconda3\
                          bin;C:\Users\John\anaconda3\condabin;C:\Users\John\anaconda3;C:\Users\
                          John\anaconda3\Library\mingw-
                          w64\bin;C:\Users\John\anaconda3\Library\usr\bin;C:\Users\John\anaconda
                          3\Library\bin;C:\Users\John\anaconda3\Scripts;C:\Program Files\NVIDIA
                          GPU Computing Toolkit\CUDA\v11.8\bin;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v11.8\libnvvp;C:\Program Files (x86)\Common
                          Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files
                          (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma
                          SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program
                          Files\Razer\ChromaBroadcast\bin;C:\Program Files (x86)\Common
                          Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program
                          Files (x86)\Common Files\Intel\Shared
                          Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Common
                          Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system
                          32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowe
                          rShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\NVIDIA
                          Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\Common Files\Autodesk
                          Shared;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;c:\program
                          files\extensis\connect fonts;C:\Windows\system32\config\systemprofile\
                          AppData\Local\Microsoft\WindowsApps;C:\Program
                          Files\Git\cmd;C:\Program Files\NVIDIA Corporation\Nsight Compute 2022.
                          3.0;C:\Users\John\AppData\Local\Microsoft\WindowsApps;C:\Users\John\ff
                          mpeg-2023-09-07-git-9c9f48e7f2-
                          essentials_build\bin;C:\Users\John\COLMAP-3.8-windows-cuda;C:\Program
                          Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8;C:\Program Files\NVIDIA
                          GPU Computing Toolkit\CUDA\v11.8\bin;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v11.8\libnvvp;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v11.8\include;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v11.8\extras\CUPTI\lib64;C:\Program Files
                          (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133
                          \bin\Hostx64\x64;C:\Program Files (x86)\Microsoft Visual
                          Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\John\anaconda3
            shell level : 1
       user config file : C:\Users\John\.condarc
 populated config files : C:\Users\John\.condarc
          conda version : 23.7.4
    conda-build version : 3.26.0
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __win=0=0
       base environment : C:\Users\John\anaconda3  (writable)
      conda av data dir : C:\Users\John\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\John\anaconda3\pkgs
                          C:\Users\John\.conda\pkgs
                          C:\Users\John\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\John\anaconda3\envs
                          C:\Users\John\.conda\envs
                          C:\Users\John\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.4 Windows/10 Windows/10.0.19045 aau/0.4.1 c/CILIXOnX9ziOEggCRAL4Zw s/bd8fk0eGqoxxsqCiyaWXyA e/dObwhlOTvRfDYQLYOnrmUA
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:`

**Comment by Snosixtyboo** [comment]
Hi,

that looks like a Conda setup issue. I would try the suggested step in the error message

```An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install```
