### ISSUE TITLE
Pip Downloads failed

### ISSUE THREAD

**Issue by msteffenelli** [graphdeco-inria/gaussian-splatting#257]
Hi guys,

I have tried to re-install everything, still does not work:

- Windows 11 Pro
-  Cuda 11.8
- Anaconda

(base) PS C:\Users\mkola\gaussian-splatting> conda env create --file environment.yml
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: | "By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"

done
Installing pip dependencies: | Ran pip subprocess with arguments:
['C:\\Users\\mkola\\anaconda3\\envs\\gaussian_splatting\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\mkola\\gaussian-splatting\\condaenv.hlde7cvw.requirements.txt', '--exists-action=b']
Pip subprocess output:
Processing c:\users\mkola\gaussian-splatting\submodules\diff-gaussian-rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Processing c:\users\mkola\gaussian-splatting\submodules\simple-knn
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: diff-gaussian-rasterization, simple-knn
  Building wheel for diff-gaussian-rasterization (setup.py): started
  Building wheel for diff-gaussian-rasterization (setup.py): finished with status 'error'
  Running setup.py clean for diff-gaussian-rasterization
  Building wheel for simple-knn (setup.py): started
  Building wheel for simple-knn (setup.py): finished with status 'error'
  Running setup.py clean for simple-knn
Failed to build diff-gaussian-rasterization simple-knn
Installing collected packages: simple-knn, diff-gaussian-rasterization
  Running setup.py install for simple-knn: started
  Running setup.py install for simple-knn: finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
      running bdist_wheel
      C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      creating build\lib.win-amd64-cpython-37\diff_gaussian_rasterization
      copying diff_gaussian_rasterization\__init__.py -> build\lib.win-amd64-cpython-37\diff_gaussian_rasterization
      running build_ext
      C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mkola\gaussian-splatting\submodules\diff-gaussian-rasterization\setup.py", line 32, in <module>
          'build_ext': BuildExtension
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 434, in build_extensions
          self._check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 808, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
          return Version(version)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
      running bdist_wheel
      C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_ext
      C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mkola\gaussian-splatting\submodules\simple-knn\setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 434, in build_extensions
          self._check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 808, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
          return Version(version)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple-knn
  error: subprocess-exited-with-error

  × Running setup.py install for simple-knn did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
      running install
      C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      running build
      running build_ext
      C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:346: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mkola\gaussian-splatting\submodules\simple-knn\setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\install.py", line 78, in run
          return orig.install.run(self)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\install.py", line 697, in run
          self.run_command('build')
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 434, in build_extensions
          self._check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 808, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
          return Version(version)
        File "C:\Users\mkola\anaconda3\envs\gaussian_splatting\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> simple-knn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

failed

CondaEnvException: Pip failed

**Comment by LuciusRapKing** [comment]
same problem

**Comment by Garfield-Finch** [comment]
Same problem

**Comment by TommyyCaron** [comment]
same problem

**Comment by Yo1up** [comment]
same problem, none of the suggested fixes for similar issues has helped in any way, shape, or form. I have installed 2 versions of VS, only one (2019) is in PATH, both versions I have installed are valid versions (17-19). I have 6 different versions of CUDA in PATH because I need them all for different projects, deleting them is not an option. the part in the readme that says "C++ Compiler and CUDA SDK must be compatible" is not clear enough to be of any use. I was able to get the COLMAP preprocessor to function by simply running "pip install simple-knn" to get the latest version of simple-knn, however, the issue persists with the other submodule, "diff-gaussian-rasterization" and I have not found a similar workaround.

**Comment by Alphyn-gunner** [comment]
This is really frustrating. I've read all the issues on the repo and tried all possible solutions. Reinstalled VC, CUDA, even conda mulitiple times. Added all sorts of things into PATH. 
diff-gaussian-rasterization always fails to install.

**Comment by LilithNoctis** [comment]
Same problem. Reinstalling everything didn't help either.

**Comment by wgcban** [comment]
Same problem

**Comment by wgcban** [comment]
I was able to install submodule pkgs. I have listed the steps here: https://github.com/graphdeco-inria/gaussian-splatting/issues/297#issuecomment-1753921575

**Comment by ishipachev** [comment]
I had the same problem. It seems there is mismatch between recommended version of cuda and what is actually inside environment.yml file (there is cuda 11.6)
I wrote about it here (and how to potentially resolve it):
https://github.com/graphdeco-inria/gaussian-splatting/issues/317

**Comment by Jason-Zhu0704** [comment]
I have the same problem with u. I can't find the solution.
