### ISSUE TITLE
Camera model error: Colmap data

### ISSUE THREAD

**Issue by victorhuzhening** [graphdeco-inria/gaussian-splatting#272]
I have a question about the camera model of the data: is cameras.bin where the gaussian_splatting model reads the model from? I have a cameras.bin file that I believe specifies PINHOLE model, but I keep getting this error:

Optimizing 
Output folder: ./output/752b4cb7-a [03/10 04:25:09]
Reading camera 1/315Traceback (most recent call last):
  File "/content/gaussian-splatting/train.py", line 216, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/content/gaussian-splatting/train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "/content/gaussian-splatting/scene/__init__.py", line 44, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval)
  File "/content/gaussian-splatting/scene/dataset_readers.py", line 145, in readColmapSceneInfo
    cam_infos_unsorted = readColmapCameras(cam_extrinsics=cam_extrinsics, cam_intrinsics=cam_intrinsics, images_folder=os.path.join(path, reading_dir))
  File "/content/gaussian-splatting/scene/dataset_readers.py", line 95, in readColmapCameras
    assert False, "Colmap camera model not handled: only undistorted datasets (PINHOLE or SIMPLE_PINHOLE cameras) supported!"
AssertionError: Colmap camera model not handled: only undistorted datasets (PINHOLE or SIMPLE_PINHOLE cameras) supported!

I also have the files organized as shown in the README. Any clues/tips on what might be causing the problem? Should I maybe specify camera model when I generate the files from Colmap?

Appreciate the help.

**Comment by Snosixtyboo** [comment]
Hi,

if your model DOES specify a PINHOLE camera, the above error shouldn't be raised, so i strongly suspect that it uses something else.

**Comment by codegrafix** [comment]
@PKU-YQH I tried you suggestion, and change the images path to the new "images" folder that were created after clicking "Undistortion". GS train.py still does not work. How did you get it to work?

**Comment by cucdengjunli** [comment]
same

**Comment by cucdengjunli** [comment]
> This is because there are some distortion in your images. Fortunately,Colmap has a function to solve it. Colmap->Reconstruction->Dense reconstruction->Undistortion. After those processes,3DGS can run correctly. I hope this will give some help.

what did you do after Undistortion

**Comment by RoyAmoyal** [comment]
same error here..

**Comment by luojin** [comment]
<img width="928" alt="企业微信截图_ca4c74f5-2a68-4804-b424-e2a780f68813" src="https://github.com/graphdeco-inria/gaussian-splatting/assets/7139534/eb17c33a-8f5e-4c27-8a4c-37a3fb44f93a">
@cucdengjunli @RoyAmoyal

**Comment by GaussRieman** [comment]
> <img alt="企业微信截图_ca4c74f5-2a68-4804-b424-e2a780f68813" width="928" src="https://private-user-images.githubusercontent.com/7139534/301125176-eb17c33a-8f5e-4c27-8a4c-37a3fb44f93a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDM0OTUsIm5iZiI6MTcwNjcwMzE5NSwicGF0aCI6Ii83MTM5NTM0LzMwMTEyNTE3Ni1lYjE3YzMzYS04ZjVlLTRjMjctOGE0Yy0zN2EzZmI0NGY5M2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMTIxMzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUwODc3ZTdmZDA0ZWJiZDhmMTk0ZTUwOTg2NWM3N2QwNWQ2MzQxZmQzZjkxYjliZjRmN2U2ZmQ3ZGE4NjE2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Od5H87NIp5zFk0hNB5Ix_HDKXoUCDb5nR2aVvosbCK4"> @cucdengjunli @RoyAmoyal

this works, thx!

**Comment by Sukriti-Shukla** [comment]
I dont understand the solution given by @cucdengjunli @RoyAmoyal can someone please explain in detail what to do

**Comment by Sukriti-Shukla** [comment]
Sry, by @luojin , can someone please explain what to do exactly @GaussRieman , how did you get it resolved?

**Comment by nurbanu170399** [comment]
As i understand, you should use the .bin/.txt files from the "sparse" folder of "dense" folder. Move them and it'll work i think. @Sukriti-Shukla

**Comment by j71200** [comment]
I solved this issue by running the convert.py.
`python convert.py -s YOUR_COLMAP_OUTPUT_DIR --colmap_executable YOUR_COLMAP_BIN_OR_BAT_PATH`

**Comment by michelgokan** [comment]
I have the same issue and above solutions didn't work for me.

The structure of my Colmap folder is as follows (for readability, I’ve omitted the full list of images and used .... to indicate truncated sections):

```
.
├── database.db
├── dense
│   └── 0
│       ├── fused.ply
│       ├── fused.ply.vis
│       ├── images
│       │   ├── 00001.jpg
│       │   ├── 00002.jpg
│       │   ├── 00003.jpg
│       │   ├── 00004.jpg
│       │   ├── 00005.jpg
│       │   ├── 00006.jpg
	....
│       │   ├── 00403.jpg
│       │   ├── 00404.jpg
│       │   ├── 00405.jpg
│       │   ├── 00406.jpg
│       │   ├── 00407.jpg
│       │   └── 00408.jpg
│       ├── meshed-poisson.ply
│       ├── run-colmap-geometric.sh
│       ├── run-colmap-photometric.sh
│       ├── sparse
│       │   ├── cameras.bin
│       │   ├── images.bin
│       │   └── points3D.bin
│       └── stereo
│           ├── consistency_graphs
│           ├── depth_maps
│           │   ├── 00001.jpg.geometric.bin
│           │   ├── 00001.jpg.photometric.bin
│           │   ├── 00002.jpg.geometric.bin
│           │   ├── 00002.jpg.photometric.bin
│           │   ├── 00003.jpg.geometric.bin
│           │   ├── 00003.jpg.photometric.bin
│           │   ├── 00004.jpg.geometric.bin
│           │   ├── 00004.jpg.photometric.bin
│           │   ├── 00005.jpg.geometric.bin
│           │   ├── 00005.jpg.photometric.bin
│           │   ├── 00006.jpg.geometric.bin
│           │   ├── 00006.jpg.photometric.bin
		...
│           │   ├── 00406.jpg.geometric.bin
│           │   ├── 00406.jpg.photometric.bin
│           │   ├── 00407.jpg.geometric.bin
│           │   ├── 00407.jpg.photometric.bin
│           │   ├── 00408.jpg.geometric.bin
│           │   └── 00408.jpg.photometric.bin
│           ├── fusion.cfg
│           ├── normal_maps
│           │   ├── 00001.jpg.geometric.bin
│           │   ├── 00001.jpg.photometric.bin
│           │   ├── 00002.jpg.geometric.bin
│           │   ├── 00002.jpg.photometric.bin
│           │   ├── 00003.jpg.geometric.bin
│           │   ├── 00003.jpg.photometric.bin
│           │   ├── 00004.jpg.geometric.bin
│           │   ├── 00004.jpg.photometric.bin
│           │   ├── 00005.jpg.geometric.bin
│           │   ├── 00005.jpg.photometric.bin
│           │   ├── 00006.jpg.geometric.bin
│           │   ├── 00006.jpg.photometric.bin
│           │   ....
		├── 00403.jpg.photometric.bin
│           │   ├── 00404.jpg.geometric.bin
│           │   ├── 00404.jpg.photometric.bin
│           │   ├── 00405.jpg.geometric.bin
│           │   ├── 00405.jpg.photometric.bin
│           │   ├── 00406.jpg.geometric.bin
│           │   ├── 00406.jpg.photometric.bin
│           │   ├── 00407.jpg.geometric.bin
│           │   ├── 00407.jpg.photometric.bin
│           │   ├── 00408.jpg.geometric.bin
│           │   └── 00408.jpg.photometric.bin
│           └── patch-match.cfg
├── distorted
│   └── sparse
├── images
│   ├── 00001.jpg
│   ├── 00002.jpg
│   ├── 00003.jpg
│   ├── 00004.jpg
│   ├── 00005.jpg
│   ├
....
│   ├── 00406.jpg
│   ├── 00407.jpg
│   ├── 00408.jpg
│   └── distorted
│       └── sparse
└── sparse
    ├── 0
    │   ├── cameras.bin
    │   ├── images.bin
    │   └── points3D.bin
    └── project.ini

15 directories, 2463 files
```

There is no `cameras.bin`, `images.bin`, and `points3D.bin` under `sparse/`. They are already under `sparse/0/`. I can see Colmap already executed the undistorte during the recunstruction phase. I re-applied undistortion again as @HHHHH6123 suggested but still I get the same error:

```
Reading camera 1/408Traceback (most recent call last):
  File "/root/Project/./gaussian_splatting/train.py", line 220, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/root/Project/./gaussian_splatting/train.py", line 36, in training
    scene = Scene(dataset, gaussians)
  File "/root/Project/gaussian_splatting/scene/__init__.py", line 44, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval)
  File "/root/Project/gaussian_splatting/scene/dataset_readers.py", line 145, in readColmapSceneInfo
    cam_infos_unsorted = readColmapCameras(cam_extrinsics=cam_extrinsics, cam_intrinsics=cam_intrinsics, images_folder=os.path.join(path, reading_dir))
  File "/root/Project/gaussian_splatting/scene/dataset_readers.py", line 95, in readColmapCameras
    assert False, "Colmap camera model not handled: only undistorted datasets (PINHOLE or SIMPLE_PINHOLE cameras) supported!"
AssertionError: Colmap camera model not handled: only undistorted datasets (PINHOLE or SIMPLE_PINHOLE cameras) supported!
```

I have also tried the solution provided by @j71200 by running the following:

```
python /root/gaussian_splatting/convert.py -s /workspace/ --colmap_executable /usr/bin/colmap
```

Getting following error:

```
[option_manager.cc:811] Check failed: ExistsDir(*image_path)
ERROR: Invalid options provided.
ERROR:root:Feature extraction failed with code 256. Exiting.
```

Any ideas?

**Comment by Sukriti-Shukla** [comment]
I guess you should run the colmap again, and change the model type to PINHOLE, that's what finally worked for me

**Comment by michelgokan** [comment]
> I guess you should run the colmap again, and change the model type to PINHOLE, that's what finally worked for me

How did you set the model type to PINHOLE? I don't see an option to set model type in the automatic reconstruction window (see attached screenshot).

<img width="311" alt="Screenshot 2024-11-21 at 1 22 30 AM" src="https://github.com/user-attachments/assets/83730a7e-749a-46c0-a246-015befca82ae">

**Comment by Sukriti-Shukla** [comment]
Dont do automatic reconstruction, do feature extraction -> feature matching -> start reconstruction,  while doing feature extraction you can set model type to PINHOLE

**Comment by j71200** [comment]
@michelgokan 
Sorry for my incomplete solution. You can copy the "images" folder and rename it as "input" (or use symbolic link).
Anyway, **you need an "input" folder includes all the images**. My folder structure looks like:

```
/workspace
├── distorted
│   ├── sparse
│   │   └── 0
│   │       ├── cameras.bin
│   │       ├── images.bin
│   │       ├── points3D.bin
│   │       └── project.ini
│   └── database.db
├── images
│   ├── 0000.png
│   ├── 0013.png
│   ├── 0026.png
│   ├── ... total 262 items ...
│   ├── 3380.png
│   └── 3393.png
├── input
│   ├── 0000.png
│   ├── 0013.png
│   ├── 0026.png
│   ├── ... total 262 items ...
│   ├── 3380.png
│   └── 3393.png
├── sparse
│   └── 0
│       ├── cameras.bin
│       ├── images.bin
│       ├── points3D.bin
│       ├── points3D.ply
│       └── project.ini
├── sparse_text
│   ├── cameras.txt
│   ├── images.txt
│   └── points3D.txt
├── database.db
...
```

**Comment by michelgokan** [comment]
@j71200 

Thanks your answer. I now changed my folder structure as follows:

```
├── database.db
├── dense
│   └── 0
│       ├── distorted
│       │   └── sparse
│       ├── fused.ply
│       ├── fused.ply.vis
│       ├── images
│       │   ├── 00001.jpg
│       │   ├── 00002.jpg
│       │   ├── 00003.jpg
...
│       │   ├── 00405.jpg
│       │   ├── 00406.jpg
│       │   ├── 00407.jpg
│       │   └── 00408.jpg
│       ├── meshed-poisson.ply
│       ├── run-colmap-geometric.sh
│       ├── run-colmap-photometric.sh
│       ├── sparse
│       │   ├── cameras.bin
│       │   ├── images.bin
│       │   └── points3D.bin
│       └── stereo
│           ├── consistency_graphs
│           ├── depth_maps
│           │   ├── 00001.jpg.geometric.bin
│           │   ├── 00001.jpg.photometric.bin
│           │   ├── 00002.jpg.geometric.bin
...
│           │   ├── 00407.jpg.geometric.bin
│           │   ├── 00407.jpg.photometric.bin
│           │   ├── 00408.jpg.geometric.bin
│           │   └── 00408.jpg.photometric.bin
│           ├── fusion.cfg
│           ├── normal_maps
│           │   ├── 00001.jpg.geometric.bin
│           │   ├── 00001.jpg.photometric.bin
│           │   ├── 00002.jpg.geometric.bin
│           │   ├── 00002.jpg.photometric.bin
...
│           │   ├── 00408.jpg.geometric.bin
│           │   └── 00408.jpg.photometric.bin
│           └── patch-match.cfg
├── distorted
│   ├── database.db
│   └── sparse
│       ├── 0
│       │   ├── cameras.bin
│       │   ├── images.bin
│       │   ├── points3D.bin
│       │   └── project.ini
│       └── project.ini
├── images
│   ├── 00001.jpg
│   ├── 00002.jpg
│   ├── 00003.jpg
...
│   ├── 00406.jpg
│   ├── 00407.jpg
│   ├── 00408.jpg
│   └── distorted
│       └── sparse
├── input
│   ├── 00001.jpg
│   ├── 00002.jpg
│   ├── 00003.jpg
│   ├── 00004.jpg
...
│   ├── 00406.jpg
│   ├── 00407.jpg
│   ├── 00408.jpg
│   └── distorted
│       └── sparse
└── sparse
    ├── 0
    │   ├── cameras.bin
    │   ├── images.bin
    │   ├── points3D.bin
    │   └── project.ini
    ├── database.db
    └── project.ini


21 directories, 2879 files

```

I'm still getting exactly same error!

Meanwhile, I'm now trying @Sukriti-Shukla suggestion.

**Comment by michelgokan** [comment]
It seems like I had to create a folder named `0` under `dense/0/sparse/` and copy the content of `sparse` into that folder (similar to what @luojin suggested). I also had to select the `dense` folder as the workspace, not the root folder of Colamp's workspace. It's now running without errors (will take several hours before I see the results, but just wanted to update about a potential solution)

**Comment by mollysunqy** [comment]
@j71200 Thanks a lot, works like magic!

**Comment by linnajing** [comment]
After feature extraction -> feature matching -> start reconstruction, just do this step（Extras - >undistortion) and use the new sparse folder (cameras.bin、images.bin\points3D.bin)

![Image](https://github.com/user-attachments/assets/20733c33-52db-4c1e-811a-6e30a9d79fd2)

**Comment by LunaBright** [comment]
Maybe you can try this: add following code in file `dataset_readers.py` in its 97 lines:
```
elif intr.model in ["OPENCV", "SIMPLE_RADIAL", "RADIAL"]:
    focal_length_x = intr.params[0]
    focal_length_y = intr.params[1]
    FovY = focal2fov(focal_length_y, height)
    FovX = focal2fov(focal_length_x, width)
```
it is used to process other camera models.

**Comment by jwaitzel** [comment]
> Maybe you can try this: add following code in file `dataset_readers.py` in its 97 lines:
> 
> ```
> elif intr.model in ["OPENCV", "SIMPLE_RADIAL", "RADIAL"]:
>     focal_length_x = intr.params[0]
>     focal_length_y = intr.params[1]
>     FovY = focal2fov(focal_length_y, height)
>     FovX = focal2fov(focal_length_x, width)
> ```
> 
> it is used to process other camera models.

This fixed my train.py using colmap gradio for making the SfM
