### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by Schmidi321** [graphdeco-inria/gaussian-splatting#308]
I have been struggling through the installation for 2 days, now I am getting the following error message

(gaussian_splatting) C:\Users\Michael\gaussian-splatting>python train.py data/meingarten
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "C:\Users\Michael\gaussian-splatting\gaussian_renderer\__init__.py", line 15, in <module>
    from scene.gaussian_model import GaussianModel
  File "C:\Users\Michael\gaussian-splatting\scene\__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "C:\Users\Michael\gaussian-splatting\scene\dataset_readers.py", line 24, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "C:\Users\Michael\gaussian-splatting\scene\gaussian_model.py", line 20, in <module>
    from simple_knn._C import distCUDA2
ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.

(gaussian_splatting) C:\Users\Michael\gaussian-splatting>

**Comment by dharmasai21** [comment]
Have you found the solution ?
