### ISSUE TITLE
Preparing Images Issue

### ISSUE THREAD

**Issue by VFXProfessorAwesome** [graphdeco-inria/gaussian-splatting#311]
When trying to prepare images I get this error:

```
(gaussian_splatting) C:\Users\Christian\gaussian-splatting>python train.py -s data\motorcycle
Optimizing
Output folder: ./output/dcaacaf5-5 [11/10 12:12:37]
Tensorboard not available: not logging progress [11/10 12:12:37]
Traceback (most recent call last):
  File "train.py", line 216, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "C:\Users\Christian\gaussian-splatting\scene\__init__.py", line 49, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!

```
I had the Pip issue as well, I think I fixed that using the info from the other thread but maybe I am still missing something?

**Comment by VFXProfessorAwesome** [comment]
Okay so, it looks like the issue was the data\motorcycle line.
Putting the full path into the command prompt fixed the issue
