### ISSUE TITLE
oh help me plz_python train.py -s erro

### ISSUE THREAD

**Issue by SDFEWRFGS** [graphdeco-inria/gaussian-splatting#313]
Optimizing
Output folder: ./output/ad4a9b9b-1 [12/10 08:51:30]
Tensorboard not available: not logging progress [12/10 08:51:30]
Reading camera 1/12Traceback (most recent call last):
  File "train.py", line 216, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "C:\Users\the2h\gaussian-splatting\scene\__init__.py", line 44, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval)
  File "C:\Users\the2h\gaussian-splatting\scene\dataset_readers.py", line 145, in readColmapSceneInfo
    cam_infos_unsorted = readColmapCameras(cam_extrinsics=cam_extrinsics, cam_intrinsics=cam_intrinsics, images_folder=os.path.join(path, reading_dir))
  File "C:\Users\the2h\gaussian-splatting\scene\dataset_readers.py", line 99, in readColmapCameras
    image = Image.open(image_path)
  File "C:\Users\the2h\AppData\Local\anaconda3\envs\gaussian_splatting\lib\site-packages\PIL\Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\the2h\\gaussian-splatting\\data\\B\\images\\0029.jpg

**Comment by Askejm** [comment]
The last error says " FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\the2h\gaussian-splatting\data\B\images\0029.jpg" 
Have you tried verifying if this file is in the specified location?

**Comment by xiaoxiongzhg** [comment]
@SDFEWRFGS Have you solved this problem?I got a similar one.
Traceback (most recent call last):
  File "train.py", line 216, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "/root/3d/scene/__init__.py", line 44, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval)
  File "/root/3d/scene/dataset_readers.py", line 146, in readColmapSceneInfo
    cam_infos_unsorted = readColmapCameras(cam_extrinsics=cam_extrinsics, cam_intrinsics=cam_intrinsics, images_folder=os.path.join(path, reading_dir))
  File "/root/3d/scene/dataset_readers.py", line 100, in readColmapCameras
    image = Image.open(image_path)
  File "/root/miniconda3/lib/python3.8/site-packages/PIL/Image.py", line 3227, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/root/3d/data/building/images/0002-checkpoint.png'

**Comment by AntonSoeffing** [comment]
> @SDFEWRFGS Have you solved this problem?I got a similar one. Traceback (most recent call last): File "train.py", line 216, in training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from) File "train.py", line 35, in training scene = Scene(dataset, gaussians) File "/root/3d/scene/**init**.py", line 44, in **init** scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval) File "/root/3d/scene/dataset_readers.py", line 146, in readColmapSceneInfo cam_infos_unsorted = readColmapCameras(cam_extrinsics=cam_extrinsics, cam_intrinsics=cam_intrinsics, images_folder=os.path.join(path, reading_dir)) File "/root/3d/scene/dataset_readers.py", line 100, in readColmapCameras image = Image.open(image_path) File "/root/miniconda3/lib/python3.8/site-packages/PIL/Image.py", line 3227, in open fp = builtins.open(filename, "rb") FileNotFoundError: [Errno 2] No such file or directory: '/root/3d/data/building/images/0002-checkpoint.png'

Hey @xiaoxiongzhg I have the exaact same issue, did you manage to fix it and if so, how?
