### ISSUE TITLE
Can't resume training from checkpoint

### ISSUE THREAD

**Issue by shokomon** [graphdeco-inria/gaussian-splatting#379]
Hi there. I'm training on some photos of and alleyway. I've done 7k iterations in one session (loss 0.18). 30k iterations in the next session (loss 0.09). So obviously I'd like to keep training BUT this time I'd like to use the checkpoint saved at 30k iterations as my starting point to save training time.

Unfortunately this gives the following error message. Can anybody help me? Much appreciated all!

PS: I'm also unsure whether --iterations 40000 will stop at the 40000th iteration (meaning it does 10k iterations this time) or whether it means to train for a further 40000 iterations, stopping at 70k.

=====================

(gaussian_splatting) C:\Users\myUserName\gaussian-splatting>python train.py -s C:\Users\myUserName\gaussian-splatting\data\AlleywayAllFootage -m ./output/AlleyWayAll_40k --start_checkpoint C:\Users\myUserName\gaussian-splatting\output\AlleyWayAll_30k\point_cloud\iteration_30000\point_cloud.ply  --iterations 40000
Optimizing ./output/AlleyWayAll_40k
Output folder: ./output/AlleyWayAll_40k [24/10 11:25:45]
Tensorboard not available: not logging progress [24/10 11:25:45]
Reading camera 241/241 [24/10 11:25:46]
Loading Training Cameras [24/10 11:25:47]
[ INFO ] Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K.
 If this is not desired, please explicitly specify '--resolution/-r' as 1 [24/10 11:25:47]
Loading Test Cameras [24/10 11:26:07]
Number of points at initialisation :  159302 [24/10 11:26:07]
Traceback (most recent call last):
  File "train.py", line 216, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 38, in training
    (model_params, first_iter) = torch.load(checkpoint)
  File "C:\Users\myUserName\AppData\Local\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\myUserName\AppData\Local\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow

**Comment by kungfrank** [comment]
You should set --checkpoint_iterations during your training step and load the stored chkpnt.pth to resume the training, not point_cloud.ply.

**Comment by murcje** [comment]
I tried a bunch of ways, can't figure this out. When I abort a training session after the 7k save, I do not have a chkpnt.pth file. Or am I misunderstanding this completely?
