### ISSUE TITLE
Error when trying to create the environment (I am using CUDA 11.8)

### ISSUE THREAD

**Issue by jjpatino-byte** [graphdeco-inria/gaussian-splatting#382]
Preparing transaction: done
Verifying transaction: done
Executing transaction: - By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/home/jjpatino/anaconda3/envs/gaussian_splatting/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/jjpatino/gaussian-splatting/condaenv.ncldoawf.requirements.txt', '--exists-action=b']
Pip subprocess output:
Processing ./submodules/diff-gaussian-rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Processing ./submodules/simple-knn
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: diff-gaussian-rasterization, simple-knn
  Building wheel for diff-gaussian-rasterization (setup.py): started
  Building wheel for diff-gaussian-rasterization (setup.py): finished with status 'error'
  Running setup.py clean for diff-gaussian-rasterization
  Building wheel for simple-knn (setup.py): started
  Building wheel for simple-knn (setup.py): finished with status 'error'
  Running setup.py clean for simple-knn
Failed to build diff-gaussian-rasterization simple-knn
Installing collected packages: simple-knn, diff-gaussian-rasterization
  Running setup.py install for simple-knn: started
  Running setup.py install for simple-knn: finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [70 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-37
      creating build/lib.linux-x86_64-cpython-37/diff_gaussian_rasterization
      copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-37/diff_gaussian_rasterization
      running build_ext
      /home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'diff_gaussian_rasterization._C' extension
      creating /home/jjpatino/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-37
      creating /home/jjpatino/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-37/cuda_rasterizer
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/jjpatino/gaussian-splatting/submodules/diff-gaussian-rasterization/setup.py", line 32, in <module>
          'build_ext': BuildExtension
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 581, in unix_wrap_ninja_compile
          cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 480, in unix_cuda_flags
          cflags + _get_cuda_arch_flags(cflags))
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1694, in _get_cuda_arch_flags
          arch_list[-1] += '+PTX'
      IndexError: list index out of range
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
      running bdist_wheel      running build
      running build_ext
      /home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'simple_knn._C' extension
      creating /home/jjpatino/gaussian-splatting/submodules/simple-knn/build
      creating /home/jjpatino/gaussian-splatting/submodules/simple-knn/build/temp.linux-x86_64-cpython-37
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/jjpatino/gaussian-splatting/submodules/simple-knn/setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 581, in unix_wrap_ninja_compile
          cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 480, in unix_cuda_flags
          cflags + _get_cuda_arch_flags(cflags))
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1694, in _get_cuda_arch_flags
          arch_list[-1] += '+PTX'
      IndexError: list index out of range
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple-knn
  error: subprocess-exited-with-error
  
  × Running setup.py install for simple-knn did not run successfully.
  │ exit code: 1
  ╰─> [80 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
      running install
      /home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
      
              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.
      
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      
      !!
        self.initialize_options()
      running build
      running build_ext
      /home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'simple_knn._C' extension
      creating /home/jjpatino/gaussian-splatting/submodules/simple-knn/build
      creating /home/jjpatino/gaussian-splatting/submodules/simple-knn/build/temp.linux-x86_64-cpython-37
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/jjpatino/gaussian-splatting/submodules/simple-knn/setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/install.py", line 78, in run
          return orig.install.run(self)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/install.py", line 697, in run
          self.run_command('build')
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 581, in unix_wrap_ninja_compile
          cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 480, in unix_cuda_flags
          cflags + _get_cuda_arch_flags(cflags))
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1694, in _get_cuda_arch_flags
          arch_list[-1] += '+PTX'
      IndexError: list index out of range
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple-knn
  error: subprocess-exited-with-error
  
  × Running setup.py install for simple-knn did not run successfully.
  │ exit code: 1
  ╰─> [80 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
      running install
      /home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
      
              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.
      
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      
      !!
        self.initialize_options()
      running build
      running build_ext
      /home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'simple_knn._C' extension
      creating /home/jjpatino/gaussian-splatting/submodules/simple-knn/build
      creating /home/jjpatino/gaussian-splatting/submodules/simple-knn/build/temp.linux-x86_64-cpython-37
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/jjpatino/gaussian-splatting/submodules/simple-knn/setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/install.py", line 78, in run
          return orig.install.run(self)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/install.py", line 697, in run
          self.run_command('build')
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 581, in unix_wrap_ninja_compile
          cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 480, in unix_cuda_flags
          cflags + _get_cuda_arch_flags(cflags))
        File "/home/jjpatino/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1694, in _get_cuda_arch_flags
          arch_list[-1] += '+PTX'
      IndexError: list index out of range
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> simple-knn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

failed

CondaEnvException: Pip failed

**Comment by MerlinusMerlin** [comment]
Maybe don't listen to me, but i was able to fix my issue with a 4090 by installing the nightly of 12.whatever the latest is .. I know everyone says don't but it worked for me.

**Comment by jjpatino-byte** [comment]
> Maybe don't listen to me, but i was able to fix my issue with a 4090 by installing the nightly of 12.whatever the latest is .. I know everyone says don't but it worked for me.
 
@MerlinusMerlin Can you explain yourself better? What is the nightly of 12? Do you refer to your graphics card by "4090"?

**Comment by MerlinusMerlin** [comment]
Yep, 4090 is the graphics card, I wasnt able to get it working via 11.8 or 11.7 so went to cuda's main page and used the latest nightly build cuda_12.2.2_537.13_windows.exe

**Comment by Geraedz** [comment]
I'm having the same error... 

@MerlinusMerlin Did you have this same error before as OP? I also have a 4090...
