### ISSUE TITLE
RuntimeError  CUDA version (12.0) mismatches the version that was used to compile  

### ISSUE THREAD

**Issue by gouxin666** [graphdeco-inria/gaussian-splatting#385]
pip install submodules/diff-gaussian-rasterization
Processing ./submodules/diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff-gaussian-rasterization
  Building wheel for diff-gaussian-rasterization (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running bdist_wheel
      /home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
      copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/lhs/project/nerf/gaussian-splatting-main/submodules/diff-gaussian-rasterization/setup.py", line 17, in <module>
          setup(
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/home/lhs/.conda/envs/3dgs/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.0) mismatches the version that was used to compile
      PyTorch (11.8). Please make sure to use the same CUDA versions.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects

Hello,In readme.md, you mentioned that the running results were good in the (Python 3.8, PyTorch 2.0.0, CUDA 12) environment. Have you encountered any of the above issues during the working process?

**Comment by henrypearce4D** [comment]
can you try;
```
conda activate gaussian_splatting
pip list
```
to see what version of troch is installed?

then you could try;

`pip uninstall torch torchvision torchaudio`

next;

`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`

then again
`pip list`

to check that `torch-2.1.0+cu121` installed?


looking here I cant see torch-2.0.0 with cuda 12.0
https://download.pytorch.org/whl/torch/#:~:text=torch%2D2.1.0%2Bcu121.with.pypi.cudnn%2Dcp38%2Dcp38%2Dlinux_x86_64.whl

**Comment by gouxin666** [comment]
pip install submodules/diff-gaussian-rasterization 
Processing ./submodules/diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff-gaussian-rasterization
  Building wheel for diff-gaussian-rasterization (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      /home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/torch/utils/cpp_extension.py:502: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      running build_ext
      /home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/torch/utils/cpp_extension.py:414: UserWarning: The detected CUDA version (12.0) has a minor version mismatch with the version that was used to compile PyTorch (12.1). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no g++ version bounds defined for CUDA version 12.0
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'diff_gaussian_rasterization._C' extension
      /usr/local/cuda-12.0/bin/nvcc -I/home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/torch/include -I/home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/torch/include/TH -I/home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-12.0/include -I/home/lhs/.conda/envs/gaussian_splatting/include/python3.8 -c cuda_rasterizer/backward.cu -o build/temp.linux-x86_64-cpython-38/cuda_rasterizer/backward.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -I/home/lhs/project/nerf/gaussian-splatting-main/submodules/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 -std=c++17
      In file included from cuda_rasterizer/backward.cu:11:
      cuda_rasterizer/backward.h:19:10: fatal error: glm/glm.hpp: No such file or directory
         19 | #include <glm/glm.hpp>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/local/cuda-12.0/bin/nvcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
Installing collected packages: diff-gaussian-rasterization
  Running setup.py install for diff-gaussian-rasterization ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for diff-gaussian-rasterization did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      running install
      /home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
      
              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.
      
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      
      !!
        self.initialize_options()
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
      copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
      running build_ext
      /home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/torch/utils/cpp_extension.py:502: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      /home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/torch/utils/cpp_extension.py:414: UserWarning: The detected CUDA version (12.0) has a minor version mismatch with the version that was used to compile PyTorch (12.1). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no g++ version bounds defined for CUDA version 12.0
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'diff_gaussian_rasterization._C' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/cuda_rasterizer
      /usr/local/cuda-12.0/bin/nvcc -I/home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/torch/include -I/home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/torch/include/TH -I/home/lhs/.conda/envs/gaussian_splatting/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-12.0/include -I/home/lhs/.conda/envs/gaussian_splatting/include/python3.8 -c cuda_rasterizer/backward.cu -o build/temp.linux-x86_64-cpython-38/cuda_rasterizer/backward.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -I/home/lhs/project/nerf/gaussian-splatting-main/submodules/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 -std=c++17
      In file included from cuda_rasterizer/backward.cu:11:
      cuda_rasterizer/backward.h:19:10: fatal error: glm/glm.hpp: No such file or directory
         19 | #include <glm/glm.hpp>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/local/cuda-12.0/bin/nvcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> diff-gaussian-rasterization

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

Thank you for your reply. I downloaded pytorch again according to your method, but encountered new problems. May I ask if you encountered this problem again during the experiment

**Comment by henrypearce4D** [comment]
Can you try updating cuda to 12.1 ? https://developer.nvidia.com/cuda-12-1-0-download-archive
It should not be a problem but worth trying

also what Visual studio version are you using?

you can try running this to make sure the paths are setup correctly

for 2019
`conda install -c anaconda vs2019_win-64`

or for 2022
`conda install -c conda-forge vs2022_win-64`

**Comment by kwea123** [comment]
the second problem you have seems related to `glm`. Can you verify if you have pulled all submodules? Go to `submodules/diff-gaussian-rasterization/third_party` and check if `glm` is there. If not do `git submodule update --init --recursive`

**Comment by gouxin666** [comment]
> Can you try updating cuda to 12.1 ? https://developer.nvidia.com/cuda-12-1-0-download-archive It should not be a problem but worth trying
> 
> also what Visual studio version are you using?
> 
> you can try running this to make sure the paths are setup correctly
> 
> for 2019 `conda install -c anaconda vs2019_win-64`
> 
> or for 2022 `conda install -c conda-forge vs2022_win-64`

Thank you very much for your reply, the issue has been resolved by changing the CUDA version

**Comment by gouxin666** [comment]
> the second problem you have seems related to `glm`. Can you verify if you have pulled all submodules? Go to `submodules/diff-gaussian-rasterization/third_party` and check if `glm` is there. If not do `git submodule update --init --recursive`

I didn't find glm in the third_party, reinstalled the problem according to your method, thank you for your reply!!

**Comment by sucy171106** [comment]
> the second problem you have seems related to `glm`. Can you verify if you have pulled all submodules? Go to `submodules/diff-gaussian-rasterization/third_party` and check if `glm` is there. If not do `git submodule update --init --recursive`

thanks so much， kui jiang. I remember i downloaded the diff-gaussian-rasterization in the github website. thanks to your comment, i find the _glm_ folder is empty. Then i run `git submodule update --init --recursive`.  it works!

**Comment by azverndias09** [comment]
> the second problem you have seems related to `glm`. Can you verify if you have pulled all submodules? Go to `submodules/diff-gaussian-rasterization/third_party` and check if `glm` is there. If not do `git submodule update --init --recursive`

This helped for some reason glm wasn't part of my submodules even though i had cloned it recursively
