### ISSUE TITLE
I got some problems while training... help!

### ISSUE THREAD

**Issue by jwc-portkeyspac** [graphdeco-inria/gaussian-splatting#407]
`(gaussian_splatting) C:\Users\jtoil\gaussian-splatting>python train.py -s data/standard
Optimizing
Output folder: ./output/f63cd780-9 [29/10 22:44:13]
Tensorboard not available: not logging progress [29/10 22:44:13]
Traceback (most recent call last):
  File "C:\Users\jtoil\gaussian-splatting\scene\dataset_readers.py", line 136, in readColmapSceneInfo
    cam_extrinsics = read_extrinsics_binary(cameras_extrinsic_file)
  File "C:\Users\jtoil\gaussian-splatting\scene\colmap_loader.py", line 199, in read_extrinsics_binary
    image_name += current_char.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 0: unexpected end of data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 219, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "C:\Users\jtoil\gaussian-splatting\scene\__init__.py", line 44, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval)
  File "C:\Users\jtoil\gaussian-splatting\scene\dataset_readers.py", line 141, in readColmapSceneInfo
    cam_extrinsics = read_extrinsics_text(cameras_extrinsic_file)
  File "C:\Users\jtoil\gaussian-splatting\scene\colmap_loader.py", line 249, in read_extrinsics_text
    with open(path, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jtoil\\gaussian-splatting\\data\\standard\\sparse/0\\images.txt'`

after converting by `convert python -s `, I run the train code and got some problem.
What's the problem??

**Comment by jaco001** [comment]
Paths?
convert.py -s [full path here]
and if you have colmap instaled you get some pictures in images folder and camera info file. 
After that 
train.py -s [full path here]
And all should work :) (effects are in the output folder)

**Comment by Shichao123123** [comment]
> ```
> (gaussian_splatting) C:\Users\jtoil\gaussian-splatting>python train.py -s data/standard
> Optimizing
> Output folder: ./output/f63cd780-9 [29/10 22:44:13]
> Tensorboard not available: not logging progress [29/10 22:44:13]
> Traceback (most recent call last):
>   File "C:\Users\jtoil\gaussian-splatting\scene\dataset_readers.py", line 136, in readColmapSceneInfo
>     cam_extrinsics = read_extrinsics_binary(cameras_extrinsic_file)
>   File "C:\Users\jtoil\gaussian-splatting\scene\colmap_loader.py", line 199, in read_extrinsics_binary
>     image_name += current_char.decode("utf-8")
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 0: unexpected end of data
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "train.py", line 219, in <module>
>     training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
>   File "train.py", line 35, in training
>     scene = Scene(dataset, gaussians)
>   File "C:\Users\jtoil\gaussian-splatting\scene\__init__.py", line 44, in __init__
>     scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval)
>   File "C:\Users\jtoil\gaussian-splatting\scene\dataset_readers.py", line 141, in readColmapSceneInfo
>     cam_extrinsics = read_extrinsics_text(cameras_extrinsic_file)
>   File "C:\Users\jtoil\gaussian-splatting\scene\colmap_loader.py", line 249, in read_extrinsics_text
>     with open(path, "r") as fid:
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jtoil\\gaussian-splatting\\data\\standard\\sparse/0\\images.txt'
> ```
> 
> after converting by `convert python -s `, I run the train code and got some problem. What's the problem??
I have the same problem

**Comment by kwea123** [comment]
`'C:\\Users\\jtoil\\gaussian-splatting\\data\\standard\\sparse/0\\images.txt'`
Is this not some path issue for windows? Like the `sparse/0` is linux path format but the rest is windows. Can you try chaging that to `sparse\\0`, or use `os.path.join(..., "sparse", "0", ...)` for universal format?

**Comment by ferengi82** [comment]
had the same problem, rename the images to something like 0001.jpg, 0002.jpg ... and it works
