### ISSUE TITLE
"pip install submodules\simple-knn" doesn't work!

### ISSUE THREAD

**Issue by YJ-142150** [graphdeco-inria/gaussian-splatting#433]
```
(gaussian_splatting) lambdasix@lambdasix-MS-7D32:~/gaussian-splatting$ python train.py -s ./data/360_v2/garden
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "/home/lambdasix/gaussian-splatting/gaussian_renderer/__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'
```
I tried to train it with 360_v2 dataset. But I got thiss error message. 

So I installed  'pip install submodules\simple-knn' and 'pip install submodules\diff-gaussian-rasterization'.
But it results these error.
How can I fix this?
```
(gaussian_splatting) lambdasix@lambdasix-MS-7D32:~/gaussian-splatting$ pip install submodules\simple-knn
ERROR: Could not find a version that satisfies the requirement submodulessimple-knn (from versions: none)
ERROR: No matching distribution found for submodulessimple-knn
(gaussian_splatting) lambdasix@lambdasix-MS-7D32:~/gaussian-splatting$ pip install submodules\diff-gaussian-rasterization
ERROR: Could not find a version that satisfies the requirement submodulesdiff-gaussian-rasterization (from versions: none)
ERROR: No matching distribution found for submodulesdiff-gaussian-rasterization
```

**Comment by yuedajiong** [comment]
1.  make sure you have checkouted the submodule CORRECTLY:  git clone *** --recursive.
2. compile & install:
pip install ./submodules/diff-gaussian-rasterization/    #cd ./submodules/diff-gaussian-rasterization/; python -Bu setup.py install; cd ../../
pip install ./submodules/simple-knn/


(if you are in China,  maybe you can not checkout by '--recursive' correctly, due to GFW, you can checkout on windows (use vpn), can copy to linux.)

good luck and have fun.

**Comment by YJ-142150** [comment]
When I try `pip install ./submodules/diff-gaussian-rasterization/`, this error comes out.

```
(gaussian_splatting) lambdasix@lambdasix-MS-7D32:~/gaussian-splatting$ pip install ./submodules/diff-gaussian-rasterization/
Processing ./submodules/diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff-gaussian-rasterization
  Building wheel for diff-gaussian-rasterization (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running bdist_wheel
      /home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/torch/utils/cpp_extension.py:461: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
      copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/lambdasix/gaussian-splatting/submodules/diff-gaussian-rasterization/setup.py", line 17, in <module>
          setup(
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 369, in run
          self.run_command("build")
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 484, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/home/lambdasix/anaconda3/envs/gaussian_splatting/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 372, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.2) mismatches the version that was used to compile
      PyTorch (11.2). Please make sure to use the same CUDA versions.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects
```

**Comment by yuedajiong** [comment]
1. fix error.   CUDA version and PytorchVersion, mismatch.    
2. had better, fix warning:  we could not find ninja.  (optional)


fix error:
1.  Nvidia Driver
2.  CUDA and reltated software (here)
3.  Pytorch and related.  (here:  GPU version and match to CUDA)

[0000-cuda11.7_pytorch1.13_tinycudann_colmap.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13274507/0000-cuda11.7_pytorch1.13_tinycudann_colmap.txt)

[0000-cuda11.1_pytorch1.09_packages_human.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13274506/0000-cuda11.1_pytorch1.09_packages_human.txt)

please say thanks to me and our great GS authors.   :-)

**Comment by YJ-142150** [comment]
Thank you!!

**Comment by Aniruddhqp** [comment]
I'm getting the following error, can anyone help beyond this point 

(gaussian_splatting) C:\Windows\System32\gaussian-splatting>python train.py -s data/MetalContainer
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "C:\Windows\System32\gaussian-splatting\gaussian_renderer\__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

**Comment by feifeitu1** [comment]
> 1. fix error.   CUDA version and PytorchVersion, mismatch.
> 2. had better, fix warning:  we could not find ninja.  (optional)
> 
> fix error:
> 
> 1. Nvidia Driver
> 2. CUDA and reltated software (here)
> 3. Pytorch and related.  (here:  GPU version and match to CUDA)
> 
> [0000-cuda11.7_pytorch1.13_tinycudann_colmap.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13274507/0000-cuda11.7_pytorch1.13_tinycudann_colmap.txt)
> 
> [0000-cuda11.1_pytorch1.09_packages_human.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13274506/0000-cuda11.1_pytorch1.09_packages_human.txt)
> 
> please say thanks to me and our great GS authors. :-)

When I install TensorRT（cuda11.1），I meet some questions like this，is it because my Ubuntu is 20.04？
![Snipaste_2023-11-19_21-00-32](https://github.com/graphdeco-inria/gaussian-splatting/assets/55725526/a2e19957-6df9-4c11-92f3-c49695ff0d56)
