### ISSUE TITLE
train.py trying to access images under wrong name. "No such file or directory: 'contax/images/0001-checkpoint.jpg'"

### ISSUE THREAD

**Issue by AntonSoeffing** [graphdeco-inria/gaussian-splatting#445]
I ran the convert.py which seemed to work fine, but when I try to run the train.py I get the following error when it tries to read the camera data:

(.conda_envs/gaussian_splatting) jgaussian-splatting$ python train.py -s contax/
Optimizing 
Output folder: ./output/468bca66-b [08/11 13:12:35]
Tensorboard not available: not logging progress [08/11 13:12:35]
Reading camera 77/119Traceback (most recent call last):
  File "train.py", line 216, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "/home/_/gsplat/gaussian-splatting/scene/__init__.py", line 44, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval)
  File "/home/_/gsplat/gaussian-splatting/scene/dataset_readers.py", line 145, in readColmapSceneInfo
    cam_infos_unsorted = readColmapCameras(cam_extrinsics=cam_extrinsics, cam_intrinsics=cam_intrinsics, images_folder=os.path.join(path, reading_dir))
  File "/home/_/gsplat/gaussian-splatting/scene/dataset_readers.py", line 99, in readColmapCameras
    image = Image.open(image_path)
  File "/home/_/.conda_envs/gaussian_splatting/lib/python3.7/site-packages/PIL/Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/_/gsplat/gaussian-splatting/contax/images/0001-checkpoint.jpg'

So its trying to acces thse ****-checkpoint.jpg in the images folder... Yet my images folder only has these:

![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/26146401/93783c37-dea7-4455-9c3f-dff2065a5911)

What are the -checkpoint.jpg for? Or is that just a renaming issue that I could fix by adding -checkpoint.jpg behind all the image names?

Thanks!

**Comment by 1738970143** [comment]
I have met this question too. Could you tell me which part lead to this error? Is it the only thing we can do that changing the images' name ?

**Comment by haixianwang6** [comment]
> I have met this question too. Could you tell me which part lead to this error? Is it the only thing we can do that changing the images' name ?

I didn't make this error during my first training, but when I use another dataset, the wrong occured. My two training steps are the same.
