### ISSUE TITLE
CUDA error in _C.rasterize_gaussians(*args)

### ISSUE THREAD

**Issue by chiehwangs** [graphdeco-inria/gaussian-splatting#461]
When running code, I encountered this issue that seems to occur in the **rasterizer.** 

Is there any good solution or info for it ?

```Training progress:   2%|█▌                                                                                                      | 600/40000 [00:11<10:31, 62.37it/s, Loss=0.1793948, L1loss=0.201340, ssim=0.227071]Traceback (most recent call last):
  File "train.py", line 296, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.is_debug)
  File "train.py", line 111, in training
    render_pkg_re = render(viewpoint_cam, gaussians, grid, pipe, background, d_xyz, d_rotation, d_scaling, iteration)
  File "/media/data1/Gaussians/Gaussians/gaussian_renderer/__init__.py", line 129, in render
    cov3D_precomp=cov3D_precomp)
  File "/home/anaconda3/envs/gaussian_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/gaussian_env/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 219, in forward
    raster_settings, 
  File "/home/anaconda3/envs/gaussian_env/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 41, in rasterize_gaussians
    raster_settings,
  File "/home/anaconda3/envs/gaussian_env/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 92, in forward
    num_rendered, color, depth, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by chiehwangs** [comment]
This doesn't seem to be due to insufficient cuda memory as stackoverflow

**Comment by yuedajiong** [comment]
follow the hint to insert this line to program entry point:  os.environ['CUDA_LAUNCH_BLOCKING'] = '1'  

to avoid asynchronously-report bwtween CPU/host and GPU/device.

and paste error again? 


of course, you can try decrease the gauss point-number.

**Comment by leblond14u** [comment]
I had the same problem with a dataset I computed with COLMAP without the `convert.py` script. 
Changing the `points3D.ply` solved the problem. Computed the point cloud file with my GT data.

**Comment by TarzanZhao** [comment]
@chiehwangs Did you solve this issue? I meet the same issue

**Comment by atdrdeterminant** [comment]
I have the same issue; if anyone solved it, that might be helpful.

**Comment by BSVogler** [comment]
This happens when the input files can not be found where they are expected.

**Comment by AutonomierLong** [comment]
> I had the same problem with a dataset I computed with COLMAP without the `convert.py` script. Changing the `points3D.ply` solved the problem. Computed the point cloud file with my GT data.

Thanks a lot.

Also, I found that one can directly replace the `points3D.ply` file with `fused.ply`, which is generated by the dense reconstruction process in COLMAP. This approach also resolves the issue. Remember to change the file name.

**Comment by AutonomierLong** [comment]
> > I had the same problem with a dataset I computed with COLMAP without the `convert.py` script. Changing the `points3D.ply` solved the problem. Computed the point cloud file with my GT data.
> 
> Thanks a lot.
> 
> Also, I found that one can directly replace the `points3D.ply` file with `fused.ply`, which is generated by the dense reconstruction process in COLMAP. This approach also resolves the issue. Remember to change the file name.

Well, this scenario typically occurs when you use your own COLMAP data with known camera poses. For instance, the first time you train on a COLMAP folder that you have manually processed, you might encounter something like this:
```
Tensorboard not available: not logging progress [03/03 17:15:06]
Reading camera 71/71 [03/03 17:15:06]
Converting point3d.bin to .ply, will happen only the first time you open the scene. [03/03 17:15:06]
Loading Training Cameras [03/03 17:15:06]
Loading Test Cameras [03/03 17:15:31]
Number of points at initialisation :  1174 [03/03 17:15:31]
```

In this case, the script will convert points3d.bin into points3d.ply during the first run of train.py on this COLMAP folder. It is essential that there are some points within the points3d.bin file; otherwise, the resulting points3d.ply will be empty. If you are unable to generate any point cloud from sparse COLMAP data, you have a couple of options: either run dense COLMAP and use fused.ply as a substitute for points3d.ply, or generate a point cloud from your ground truth data.

**Comment by DREWdrew53** [comment]
I also encountered such an error, but it has been resolved now. My error occurred because "batch" or "gaussians" was running on the CPU. I hope this can be helpful to you.
