### ISSUE TITLE
eval isotropic in the code

### ISSUE THREAD

**Issue by cv-lab-x** [graphdeco-inria/gaussian-splatting#474]

**Comment by yuedajiong** [comment]
unofficial answer, maybe wrong:
    I tried different ablations, and some my new ideas(flat single gauss point and flat cloud gausspointS).

    Isotropic  vs. Anisotropic
    I initilized the components in 'scale' with fixed same value, and disable the optimized/grad, the rotation is meaningless, or dynamic same value to keep scaling, in python.
    of course, we can hardcode 'disable scale/rot' in cpp/cuda.

    FYI.

**Comment by dhuwzj** [comment]
> unofficial answer, maybe wrong: I tried different ablations, and some my new ideas(flat single gauss point and flat cloud gausspointS).
> 
> ```
> Isotropic  vs. Anisotropic
> I initilized the components in 'scale' with fixed same value, and disable the optimized/grad, the rotation is meaningless, or dynamic same value to keep scaling, in python.
> of course, we can hardcode 'disable scale/rot' in cpp/cuda.
> 
> FYI.
> ```

hi,how to let each gaussian to learn same scale,instead of to fix their scale？like your "dynamic same value".
I would be grateful if you could give me some advices.

**Comment by yuedajiong** [comment]
@dhuwzj 
1) i dont think same scales can get better performance.
2) if you just want to 'try', too many methods:
    a) modify code:   scale: vector_3 to vector_1,   ellipse to spheree
    b) simpler code:   vector_3 / 3 as real_scale_1,  simpler, no renderer code change.
    ...

**Comment by kwea123** [comment]
1. remove the `.repeat(1, 3)` on this line (so that `self._scaling` is a (N, 1) tensor)
https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L135
2. add `.repeat(1, 3)` to the this line
https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L97

in this way the scaling is expanded to (N, 3) where the 3 scales are always the same (a repeated value of the `self._scaling` parameter) no matter how you optimize.

**Comment by dhuwzj** [comment]
> 1. remove the `.repeat(1, 3)` on this line (so that `self._scaling` is a (N, 1) tensor)
>    https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L135
> 2. add `.repeat(1, 3)` to the end of this line
>    https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L97
> 
> in this way the scaling is expanded to (N, 3) where the 3 scales are always the same (a repeated value of the `self._scaling` parameter) no matter how you optimize.



> 1. remove the `.repeat(1, 3)` on this line (so that `self._scaling` is a (N, 1) tensor)
>    https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L135
> 2. add `.repeat(1, 3)` to the end of this line
>    https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L97
> 
> in this way the scaling is expanded to (N, 3) where the 3 scales are always the same (a repeated value of the `self._scaling` parameter) no matter how you optimize.



> 1. remove the `.repeat(1, 3)` on this line (so that `self._scaling` is a (N, 1) tensor)
>    https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L135
> 2. add `.repeat(1, 3)` to the end of this line
>    https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L97
> 
> in this way the scaling is expanded to (N, 3) where the 3 scales are always the same (a repeated value of the `self._scaling` parameter) no matter how you optimize.

Thanks for the suggestion, I will try it! Also thank you for the video explaining the 3D Gaussian CUDA code!
謝謝葵大！

**Comment by dhuwzj** [comment]
> 1. remove the `.repeat(1, 3)` on this line (so that `self._scaling` is a (N, 1) tensor)
>    https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L135
> 2. add `.repeat(1, 3)` to the end of this line
>    https://github.com/graphdeco-inria/gaussian-splatting/blob/2eee0e26d2d5fd00ec462df47752223952f6bf4e/scene/gaussian_model.py#L97
> 
> in this way the scaling is expanded to (N, 3) where the 3 scales are always the same (a repeated value of the `self._scaling` parameter) no matter how you optimize.

Thanks for the code suggestion, I'll try it! Also thank you for the video explaining the 3d Gaussian CUDA code!
謝謝葵大！

**Comment by niceyh888** [comment]
but I get a new problem:
(gaussian_splatting) root@autodl-container-78fb4ea487-199f48e5:~/gaussian-splatting# python train.py -s /root/autodl-tmp/open_data/tandt/train -m /root/autodl-tmp/output/tandt/train --eval
Optimizing /root/autodl-tmp/output/tandt/train
Output folder: /root/autodl-tmp/output/tandt/train [18/08 19:49:00]
Tensorboard not available: not logging progress [18/08 19:49:00]
------------LLFF HOLD------------- [18/08 19:49:02]
Reading camera 301/301 [18/08 19:49:02]
Loading Training Cameras [18/08 19:49:02]
Loading Test Cameras [18/08 19:49:06]
Number of points at initialisation :  182686 [18/08 19:49:06]
Training progress:   2%|█▍                                                                       | 600/30000 [00:14<09:55, 49.39it/s, Loss=0.2015194, Depth Loss=0.0000000]Traceback (most recent call last):
  File "/root/gaussian-splatting/train.py", line 284, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/root/gaussian-splatting/train.py", line 171, in training
    gaussians.densify_and_prune(opt.densify_grad_threshold, 0.005, scene.cameras_extent, size_threshold, radii)
  File "/root/gaussian-splatting/scene/gaussian_model.py", line 478, in densify_and_prune
    self.densify_and_split(grads, max_grad, extent)
  File "/root/gaussian-splatting/scene/gaussian_model.py", line 446, in densify_and_split
    self.densification_postfix(new_xyz, new_features_dc, new_features_rest, new_opacity, new_scaling, new_rotation,
  File "/root/gaussian-splatting/scene/gaussian_model.py", line 411, in densification_postfix
    optimizable_tensors = self.cat_tensors_to_optimizer(d)
  File "/root/gaussian-splatting/scene/gaussian_model.py", line 384, in cat_tensors_to_optimizer
    stored_state["exp_avg"] = torch.cat((stored_state["exp_avg"], torch.zeros_like(extension_tensor)),
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 1 but got size 3 for tensor number 1 in the list.
Training progress:   2%|█▍                                                                       | 600/30000 [00:14<11:49, 41.43it/s, Loss=0.2015194, Depth Loss=0.0000000]
