### ISSUE TITLE
Unable to compute metrics for model output/lego

### ISSUE THREAD

**Issue by yangqinhui0423** [graphdeco-inria/gaussian-splatting#481]
I trained it on the NeRF-synthetic dataset, and it worked, and it rendered. But when I run **python metrics.py -m output/lego**, I get an error saying **Unable to compute metrics for model output/lego**. 
![1](https://github.com/graphdeco-inria/gaussian-splatting/assets/112925344/4402ac74-b12c-432a-946b-063d263dc192)
![2](https://github.com/graphdeco-inria/gaussian-splatting/assets/112925344/32410999-f3ae-4e49-aa79-e77faaff82d2)

Has anyone encountered a similar problem and knew how to solve it?
PS：I was able to compute metrics on the Mip-NeRF360 dataset after colmap.

**Comment by RetroFuturism7** [comment]
same issue.

**Comment by curious-energy** [comment]
I made a simple change, please see #632.

**Comment by curious-energy** [comment]
> I made a simple change, please see #632.

and another reason is VRAM OOM when the progress bar is interrupted.

**Comment by LakeofRain** [comment]
> I made a simple change, please see #632.

I have solved the problem of 'Unable to compute metrics for model ' by 'pip install torchmetrics', although don't know why, but it did work well. Now I can obtain the metrics.

**Comment by LakeofRain** [comment]
I have solved the problem of 'Unable to compute metrics for model ' by 'pip install torchmetrics', although don't know why, but it does work well. Now I can obtain the metrics.

**Comment by LakeofRain** [comment]
> I made a simple change, please see #632.

I have solved the problem of 'Unable to compute metrics for model ' by 'pip install torchmetrics', although don't know why, but it does work well. Now I can obtain the metrics.

**Comment by shenqianxiang** [comment]
> 我做了一个简单的更改，请参阅#632。

你好请问你是怎么解决的

**Comment by LakeofRain** [comment]
我是因为torchvision版本不对，算lpips时vgg网络没下载下来。发自我的荣耀手机-------- 原始邮件 --------发件人： shenqianxiang ***@***.***>日期： 2024年6月26日周三 23:07收件人： graphdeco-inria/gaussian-splatting ***@***.***>抄送： LakeofRain ***@***.***>, Comment ***@***.***>主    题： Re: [graphdeco-inria/gaussian-splatting] Unable to compute metrics for model output/lego (Issue #481)

同样的问题。

你解决了吗

**Comment by biter0088** [comment]
I re-found a new environment on my computer with the torch package, ran `pip install torchmetrics` and re-executed `python metrics.py -m “/home/xiu/Learning/gaussian-splatting/output/train”` and was able to output the following results# Metric evaluation progress: 100%|█████████████████████████████████████████████████████████████████████████| 38/38 [00:39<00:00, 1.05 s/it]
# here
# SSIM : 0.8076466
# PSNR : 21.7869835
# LPIPS: 0.2143032

Translated with DeepL.com (free version)

**Comment by kellofcn** [comment]
> Same problem here `metrics.py` does not work. Tried to install torchmetrics but:
> 
> * No improvements with `pip install`
> * And the `conda install` of torchmetrics is messing with my conda environment
> 
> This is what I have after a full metrics evaluation : ![image](https://private-user-images.githubusercontent.com/79441357/316541943-019d3d86-658a-4ce6-984b-00de44dc4b3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5Nzk2MTUsIm5iZiI6MTcyODk3OTMxNSwicGF0aCI6Ii83OTQ0MTM1Ny8zMTY1NDE5NDMtMDE5ZDNkODYtNjU4YS00Y2U2LTk4NGItMDBkZTQ0ZGM0YjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA4MDE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MTAwZjgzMmIzZjg3YTZlNDBkYWIzNDc0NTIyMmI1OTY4ODk1NGMzM2U4OWM5MmQzNmE2NWY5NTdmNGRkMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vGof0n85_Yaea_3LOpAqD95f2k6lyBe3XXK6hJOvLSE) All of the metrics are NaN ...
> 
> Sometimes it also crashes :
> 
> ```
> Traceback (most recent call last):
>   File "/home/hleblond/Bureau/PhD/Depth_3DGS/metrics.py", line 150, in <module>
>     evaluate(args.model_paths)
>   File "/home/hleblond/Bureau/PhD/Depth_3DGS/metrics.py", line 116, in evaluate
>     lpipss.append(lpips(renders[idx], gts[idx], net_type='vgg'))
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/hleblond/Bureau/PhD/Depth_3DGS/lpipsPyTorch/__init__.py", line 20, in lpips
>     criterion = LPIPS(net_type, version).to(device)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/hleblond/Bureau/PhD/Depth_3DGS/lpipsPyTorch/modules/lpips.py", line 28, in __init__
>     self.lin.load_state_dict(get_state_dict(net_type, version))
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/hleblond/Bureau/PhD/Depth_3DGS/lpipsPyTorch/modules/utils.py", line 17, in get_state_dict
>     old_state_dict = torch.hub.load_state_dict_from_url(
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/hleblond/anaconda3/envs/GS/lib/python3.11/site-packages/torch/hub.py", line 770, in load_state_dict_from_url
>     return torch.load(cached_file, map_location=map_location, weights_only=weights_only)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/hleblond/anaconda3/envs/GS/lib/python3.11/site-packages/torch/serialization.py", line 1028, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/hleblond/anaconda3/envs/GS/lib/python3.11/site-packages/torch/serialization.py", line 1264, in _legacy_load
>     typed_storage._untyped_storage._set_from_file(
> RuntimeError: CUDA error: an illegal memory access was encountered
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> ```

This is what I have executed `python metrics.py -m /home/lwk/gaussian-splatting/output/980df71c-a` :
![Uploading 屏幕截图 2024-10-15 161427.png…]()

**Comment by kellofcn** [comment]
> Same problem here `metrics.py` does not work. Tried to install torchmetrics but:
> 
> * No improvements with `pip install`
> * And the `conda install` of torchmetrics is messing with my conda environment
> 
> This is what I have after a full metrics evaluation : ![image](https://private-user-images.githubusercontent.com/79441357/316541943-019d3d86-658a-4ce6-984b-00de44dc4b3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5ODA4MDksIm5iZiI6MTcyODk4MDUwOSwicGF0aCI6Ii83OTQ0MTM1Ny8zMTY1NDE5NDMtMDE5ZDNkODYtNjU4YS00Y2U2LTk4NGItMDBkZTQ0ZGM0YjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA4MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYjc2MjdmNjY3NWY0MjUwZTI4ZTA0MzMzMmM3YzY2NzQyNGQ4OWIxYjU0YzdmNzQwMzc2Nzk1NTRlZTRjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r4VE0qLZHs2NlwUq3h4VoBVgAdtdqFy2iPVGU1OzEwI) All of the metrics are NaN ...
> 
> Sometimes it also crashes :
> 
> ```
> Traceback (most recent call last):
>   File "/home/hleblond/Bureau/PhD/Depth_3DGS/metrics.py", line 150, in <module>
>     evaluate(args.model_paths)
>   File "/home/hleblond/Bureau/PhD/Depth_3DGS/metrics.py", line 116, in evaluate
>     lpipss.append(lpips(renders[idx], gts[idx], net_type='vgg'))
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/hleblond/Bureau/PhD/Depth_3DGS/lpipsPyTorch/__init__.py", line 20, in lpips
>     criterion = LPIPS(net_type, version).to(device)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/hleblond/Bureau/PhD/Depth_3DGS/lpipsPyTorch/modules/lpips.py", line 28, in __init__
>     self.lin.load_state_dict(get_state_dict(net_type, version))
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/hleblond/Bureau/PhD/Depth_3DGS/lpipsPyTorch/modules/utils.py", line 17, in get_state_dict
>     old_state_dict = torch.hub.load_state_dict_from_url(
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/hleblond/anaconda3/envs/GS/lib/python3.11/site-packages/torch/hub.py", line 770, in load_state_dict_from_url
>     return torch.load(cached_file, map_location=map_location, weights_only=weights_only)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/hleblond/anaconda3/envs/GS/lib/python3.11/site-packages/torch/serialization.py", line 1028, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/hleblond/anaconda3/envs/GS/lib/python3.11/site-packages/torch/serialization.py", line 1264, in _legacy_load
>     typed_storage._untyped_storage._set_from_file(
> RuntimeError: CUDA error: an illegal memory access was encountered
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> ```

This is what I have executed `python metrics.py -m /home/lwk/gaussian-splatting/output/980df71c-a` , metric evaluation progress is 0it , do u know why?
`Scene: /home/lwk/gaussian-splatting/output/980df71c-a
Method: ours_18000
Metric evaluation progress: 0it [00:00, ?it/s]
  SSIM :          nan
  PSNR :          nan
  LPIPS:          nan`

**Comment by HanYan012** [comment]
> > Same problem here `metrics.py` does not work. Tried to install torchmetrics but:
> > 
> > * No improvements with `pip install`
> > * And the `conda install` of torchmetrics is messing with my conda environment
> > 
> > This is what I have after a full metrics evaluation : ![image](https://private-user-images.githubusercontent.com/79441357/316541943-019d3d86-658a-4ce6-984b-00de44dc4b3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5ODA4MDksIm5iZiI6MTcyODk4MDUwOSwicGF0aCI6Ii83OTQ0MTM1Ny8zMTY1NDE5NDMtMDE5ZDNkODYtNjU4YS00Y2U2LTk4NGItMDBkZTQ0ZGM0YjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA4MjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYjc2MjdmNjY3NWY0MjUwZTI4ZTA0MzMzMmM3YzY2NzQyNGQ4OWIxYjU0YzdmNzQwMzc2Nzk1NTRlZTRjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r4VE0qLZHs2NlwUq3h4VoBVgAdtdqFy2iPVGU1OzEwI) All of the metrics are NaN ...
> > Sometimes it also crashes :
> > ```
> > Traceback (most recent call last):
> >   File "/home/hleblond/Bureau/PhD/Depth_3DGS/metrics.py", line 150, in <module>
> >     evaluate(args.model_paths)
> >   File "/home/hleblond/Bureau/PhD/Depth_3DGS/metrics.py", line 116, in evaluate
> >     lpipss.append(lpips(renders[idx], gts[idx], net_type='vgg'))
> >                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/hleblond/Bureau/PhD/Depth_3DGS/lpipsPyTorch/__init__.py", line 20, in lpips
> >     criterion = LPIPS(net_type, version).to(device)
> >                 ^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/hleblond/Bureau/PhD/Depth_3DGS/lpipsPyTorch/modules/lpips.py", line 28, in __init__
> >     self.lin.load_state_dict(get_state_dict(net_type, version))
> >                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/hleblond/Bureau/PhD/Depth_3DGS/lpipsPyTorch/modules/utils.py", line 17, in get_state_dict
> >     old_state_dict = torch.hub.load_state_dict_from_url(
> >                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/hleblond/anaconda3/envs/GS/lib/python3.11/site-packages/torch/hub.py", line 770, in load_state_dict_from_url
> >     return torch.load(cached_file, map_location=map_location, weights_only=weights_only)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/hleblond/anaconda3/envs/GS/lib/python3.11/site-packages/torch/serialization.py", line 1028, in load
> >     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/home/hleblond/anaconda3/envs/GS/lib/python3.11/site-packages/torch/serialization.py", line 1264, in _legacy_load
> >     typed_storage._untyped_storage._set_from_file(
> > RuntimeError: CUDA error: an illegal memory access was encountered
> > CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> > For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> > Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> > ```
> 
> This is what I have executed `python metrics.py -m /home/lwk/gaussian-splatting/output/980df71c-a` , metric evaluation progress is 0it , do u know why? `Scene: /home/lwk/gaussian-splatting/output/980df71c-a Method: ours_18000 Metric evaluation progress: 0it [00:00, ?it/s] SSIM : nan PSNR : nan LPIPS: nan`

Same. Did you solve this?

**Comment by tapowanliwuyun** [comment]
Same. Did you solve this?

**Comment by tapowanliwuyun** [comment]
solved！please chekck  /home/dkcs/.cache/torch/hub/checkpoints/vgg.pth ....

**Comment by micki-37** [comment]
> 我是因为torchvision版本不对，算lpips时vgg网络没下载下来。发自我的荣耀手机-------- 原始邮件 --------发件人： shenqianxiang ***@***.***>日期： 2024年6月26日周三 23:07收件人： graphdeco-inria/gaussian-splatting ***@***.***>抄送： LakeofRain ***@***.***>, Comment ***@***.***>主 题： Re: [graphdeco-inria/gaussian-splatting] Unable to compute metrics for model output/lego (Issue #481) 同样的问题。 你解决了吗 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

    我也是vgg网络没下完 重新跑metrics就显示算不了了 但并不会重新下vgg的权重 是得重新训练完重新下vgg吗

**Comment by LakeofRain** [comment]
我换了个torchvision的版本就解决了，没重新训练



在 2025-01-10 10:01:12，"micki-37" ***@***.***> 写道：

我是因为torchvision版本不对，算lpips时vgg网络没下载下来。发自我的荣耀手机-------- 原始邮件 --------发件人： shenqianxiang @.>日期： 2024年6月26日周三 23:07收件人： graphdeco-inria/gaussian-splatting @.>抄送： LakeofRain @.>, Comment @.>主 题： Re: [graphdeco-inria/gaussian-splatting] Unable to compute metrics for model output/lego (Issue #481) 同样的问题。 你解决了吗 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***>

我也是vgg网络没下完 重新跑metrics就显示算不了了 但并不会重新下vgg的权重 是得重新训练完重新下vgg吗

**Comment by king1111sadjfoisja** [comment]
> I re-found a new environment on my computer with the torch package, ran `pip install torchmetrics` and re-executed `python metrics.py -m “/home/xiu/Learning/gaussian-splatting/output/train”` and was able to output the following results:
> 
> # Metric evaluation progress: 100%|█████████████████████████████████████████████████████████████████████████| 38/38 [00:39<00:00, 1.05 s/it]
> # here
> # SSIM : 0.8076466
> # PSNR : 21.7869835
> # LPIPS: 0.2143032

Hello, how did you create this environment? Did you follow the environment.yml file? Were there any modifications?

**Comment by king1111sadjfoisja** [comment]
> 我换了个torchvision的版本就解决了，没重新训

你好，换成什么版本了方便问一下吗？谢谢

**Comment by lishuai-97** [comment]
Same issue! I installed the `torchmetrics` package with conda, but it not work for me.

**Comment by mekeny1** [comment]
> solved！please chekck /home/dkcs/.cache/torch/hub/checkpoints/vgg.pth ....

right! but i also noticed there are 2 pths totally to download(https://raw.githubusercontent.com/richzhang/PerceptualSimilarity/master/lpips/weights/v0.1/vgg.pth, https://download.pytorch.org/models/vgg16-397923af.pth), them should be downloaded by the script, but in my case, only vgg16-397923af.pth can be downloaded, but not vgg.pth. Finally, just put the two in the checkpoints

**Comment by 2229736580** [comment]
**Here is my modification process that allowed me to successfully resolve the issue. The fix primarily involved updating metrics.py to skip hidden directories generated in the file system, though I have not yet investigated the root cause of these hidden**

1. **Switching the "except" clause**  
   Initially, the script used a bare `except:` statement, which suppressed specific error messages. Replacing it with:  
   ```python
   except Exception as e:
       print("Unable to compute metrics for model", scene_dir)
       print("Error:", e)
   ```  
   allowed the code to print the actual error details.

2. **Inspecting the error message**  
   After running the updated script, the error message indicated an “[Errno 21] Is a directory” issue, meaning the code attempted to open a directory (`.ipynb_checkpoints`) as if it were an image.

3. **Confirming the hidden folder**  
   Checking the target directory indeed revealed that.

<p align="center">
  <img src="https://github.com/user-attachments/assets/f8490b48-8876-40e9-8131-df15e5bad4a8" alt="Image">
</p>

4. **Identifying the core function**  
   The issue originated in the `readImages` function, which scanned all entries in the folder, unintentionally including hidden directories.

5. **Filtering hidden folders**  
   Within `readImages`, adding conditions to skip entries starting with “.” or that are directories prevented .ipynb_checkpoints from being processed:
   ```python
   for fname in os.listdir(renders_dir):
       if fname.startswith('.') or (renders_dir / fname).is_dir():
           continue
       ...
   ```

6. **Verifying the fix**  
   After testing, the script successfully avoided "Unable to compute metrics for model" errors by properly ignoring hidden directories (`.ipynb_checkpoints`) and produced the expected output.
