### ISSUE TITLE
Pip subprocess error at local setup step

### ISSUE THREAD

**Issue by Em-2800** [graphdeco-inria/gaussian-splatting#520]
Hi everyone,

I've run into an error that I'm not sure how to fix. The error arises when I try and execute the "conda env create --file environment.yml" line. I'm executing it within Anaconda Prompt. Here is the output I get from executing that line:

```
Channels:
 - pytorch
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: \ "By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions o 
done
Installing pip dependencies: / Ran pip subprocess with arguments:
['C:\\Users\\emmet\\anaconda3\\envs\\gaussian_splatting\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\emm]
Pip subprocess output:
Processing c:\users\emmet\gaussian-splatting\submodules\diff-gaussian-rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\emmet\gaussian-splatting\submodules\diff-gaussian-rasterization\setup.py", line 29, in <module>
          extra_compile_args={"nvcc": ["-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "third_party/glm/")
        File "C:\Users\emmet\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 983,n
          library_dirs += library_paths(cuda=True)
        File "C:\Users\emmet\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1105s
          paths.append(_join_cuda_home(lib_dir))
        File "C:\Users\emmet\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 2125e
          raise EnvironmentError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

I was able to find others experiencing issues with this step in the "Pip Dependencies fail to install" #146 isssue but it appears that no one on that thread was having the same error that I was. I feel like it's worth mentioning that I'm running VS Community 2023 and not VS 2019 as this might be a source of error. Any help or insights would be greatly appreciated, thanks in advance!

**Comment by timstr** [comment]
Seeing the exact same error on Linux-64:
```
Pip subprocess error:                                                                                                                                                                                                                         
  error: subprocess-exited-with-error                                                                                                                                                                                                         
                                                                                                                                                                                                                                              
  × python setup.py egg_info did not run successfully.                                                                                                                                                                                        
  │ exit code: 1                                                                                                                                                                                                                              
  ╰─> [12 lines of output]                                                                                                                                                                                                                    
      Traceback (most recent call last):                                                                                                                                                                                                      
        File "<string>", line 36, in <module>                                                                                                                                                                                                 
        File "<pip-setuptools-caller>", line 34, in <module>                                                                                                                                                                                  
        File "/home/tim/dev/python/gaussian-splatting/submodules/diff-gaussian-rasterization/setup.py", line 29, in <module>                                                                                                                  
          extra_compile_args={"nvcc": ["-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "third_party/glm/")]})                                                                                                                 
        File "/home/tim/.miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 983, in CUDAExtension                                                                                             
          library_dirs += library_paths(cuda=True)                                                                                                                                                                                            
        File "/home/tim/.miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1098, in library_paths                                                                                            
          if (not os.path.exists(_join_cuda_home(lib_dir)) and                                                                                                                                                                                
        File "/home/tim/.miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 2125, in _join_cuda_home                                                                                          
          raise EnvironmentError('CUDA_HOME environment variable is not set. '                                                                                                                                                                
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.                                                                                                                                            
      [end of output]                                                                                                                                                                                                                         
                                                                                                                                                                                                                                              
  note: This error originates from a subprocess, and is likely not a problem with pip.                                                                                                                                                        
error: metadata-generation-failed 
```

**Comment by timstr** [comment]
I tried first installing Cuda Toolkit using NVidia's documentation, but this failed too due to a Cuda version mismatch, and it seems that packages for Cuda Toolkit 11.6 aren't listed anymore, and only 11.7 and higher are currently available to install it appears.
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

Seeing three different copies of this building wheel for diff-gaussian-rasterization and simple-knn:
```plaintext
---snip---
        File "/home/tim/.miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/tim/.miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 434, in build_extensions
          self._check_cuda_version(compiler_name, compiler_version)
        File "/home/tim/.miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 812, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.3) mismatches the version that was used to compile
      PyTorch (11.6). Please make sure to use the same CUDA versions.
```
  Sadly, as mentioned, there is no 11.6 available from NVidia's current instructions:
```plaintext
>  sudo apt-get install cuda-toolkit-11-6
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package cuda-toolkit-11-6
```
The documentation defaults to 12.3 currently. Other available version in Linux begin at 11.7:
```plaintext
cuda-toolkit-11-7
cuda-toolkit-12-0
cuda-toolkit-12-3                
cuda-toolkit-12-2
cuda-toolkit-11-8
cuda-toolkit-12
cuda-toolkit-12-1
```

I'm giving up on this. Deleted everything pulled in from installing cuda toolkit and the conda environment and won back 20 GB (!!!) of disk space.

**Comment by Em-2800** [comment]
Tismtr, yeah unfortunately I haven't been able to make any progress either since my original post. How did you go about deleting cuda from your machine?

**Comment by Liangym1225** [comment]
`conda install -c conda-forge cudatoolkit-dev`
@timstr @Em-2800 This works for me. It seems that conda doesn't install nvcc.

**Comment by ZhiyeTang** [comment]
> `conda install -c conda-forge cudatoolkit-dev`

This works good for me.

**Comment by holk-h** [comment]
I wanna use the `cuda12.x` and `python 3.8`, so I changed the `environment.yml` to:

```yml
name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cudatoolkit-dev
  - plyfile=0.8.1
  - python=3.8
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - pytorch-cuda=12.1
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
 ```
 and it's worked.

**Comment by Zhanpeng1202** [comment]
Here is my solution. [This StackOverFlow link is super helpful](https://stackoverflow.com/questions/75751907/oserror-cuda-home-environment-variable-is-not-set-please-set-it-to-your-cuda-i)

The reason why cuda_home is not set is, our Pytorch is not correctly compiled at all. We need the **exact version** e.g. from the previous version from pytorch official website.

Test by `python -c "import torch; print(torch.cuda._is_compiled())"`.
