### ISSUE TITLE
Unable to install the submodules with pip

### ISSUE THREAD

**Issue by karthikey97** [graphdeco-inria/gaussian-splatting#535]
I have been trying quite a bit to get this repo to work. I am getting stuck at the installation of the sub modules. 
Here is the error log I'm getting getting. Any help is greatly appreciated.

```
Processing ./submodules/diff-gaussian-rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: diff-gaussian-rasterization
  Building wheel for diff-gaussian-rasterization (setup.py): started
  Building wheel for diff-gaussian-rasterization (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [94 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
      copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
      running build_ext
      /home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/utils/cpp_extension.py:398: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'diff_gaussian_rasterization._C' extension
      creating /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38
      creating /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/cuda_rasterizer
      Emitting ninja build file /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/build.ninja...
      Compiling objects...
      Using envvar MAX_JOBS (1) as the number of workers...
      [1/5] /home/sp53252/anaconda3/pkgs/cuda-nvcc-11.8.89-0/bin/nvcc  -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include/TH -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include/THC -I/home/sp53252/anaconda3/pkgs/cuda-nvcc-11.8.89-0/include -I/home/sp53252/anaconda3/envs/gsplat/include/python3.8 -c -c /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/backward.cu -o /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/cuda_rasterizer/backward.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17
      /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/auxiliary.h(151): warning #177-D: variable "p_proj" was declared but never referenced
      
      [2/5] /home/sp53252/anaconda3/pkgs/cuda-nvcc-11.8.89-0/bin/nvcc  -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include/TH -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include/THC -I/home/sp53252/anaconda3/pkgs/cuda-nvcc-11.8.89-0/include -I/home/sp53252/anaconda3/envs/gsplat/include/python3.8 -c -c /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/forward.cu -o /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/cuda_rasterizer/forward.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17
      /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/auxiliary.h(151): warning #177-D: variable "p_proj" was declared but never referenced
      
      [3/5] /home/sp53252/anaconda3/pkgs/cuda-nvcc-11.8.89-0/bin/nvcc  -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include/TH -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include/THC -I/home/sp53252/anaconda3/pkgs/cuda-nvcc-11.8.89-0/include -I/home/sp53252/anaconda3/envs/gsplat/include/python3.8 -c -c /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/rasterizer_impl.cu -o /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/cuda_rasterizer/rasterizer_impl.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17
      FAILED: /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/cuda_rasterizer/rasterizer_impl.o
      /home/sp53252/anaconda3/pkgs/cuda-nvcc-11.8.89-0/bin/nvcc  -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include/TH -I/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/include/THC -I/home/sp53252/anaconda3/pkgs/cuda-nvcc-11.8.89-0/include -I/home/sp53252/anaconda3/envs/gsplat/include/python3.8 -c -c /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/rasterizer_impl.cu -o /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/cuda_rasterizer/rasterizer_impl.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17
      /home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/auxiliary.h(151): warning #177-D: variable "p_proj" was declared but never referenced
      
      /usr/include/cub/detail/device_synchronize.cuh(53): error: identifier "__cudaDeviceSynchronizeDeprecationAvoidance" is undefined
      
      1 error detected in the compilation of "/home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/rasterizer_impl.cu".
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '1']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/sp53252/gaussian-splatting/submodules/diff-gaussian-rasterization/setup.py", line 17, in <module>
          setup(
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/sp53252/anaconda3/envs/gsplat/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects
'''

**Comment by pro90** [comment]
I have the same problem. 

Tried it on Ubuntu 22.04 with CUDA 11.8 and with a cuda 11.7 docker container - always the same error while running ```conda env create --file environment.yml```

**Comment by avinabsaha** [comment]
Just follow the steps here in this colab : 

https://colab.research.google.com/github/camenduru/gaussian-splatting-colab/blob/main/gaussian_splatting_colab.ipynb

**Comment by GrapeApe230** [comment]
I am running into the same issue but in Windows

**Comment by pjustus10** [comment]
> Just follow the steps here in this colab :
> 
> https://colab.research.google.com/github/camenduru/gaussian-splatting-colab/blob/main/gaussian_splatting_colab.ipynb

This wasn't very helpful for a windows user.

**Comment by avinabsaha** [comment]
Yes, this worked on Linux! Sadly, we do not have Windows systems to test this.

**Comment by pjustus10** [comment]
Managed to resolve this issue.

It it fails to install the submodules, using either of these commands will solve the issue; choose the one according to the Visual Studio you installed
VS 2022: conda install -c conda-forge vs2022_win-64 
VS 2019: conda install -c conda-forge vs2019_win-64

**Comment by maxolib** [comment]
> Managed to resolve this issue.
> 
> It it fails to install the submodules, using either of these commands will solve the issue; choose the one according to the Visual Studio you installed VS 2022: conda install -c conda-forge vs2022_win-64 VS 2019: conda install -c conda-forge vs2019_win-64

This can solve the issue for me. My OS is Windows and it can install the environment successfully.

**Comment by NaG14157** [comment]
> Managed to resolve this issue.
> 
> It it fails to install the submodules, using either of these commands will solve the issue; choose the one according to the Visual Studio you installed VS 2022: conda install -c conda-forge vs2022_win-64 VS 2019: conda install -c conda-forge vs2019_win-64

what is this code effect，can you explain it，thank you

**Comment by karthikey97** [comment]
Found two solutions to resolve this

### 1. Easy workaround
Install the wheels provided in the [colab link](https://colab.research.google.com/github/camenduru/gaussian-splatting-colab/blob/main/gaussian_splatting_colab.ipynb) as suggested by @avinabsaha in the thread above.

### 2. Probably the correct method (at least on Ubuntu 20.04)
Use the correct versions of compilers ie. gcc-10 and g++-10. 
You can do this by doing the following steps:

```
sudo apt-get install gcc-10 g++-10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
```

I also observed it doesn't work with nvcc version 11.5 and worked with version 11.6.
This need not be installed globally and can be done within your conda environment like this:
```
conda install cuda -c nvidia/label/cuda-11.6
```

**Comment by karthikey97** [comment]
Found two solutions to resolve this
### 1. Easy workaround

Install the wheels provided in the [colab link](https://colab.research.google.com/github/camenduru/gaussian-splatting-colab/blob/main/gaussian_splatting_colab.ipynb) as suggested by @avinabsaha in the thread above.
### 2. Probably the correct method (at least on Ubuntu 20.04)
Use the correct versions of compilers ie. gcc-10 and g++-10.
You can do this by doing the following steps:
```
sudo apt-get install gcc-10 g++-10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
```
I also observed it doesn't work with nvcc version 11.5 and worked with version 11.6.
The cudatoolkit=11.6 included in the environemnt.yml file provided in the repo does not install nvcc. 
This can be fixed by running the following command within your conda environment. 
(Installing the cudatoolkit from Nvidia's official channel fixes the issue)
```
conda install cuda -c nvidia/label/cuda-11.6
```

**Comment by lihaolin88** [comment]
For Linux user, this link: https://stackoverflow.com/questions/28977455/why-cant-c-find-glm-headers may help to solve the problem about diff_gaussian_rasterization install error

**Comment by goxq** [comment]
> sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100

thanks a lot this helps

**Comment by lrxsxdl** [comment]
> For Linux user, this link: https://stackoverflow.com/questions/28977455/why-cant-c-find-glm-headers may help to solve the problem about diff_gaussian_rasterization install error

It works for me.  I execute apt-get install libglm-dev.
