### ISSUE TITLE
Colab notebook no longer working

### ISSUE THREAD

**Issue by fasteinke** [graphdeco-inria/gaussian-splatting#554]
Have raised this with camenduru, but will note it here as well ... as of just today, the train.py module fails, with this error:

Traceback (most recent call last):
File "/content/gaussian-splatting/train.py", line 16, in
from gaussian_renderer import render, network_gui
File "/content/gaussian-splatting/gaussian_renderer/init.py", line 14, in
from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
File "/usr/local/lib/python3.10/dist-packages/diff_gaussian_rasterization/init.py", line 15, in
from . import _C
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

**Comment by NagaPadma** [comment]
I have the same issue.

**Comment by pavelgolikov** [comment]
Same here.

**Comment by NagaPadma** [comment]
I assume that the cause would be the mismatch of the cuda versions of submodules, and when I reinstall them, it worked fine now, but it took several minutes for reinstalling them.

!pip install -U submodules/diff-gaussian-rasterization
!pip install -U submodules/simple-knn

follow this https://github.com/camenduru/gaussian-splatting-colab/issues/8#issuecomment-1861911077

**Comment by dzeitman** [comment]
10/21/2024 -- I attempted to run the colab notebook - no dice.  tons of version dependency issues.   Does anyone have a working colab version.   I
