### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by liwd190019** [graphdeco-inria/gaussian-splatting#599]
Hi. I had some horrible time trying to run code locally.
The error is: RuntimeError: `CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling 'cublasCreate(handle)'`
```
(gaussian_splatting) root@b6b37a8b8f14:/data/gaussian-splatting# python train.py -s /dataset/NeRF/nerf_synthetic/lego/
Optimizing 
Output folder: ./output/2673b61b-a [06/01 04:52:03]
Tensorboard not available: not logging progress [06/01 04:52:03]
Found transforms_train.json file, assuming Blender data set! [06/01 04:52:03]
Reading Training Transforms [06/01 04:52:03]
Reading Test Transforms [06/01 04:52:12]
Loading Training Cameras [06/01 04:52:26]
cameras.py executed [06/01 04:52:26]
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "/data/gaussian-splatting/scene/__init__.py", line 73, in __init__
    self.train_cameras[resolution_scale] = cameraList_from_camInfos(scene_info.train_cameras, resolution_scale, args)
  File "/data/gaussian-splatting/utils/camera_utils.py", line 58, in cameraList_from_camInfos
    camera_list.append(loadCam(args, id, c, resolution_scale))
  File "/data/gaussian-splatting/utils/camera_utils.py", line 52, in loadCam
    image_name=cam_info.image_name, uid=id, data_device=args.data_device)
  File "/data/gaussian-splatting/scene/cameras.py", line 58, in __init__
    self.full_proj_transform = (self.world_view_transform.unsqueeze(0).bmm(self.projection_matrix.unsqueeze(0))).squeeze(0)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
```

I think I followed the steps described in README, which is:
```
conda env create --file environment.yml
conda activate gaussian-splatting
python train.py -s /dataset/NeRF/nerf_synthetic/lego/ #/dataset/NeRF/nerf_synthetic/lego is the address of the dataset
```

Does everyone generally do the same steps shown above? I'm not sure what I did is 100% correct... 

I have searched this error for a long time, and it seems this error can happen from multiple aspects. I'm trying to clarify my specific Runtime Error belongs to "hardware side" or "software side".

Any suggestion will be highly appreciated.

**Comment by Snosixtyboo** [comment]
Please consider this post, though I am not sure if that is your actual issue. Consider researching the particular error message, it is not part of code that was written by us.
https://discuss.pytorch.org/t/cuda-error-cublas-status-not-initialized-when-calling-cublascreate-handle/125450
