### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by Gurutva** [graphdeco-inria/gaussian-splatting#637]
Getting the following error when trying for less number of input images like 3 or 4 images.

Optimizing output/nerf_llff_SPARSE_input_DENSE_colmap_KEEP_SAFE\set04\leaves
Output folder: output/nerf_llff_SPARSE_input_DENSE_colmap_KEEP_SAFE\set04\leaves [26/01 05:14:09]
Tensorboard not available: not logging progress [26/01 05:14:09]
Found transforms_train.json file, assuming Blender data set! [26/01 05:14:09]
Reading Training Transforms [26/01 05:14:09]
Reading Test Transforms [26/01 05:14:09]
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "C:\Gurutva\Nerf_exp\gaussian_splat\gaussian-splatting\scene\__init__.py", line 47, in __init__
    scene_info = sceneLoadTypeCallbacks["Blender"](args.source_path, args.white_background, args.eval)
  File "C:\Gurutva\Nerf_exp\gaussian_splat\gaussian-splatting\scene\dataset_readers.py", line 231, in readNerfSyntheticInfo
    nerf_normalization = getNerfppNorm(train_cam_infos)
  File "C:\Gurutva\Nerf_exp\gaussian_splat\gaussian-splatting\scene\dataset_readers.py", line 61, in getNerfppNorm
    center, diagonal = get_center_and_diag(cam_centers)
  File "C:\Gurutva\Nerf_exp\gaussian_splat\gaussian-splatting\scene\dataset_readers.py", line 47, in get_center_and_diag
    cam_centers = np.hstack(cam_centers)
  File "<__array_function__ internals>", line 6, in hstack
  File "C:\Users\USER\anaconda3\envs\gaussian_splatting\lib\site-packages\numpy\core\shape_base.py", line 345, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by Snosixtyboo** [comment]
Can you print the train_cam_infos at the corresponding location in ```dataset_readers.py```?
