### ISSUE TITLE
Python is unable to load the 'diff_Gaussian refinement' module_ C extension on win10

### ISSUE THREAD

**Issue by salier** [graphdeco-inria/gaussian-splatting#639]
i use  win10 cuda1.8 pytouch 2.1.2 Python 3.7.12 VS2019
python train.py -s <path to COLMAP or NeRF Synthetic dataset> error

(gaussian_splatting) PS D:\gaussian-splatting> python train.py -s D:\gaussian-splatting\data\01
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "D:\gaussian-splatting\gaussian_renderer\__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
  File "D:\conda3\envs\gaussian_splatting\lib\site-packages\diff_gaussian_rasterization\__init__.py", line 15, in <module>
    from . import _C
ImportError: DLL load failed: 找不到指定的程序。
(gaussian_splatting) PS D:\gaussian-splatting> pip show diff_gaussian_rasterization
Name: diff_gaussian_rasterization
Version: 0.0.0
Summary:
Home-page:
Author:
Author-email:
License:
Location: d:\conda3\envs\gaussian_splatting\lib\site-packages
Requires:
Required-by:
(gaussian_splatting) PS D:\gaussian-splatting> python setup.py build_ext --inplace
D:\conda3\envs\gaussian_splatting\python.exe: can't open file 'setup.py': [Errno 2] No such file or directory
(gaussian_splatting) PS D:\gaussian-splatting> 
![image](https://github.com/graphdeco-inria/gaussian-splatting/assets/28691601/bef034e0-0465-46b5-a267-56972804a20f)

**Comment by evearmadillo** [comment]
Hi @salier , have you managed to resolve your issue? I have a similar one, but no luck yet

**Comment by MurphyMiao** [comment]
I fixed it. Delete the current environment and recreate it
`conda env remove -n <environment_name>`
`conda create -n <new_environment_name>`
