### ISSUE TITLE
train.py errors

### ISSUE THREAD

**Issue by kencessna** [graphdeco-inria/gaussian-splatting#677]
Hi, no matter what input I choose, I`ll always get the following:

Optimizing
Output folder: ./output/40f86172-f [27/02 15:14:32]
Tensorboard not available: not logging progress [27/02 15:14:32]
Reading camera 2/2 [27/02 15:14:33]
Converting point3d.bin to .ply, will happen only the first time you open the scene. [27/02 15:14:33]
Loading Training Cameras [27/02 15:14:33]
Loading Test Cameras [27/02 15:14:58]
Number of points at initialisation :  1059 [27/02 15:14:58]
Training progress:   0%|                                                                     | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 219, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 92, in training
    loss = (1.0 - opt.lambda_dssim) * Ll1 + opt.lambda_dssim * (1.0 - ssim(image, gt_image))
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Training progress:   0%|

I really need help, thanks, Can

**Comment by jaco001** [comment]
Only two cameras? Are you sure that your data is not corrupted?

**Comment by kencessna** [comment]
Thanks for your quick answer! I tried 3 different sets and convert.py doesn`t give me any errors! I`ll try another one just to be sure! :)

**Comment by kencessna** [comment]
I tried another set! That´s the outcome of  convert.py:

I20240228 10:13:33.380679 19260 undistortion.cc:210] Undistorting image [499/499]
I20240228 10:13:33.412593 19260 undistortion.cc:223] Writing reconstruction...
I20240228 10:13:35.776777 19260 undistortion.cc:228] Writing configuration...
I20240228 10:13:35.808691 19260 undistortion.cc:232] Writing scripts...
I20240228 10:13:35.837613 19260 timer.cc:91] Elapsed time: 0.307 [minutes]
Done.

And thats the training.py outcome:

Output folder: ./output/404ab7b1-e [28/02 10:14:59]
Tensorboard not available: not logging progress [28/02 10:14:59]
Reading camera 499/499 [28/02 10:15:03]
Converting point3d.bin to .ply, will happen only the first time you open the scene. [28/02 10:15:03]
Loading Training Cameras [28/02 10:15:05]
Loading Test Cameras [28/02 10:15:40]
Number of points at initialisation :  248303 [28/02 10:15:41]
Training progress:   0%|                                                                           | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 219, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 92, in training
    loss = (1.0 - opt.lambda_dssim) * Ll1 + opt.lambda_dssim * (1.0 - ssim(image, gt_image))
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Training progress:   0%|

Thanks for your help, Can

**Comment by kencessna** [comment]
Solved! I used the wrong python version due to some other errors! I installed everything new and fresh and it works perfectly! :) Sorry!

**Comment by hm123450** [comment]
> Thanks for your quick answer! I tried 3 different sets and convert.py doesn`t give me any errors! I`ll try another one just to be sure! :)
hello, I meet some problem similiar with you, could you help me

**Comment by hm123450** [comment]
> Hi, I set up 2 different Computer and both work fine until this point. No matter what input I choose, I`ll always get the following:
> 
> Optimizing Output folder: ./output/40f86172-f [27/02 15:14:32] Tensorboard not available: not logging progress [27/02 15:14:32] Reading camera 2/2 [27/02 15:14:33] Converting point3d.bin to .ply, will happen only the first time you open the scene. [27/02 15:14:33] Loading Training Cameras [27/02 15:14:33] Loading Test Cameras [27/02 15:14:58] Number of points at initialisation : 1059 [27/02 15:14:58] Training progress: 0%| | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last): File "train.py", line 219, in training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from) File "train.py", line 92, in training loss = (1.0 - opt.lambda_dssim) * Ll1 + opt.lambda_dssim * (1.0 - ssim(image, gt_image)) TypeError: unsupported operand type(s) for -: 'float' and 'NoneType' Training progress: 0%|
> 
> I really need help, thanks, Can

My reading camera is only 2 but I have 72 images. There is something wrong when I use convert.py. I don't know how can you solve the problem. You say that you try another set and it works. Could you tell me how can you solve the problem? Thank you so much.

**Comment by kencessna** [comment]
Hi hm123450, do you have the same errors or alway only 2 cameras converted? I figured out everything I film with my mobile has this problem and when I use drone videos from youtube it works perfect! Later today I want to make atest with  a real camera and if this gives me good output I`ll be sure it has to do with my mobile. maybe it is to blurry, wrong lens, whatever! I´ll loet you know!

**Comment by kencessna** [comment]
I made nearly a same movie with my Nikon D7000 and I got 296 cameras! So as I mentioned it has something to do making sourcematerial with a mobile phone in my case!
