### ISSUE TITLE
ImportError: DLL load failed while importing _C

### ISSUE THREAD

**Issue by shiwangyan** [graphdeco-inria/gaussian-splatting#701]
D:\3DGS\gaussian-splatting>python train.py -s data -m data/output
Traceback (most recent call last):
  File "D:\3DGS\gaussian-splatting\train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "D:\3DGS\gaussian-splatting\gaussian_renderer\__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
  File "D:\anaconda3\lib\site-packages\diff_gaussian_rasterization\__init__.py", line 15, in <module>
    from . import _C
ImportError: DLL load failed while importing _C: The specified program cannot be found.

It was working fine previously, but suddenly this error occurred.

**Comment by gaetan-landreau** [comment]
Hi !

**Comment by gaetan-landreau** [comment]
Hi !

**Comment by gaetan-landreau** [comment]
Hi ! 
Not 100% sure since I don't know your env. setting but I will go for a torch version update/downgrade you've made. If you do so, you would need to compile again the submodule `diff_gaussian_rasterization` (as well as the `simple-knn one`) 
Running 
```python
pip install -e submodules/* 
```
at the project root should do the trick 🙂
