### ISSUE TITLE
Submodules do not compile

### ISSUE THREAD

**Issue by AndreM417** [graphdeco-inria/gaussian-splatting#724]
I've been trying to install the Gaussian Splatting repository on Windows 10 with an RTX 4090 since yesterday. I have tried a lot of combinations of different CUDA versions and workarounds.
When I follow the standard installation instructions (with CUDA 11.8 SDK or CUDA 11.7 SDK, even if the 11.6 toolkit is loaded via environment.yml), I get the following error message:
```
Pip subprocess output:
Processing c:\users\a\desktop\gaussian-splatting\submodules\diff-gaussian-rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Processing c:\users\a\desktop\gaussian-splatting\submodules\simple-knn
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: diff_gaussian_rasterization, simple_knn
  Building wheel for diff_gaussian_rasterization (setup.py): started
  Building wheel for diff_gaussian_rasterization (setup.py): finished with status 'error'
  Running setup.py clean for diff_gaussian_rasterization
  Building wheel for simple_knn (setup.py): started
  Building wheel for simple_knn (setup.py): finished with status 'error'
  Running setup.py clean for simple_knn
Failed to build diff_gaussian_rasterization simple_knn
Installing collected packages: simple_knn, diff_gaussian_rasterization
  Running setup.py install for simple_knn: started
  Running setup.py install for simple_knn: finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\A\Desktop\gaussian-splatting\submodules\diff-gaussian-rasterization\setup.py", line 32, in <module>
          'build_ext': BuildExtension
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 172, in setup
          ok = dist.parse_command_line()
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 475, in parse_command_line
          args = self._parse_command_opts(parser, args)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 863, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 534, in _parse_command_opts
          cmd_class = self.get_command_class(command)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 710, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 208, in load
          module = import_module(match.group('module'))
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\importlib\__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 728, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\bdist_wheel.py", line 28, in <module>
          from .metadata import pkginfo_to_metadata
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\metadata.py", line 16, in <module>
          from .vendored.packaging.requirements import Requirement
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\requirements.py", line 7, in <module>
          from ._parser import parse_requirement as _parse_requirement
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\_parser.py", line 10, in <module>
          from ._tokenizer import DEFAULT_RULES, Tokenizer
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\_tokenizer.py", line 6, in <module>
          from .specifiers import Specifier
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\specifiers.py", line 16, in <module>
          from .utils import canonicalize_version
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\utils.py", line 8, in <module>
          from .tags import Tag, parse_tag
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\tags.py", line 26, in <module>
          from . import _manylinux, _musllinux
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\_manylinux.py", line 171, in <module>
          def _get_glibc_version() -> Tuple[int, int]:
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\functools.py", line 490, in lru_cache
          raise TypeError('Expected maxsize to be an integer or None')
      TypeError: Expected maxsize to be an integer or None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\A\Desktop\gaussian-splatting\submodules\simple-knn\setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 172, in setup
          ok = dist.parse_command_line()
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 475, in parse_command_line
          args = self._parse_command_opts(parser, args)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 863, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 534, in _parse_command_opts
          cmd_class = self.get_command_class(command)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 710, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 208, in load
          module = import_module(match.group('module'))
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\importlib\__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 728, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\bdist_wheel.py", line 28, in <module>
          from .metadata import pkginfo_to_metadata
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\metadata.py", line 16, in <module>
          from .vendored.packaging.requirements import Requirement
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\requirements.py", line 7, in <module>
          from ._parser import parse_requirement as _parse_requirement
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\_parser.py", line 10, in <module>
          from ._tokenizer import DEFAULT_RULES, Tokenizer
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\_tokenizer.py", line 6, in <module>
          from .specifiers import Specifier
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\specifiers.py", line 16, in <module>
          from .utils import canonicalize_version
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\utils.py", line 8, in <module>
          from .tags import Tag, parse_tag
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\tags.py", line 26, in <module>
          from . import _manylinux, _musllinux
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\_manylinux.py", line 171, in <module>
          def _get_glibc_version() -> Tuple[int, int]:
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\functools.py", line 490, in lru_cache
          raise TypeError('Expected maxsize to be an integer or None')
      TypeError: Expected maxsize to be an integer or None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple_knn
  error: subprocess-exited-with-error

  × Running setup.py install for simple_knn did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
      running install
      C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      running build
      running build_ext
      C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\A\Desktop\gaussian-splatting\submodules\simple-knn\setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\command\install.py", line 78, in run
          return orig.install.run(self)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\install.py", line 697, in run
          self.run_command('build')
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
          return Version(version)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> simple_knn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

If I add the Visual Studio Path for the `cl.exe` as described in the FAQ, the error changes as follows:
```
Pip subprocess output:
Processing c:\users\a\desktop\gaussian-splatting\submodules\diff-gaussian-rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Processing c:\users\a\desktop\gaussian-splatting\submodules\simple-knn
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: diff_gaussian_rasterization, simple_knn
  Building wheel for diff_gaussian_rasterization (setup.py): started
  Building wheel for diff_gaussian_rasterization (setup.py): finished with status 'error'
  Running setup.py clean for diff_gaussian_rasterization
  Building wheel for simple_knn (setup.py): started
  Building wheel for simple_knn (setup.py): finished with status 'error'
  Running setup.py clean for simple_knn
Failed to build diff_gaussian_rasterization simple_knn
Installing collected packages: simple_knn, diff_gaussian_rasterization
  Running setup.py install for simple_knn: started
  Running setup.py install for simple_knn: finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\A\Desktop\gaussian-splatting\submodules\diff-gaussian-rasterization\setup.py", line 32, in <module>
          'build_ext': BuildExtension
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 172, in setup
          ok = dist.parse_command_line()
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 475, in parse_command_line
          args = self._parse_command_opts(parser, args)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 863, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 534, in _parse_command_opts
          cmd_class = self.get_command_class(command)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 710, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 208, in load
          module = import_module(match.group('module'))
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\importlib\__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 728, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\bdist_wheel.py", line 28, in <module>
          from .metadata import pkginfo_to_metadata
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\metadata.py", line 16, in <module>
          from .vendored.packaging.requirements import Requirement
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\requirements.py", line 7, in <module>
          from ._parser import parse_requirement as _parse_requirement
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\_parser.py", line 10, in <module>
          from ._tokenizer import DEFAULT_RULES, Tokenizer
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\_tokenizer.py", line 6, in <module>
          from .specifiers import Specifier
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\specifiers.py", line 16, in <module>
          from .utils import canonicalize_version
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\utils.py", line 8, in <module>
          from .tags import Tag, parse_tag
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\tags.py", line 26, in <module>
          from . import _manylinux, _musllinux
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\_manylinux.py", line 171, in <module>
          def _get_glibc_version() -> Tuple[int, int]:
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\functools.py", line 490, in lru_cache
          raise TypeError('Expected maxsize to be an integer or None')
      TypeError: Expected maxsize to be an integer or None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\A\Desktop\gaussian-splatting\submodules\simple-knn\setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 172, in setup
          ok = dist.parse_command_line()
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 475, in parse_command_line
          args = self._parse_command_opts(parser, args)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 863, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 534, in _parse_command_opts
          cmd_class = self.get_command_class(command)
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 710, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 208, in load
          module = import_module(match.group('module'))
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\importlib\__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 728, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\bdist_wheel.py", line 28, in <module>
          from .metadata import pkginfo_to_metadata
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\metadata.py", line 16, in <module>
          from .vendored.packaging.requirements import Requirement
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\requirements.py", line 7, in <module>
          from ._parser import parse_requirement as _parse_requirement
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\_parser.py", line 10, in <module>
          from ._tokenizer import DEFAULT_RULES, Tokenizer
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\_tokenizer.py", line 6, in <module>
          from .specifiers import Specifier
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\specifiers.py", line 16, in <module>
          from .utils import canonicalize_version
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\utils.py", line 8, in <module>
          from .tags import Tag, parse_tag
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\tags.py", line 26, in <module>
          from . import _manylinux, _musllinux
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\wheel\vendored\packaging\_manylinux.py", line 171, in <module>
          def _get_glibc_version() -> Tuple[int, int]:
        File "C:\Users\A\.conda\envs\gaussian_splatting\lib\functools.py", line 490, in lru_cache
          raise TypeError('Expected maxsize to be an integer or None')
      TypeError: Expected maxsize to be an integer or None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple_knn
  error: subprocess-exited-with-error

  × Running setup.py install for simple_knn did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running install
      C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      running build
      running build_ext
      C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:813: UserWarning: The detected CUDA version (11.7) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'simple_knn._C' extension
      creating build
      creating build\temp.win-amd64-cpython-37
      creating build\temp.win-amd64-cpython-37\Release
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\torch\include -IC:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\TH -IC:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -IC:\Users\A\.conda\envs\gaussian_splatting\include -IC:\Users\A\.conda\envs\gaussian_splatting\Include /EHsc /Tpext.cpp /Fobuild\temp.win-amd64-cpython-37\Release\ext.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc /wd4624 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      ext.cpp
      C:\Users\A\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuda.h(5): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "cstdint": No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> simple_knn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

I also tried this workaround: https://github.com/graphdeco-inria/gaussian-splatting/issues/297#issuecomment-1758813369 - the installation of the submodules then works, but I then get an error message when executing that the CUDA version is not compatible with the RTX 4090 (regarding smXX version).

I played around a little more with different CUDA versions, but in the best case I still had the following error, which was also described in the following issue with missing DLLs: https://github.com/graphdeco-inria/gaussian-splatting/issues/701

I have now also tried the installation on another computer (with RTX 2060 Super), but it doesn't work either.

Does anyone have any tips as to why this might be and how I can get it installed after all?

**Comment by AndreM417** [comment]
After I saw #727, I tried to install it again as in this description (https://github.com/graphdeco-inria/gaussian-splatting/issues/297#issuecomment-1758813369) without `conda install` and instead using `pip`. 

However, I adapted the Pytorch installation command with regard to the CUDA version and replaced it with `pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117`. I had installed CUDA 11.7 at the same time. Now it works for me.
