### ISSUE TITLE
Fail to run the optimizer

### ISSUE THREAD

**Issue by libingzeng** [graphdeco-inria/gaussian-splatting#76]
Hi there,

Thank you so much for your excellent work!

I am trying to run the optimizer like this:
`python train.py -s data/db/playroom -m output/playroom
`

The output log is as follows:
```
Reading camera 225/225 [07/08 02:12:50]
Loading Training Cameras [07/08 02:12:50]
Loading Test Cameras [07/08 02:14:07]
Number of points at initialisation :  37005 [07/08 02:14:11]
Training progress:   0%|                            | 0/30000 [00:00<?, ?it/s]
Connected by ('127.0.0.1', 60074) [07/08 02:14:13]
**Floating point exception (core dumped)**
```
I have been stuck in this situation for quite some time, and I would greatly appreciate any suggestions or advice you may have.

**Comment by libingzeng** [comment]
I inserted some logs into the function int **CudaRasterizer::Rasterizer::forward()** and observed that the **_C.rasterize_gaussians(*args)** function was called four times. However, on the fifth invocation, memory-related errors occurred, specifically with **binning_chunk_size** and **num_rendered** having values of **18446744043532756609** and **1257366468**, respectively.

Here is the detailed log for reference:
```
(gaussian_splatting) libingzeng@csce-7kyhpy2:~/Documents/Research/gaussian-splatting$ python train.py -s /home/grads/l/libingzeng/Documents/Data/gaussian-splatting/data/db/playroom -m /home/grads/l/libingzeng/Documents/Data/gaussian-splatting/output/playroom
Optimizing /home/grads/l/libingzeng/Documents/Data/gaussian-splatting/output/playroom
Output folder: /home/grads/l/libingzeng/Documents/Data/gaussian-splatting/output/playroom [09/08 15:24:10]
Tensorboard not available: not logging progress [09/08 15:24:10]
Reading camera 225/225 [09/08 15:24:20]
Loading Training Cameras [09/08 15:24:20]
Loading Test Cameras [09/08 15:26:25]
Number of points at initialisation :  37005 [09/08 15:26:26]
Training progress:   0%|                                                                                                                               | 0/30000 [00:00<?, ?it/s]> /home/grads/l/libingzeng/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py(93)forward()
-> num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args) [09/08 15:26:29]
(Pdb) c
lbz---------------------------------
lbz----CudaRasterizer::Rasterizer::forward-----------------------------
lbz----CudaRasterizer::Rasterizer::forward-----------------2------------
lbz----CudaRasterizer::Rasterizer::forward-----------------3------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4------geomState.point_offsets------0x7f18662a5e80
lbz----CudaRasterizer::Rasterizer::forward-----------------4------P------37005
lbz----CudaRasterizer::Rasterizer::forward-----------------4------cudaMemcpyDeviceToHost------2
lbz----CudaRasterizer::Rasterizer::forward-----------------4.1------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------binning_chunk_size------129
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------num_rendered------0
lbz----CudaRasterizer::Rasterizer::forward-----------------4.5------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4.6------------
lbz----CudaRasterizer::Rasterizer::forward-----------------5------------
lbz----CudaRasterizer::Rasterizer::forward-----------------6------------
lbz----CudaRasterizer::Rasterizer::forward-----------------7------------
> /home/grads/l/libingzeng/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py(93)forward()
-> num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args) [09/08 15:26:57]
(Pdb) c
lbz---------------------------------
lbz----CudaRasterizer::Rasterizer::forward-----------------------------
lbz----CudaRasterizer::Rasterizer::forward-----------------2------------
lbz----CudaRasterizer::Rasterizer::forward-----------------3------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4------geomState.point_offsets------0x7f1854900280
lbz----CudaRasterizer::Rasterizer::forward-----------------4------P------37005
lbz----CudaRasterizer::Rasterizer::forward-----------------4------cudaMemcpyDeviceToHost------2
lbz----CudaRasterizer::Rasterizer::forward-----------------4.1------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------binning_chunk_size------129
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------num_rendered------0
lbz----CudaRasterizer::Rasterizer::forward-----------------4.5------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4.6------------
lbz----CudaRasterizer::Rasterizer::forward-----------------5------------
lbz----CudaRasterizer::Rasterizer::forward-----------------6------------
lbz----CudaRasterizer::Rasterizer::forward-----------------7------------
> /home/grads/l/libingzeng/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py(93)forward()
-> num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args) [09/08 15:26:59]
(Pdb) c
lbz---------------------------------
lbz----CudaRasterizer::Rasterizer::forward-----------------------------
lbz----CudaRasterizer::Rasterizer::forward-----------------2------------
lbz----CudaRasterizer::Rasterizer::forward-----------------3------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4------geomState.point_offsets------0x7f18672b2080
lbz----CudaRasterizer::Rasterizer::forward-----------------4------P------37005
lbz----CudaRasterizer::Rasterizer::forward-----------------4------cudaMemcpyDeviceToHost------2
lbz----CudaRasterizer::Rasterizer::forward-----------------4.1------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------binning_chunk_size------129
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------num_rendered------0
lbz----CudaRasterizer::Rasterizer::forward-----------------4.5------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4.6------------
lbz----CudaRasterizer::Rasterizer::forward-----------------5------------
lbz----CudaRasterizer::Rasterizer::forward-----------------6------------
lbz----CudaRasterizer::Rasterizer::forward-----------------7------------
> /home/grads/l/libingzeng/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py(93)forward()
-> num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args) [09/08 15:27:01]
(Pdb) c
lbz---------------------------------
lbz----CudaRasterizer::Rasterizer::forward-----------------------------
lbz----CudaRasterizer::Rasterizer::forward-----------------2------------
lbz----CudaRasterizer::Rasterizer::forward-----------------3------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4------geomState.point_offsets------0x7f1854bca480
lbz----CudaRasterizer::Rasterizer::forward-----------------4------P------37005
lbz----CudaRasterizer::Rasterizer::forward-----------------4------cudaMemcpyDeviceToHost------2
lbz----CudaRasterizer::Rasterizer::forward-----------------4.1------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------binning_chunk_size------129
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------num_rendered------0
lbz----CudaRasterizer::Rasterizer::forward-----------------4.5------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4.6------------
lbz----CudaRasterizer::Rasterizer::forward-----------------5------------
lbz----CudaRasterizer::Rasterizer::forward-----------------6------------
lbz----CudaRasterizer::Rasterizer::forward-----------------7------------
> /home/grads/l/libingzeng/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py(93)forward()
-> num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args) [09/08 15:27:01]
(Pdb) c
lbz---------------------------------
lbz----CudaRasterizer::Rasterizer::forward-----------------------------
lbz----CudaRasterizer::Rasterizer::forward-----------------2------------
lbz----CudaRasterizer::Rasterizer::forward-----------------3------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4------geomState.point_offsets------0x7f1845b6c880
lbz----CudaRasterizer::Rasterizer::forward-----------------4------P------37005
lbz----CudaRasterizer::Rasterizer::forward-----------------4------cudaMemcpyDeviceToHost------2
lbz----CudaRasterizer::Rasterizer::forward-----------------4.1------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------------
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------binning_chunk_size------18446744043532756609
lbz----CudaRasterizer::Rasterizer::forward-----------------4.2------num_rendered-------1257366468
Traceback (most recent call last):
  File "train.py", line 216, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 83, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "/home/grads/l/libingzeng/Documents/Research/gaussian-splatting/gaussian_renderer/__init__.py", line 93, in render
    cov3D_precomp = cov3D_precomp)
  File "/home/grads/l/libingzeng/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/grads/l/libingzeng/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 220, in forward
    raster_settings, 
  File "/home/grads/l/libingzeng/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 41, in rasterize_gaussians
    raster_settings,
  File "/home/grads/l/libingzeng/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 93, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
RuntimeError: numel: integer multiplication overflow
Training progress:   0%|  
```

I've been grappling with this situation for a considerable duration, and I would highly value any insights, suggestions, or advice you could offer.

**Comment by Snosixtyboo** [comment]
Hi,

sorry we are currently at Siggraph and that makes developing hard, but we will take a look as soon as we're back. But it seems to me you see two different errors?

The first was a floating point exception, the second shows "integer multiplication overflow". The curious thing is that with an up-to-date codebase, things that cause a crash SHOULD produce a ```snapshot_fw.dump``` or ```snapshot_bw.dump``` and tell you to forward that to us for debugging purposes. But I actually don't see that happening in your logs...

**Comment by libingzeng** [comment]
Hi,

Thanks for your prompt response.

Here is the [snapshot_fw.dump](https://drive.google.com/file/d/1DQshHnvc1J3NdwMuHCy00sppo9nc59ts/view?usp=drive_link).

Please check that.

**Comment by Snosixtyboo** [comment]
Hi, 

I finally had time to do check your submitted file. Unfortunately, I can't reproduce the error. Can you tell me
- which OS you are on
- which GPU model you have
- if there are multiple GPUs in the system?

The memory issues occurring after the first few iterations, I have seen this on a few Ubuntu machines and tried debugging it with another user, but we couldn't solve or make sense of it... the behavior was very inconsistent 😞 

If this keeps you from trying the method, maybe using the Colab by another user would work out for you?
https://github.com/graphdeco-inria/gaussian-splatting/issues/114

**Comment by Snosixtyboo** [comment]
Closing due to inactivity

**Comment by frankielp** [comment]
i got this error also, it collapse with integer overflow right at the 1st epoch

**Comment by frankielp** [comment]
- Ubuntu 20.04
- Tesla V100
yes, i got multiple GPU
[snapshot_fw.dump](https://drive.google.com/file/d/1NBAh05nySGhti-MTpvB_X6l5oZ_iB2Ay/view?usp=sharing)
