### ISSUE TITLE
ImportError: DLL load failed while importing _C:

### ISSUE THREAD

**Issue by lllllyzer** [graphdeco-inria/gaussian-splatting#803]
I encountered this issue while running the model, and this is my runtime interface：

(3DGS) PS E:\lyz\3D-GS> python train.py -s data -m output/240511/ --iterations 8000
Traceback (most recent call last):
  File "E:\lyz\3D-GS\train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "E:\lyz\3D-GS\gaussian_renderer\__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
  File "C:\Users\new\.conda\envs\3DGS\lib\site-packages\diff_gaussian_rasterization\__init__.py", line 15, in <module>
    from . import _C
ImportError: DLL load failed while importing _C: 找不到指定的模块。

The environment configured for 3D-GS is as follows:

git clone https://github.com/graphdeco-inria/gaussian-splatting --recursive
cd gaussian-splatting
conda create -n gaussian_splatting python=3.10
conda activate gaussian_splatting
conda install -c conda-forge vs2022_win-64
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
SET DISTUTILS_USE_SDK=1
pip install submodules\diff-gaussian-rasterization
pip install submodules\simple-knn
pip install plyfile
pip install tqdm

**Comment by lllllyzer** [comment]
I have also reconfigured simple_knn and diff Gaussian transformation, which are shown as follows:

(3DGS) PS E:\lyz\3D-GS> pip install submodules\diff-gaussian-rasterization
Processing e:\lyz\3d-gs\submodules\diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff_gaussian_rasterization
  Building wheel for diff_gaussian_rasterization (setup.py) ... done
  Created wheel for diff_gaussian_rasterization: filename=diff_gaussian_rasterization-0.0.0-cp310-cp310-win_amd64.whl size=337461 sha256=c58a227b3e028cb51d83dc2f7f117f85b515da9c40f12fc8982d923ed22e59ad
  Stored in directory: c:\users\new\appdata\local\pip\cache\wheels\0d\13\20\3eb104abd08b50f41bb44c9777d4b17ee7597034c8195d3f34
Successfully built diff_gaussian_rasterization
Installing collected packages: diff_gaussian_rasterization
  Attempting uninstall: diff_gaussian_rasterization
    Found existing installation: diff_gaussian_rasterization 0.0.0
    Uninstalling diff_gaussian_rasterization-0.0.0:
      Successfully uninstalled diff_gaussian_rasterization-0.0.0
Successfully installed diff_gaussian_rasterization-0.0.0

(3DGS) PS E:\lyz\3D-GS> pip install submodules\simple-knn
Processing e:\lyz\3d-gs\submodules\simple-knn
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: simple_knn
  Building wheel for simple_knn (setup.py) ... done
  Created wheel for simple_knn: filename=simple_knn-0.0.0-cp310-cp310-win_amd64.whl size=368415 sha256=b483f86496dbe10c5a6d98137cab3210d03fbcd4bfc6a574b4ccd972bc9b4039
  Stored in directory: c:\users\new\appdata\local\pip\cache\wheels\42\75\4f\88fff82c7c81e4c715b8c68b77913b946c54a72698fc68c3f2
Successfully built simple_knn
Installing collected packages: simple_knn
  Attempting uninstall: simple_knn
    Found existing installation: simple_knn 0.0.0
    Uninstalling simple_knn-0.0.0:
      Successfully uninstalled simple_knn-0.0.0
Successfully installed simple_knn-0.0.0

**Comment by QAQQL** [comment]
Me Too

**Comment by Huajijunbilibili** [comment]
me too

**Comment by Fanxdragons** [comment]
> 看起来“pip install -e submodules/simple-knn”有时不起作用，我建议先走simple-knn的根路径，再选“setup.py”，用这个：'python setup.py install '来实现，这对我来说有效。

感谢！弄了很久的终于成功了
