### ISSUE TITLE
RuntimeError: numel: integer multiplication overflow

### ISSUE THREAD

**Issue by gwilczynski95** [graphdeco-inria/gaussian-splatting#845]
Hello. I run my custom project where I use GS rasterizer. Sometimes I encounter this problem (it happens with a random interval, usually during the second epoch, nonetheless it happens always).

Do you have any idea what is the issue here? Any tips?

```
23 Traceback (most recent call last):
24   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/train_cloth_rigid_nonrigid.py", line 321, in <module>
25     main()
26   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/train_cloth_rigid_nonrigid.py", line 313, in main
27     train(
28   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/train_cloth_rigid_nonrigid.py", line 182, in train
29     losses, data_to_loss = iter_pass(
30   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/train_cloth_rigid_nonrigid.py", line 59, in iter_pass
31     pred_mask = render_batch(
32   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/own_gaussian_utils.py", line 324, in render_batch
33     rendered_image, _ = rasterizer(
34   File "/home/olaf/miniconda3/envs/splats310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
35     return forward_call(*input, **kwargs)
36   File "/home/olaf/miniconda3/envs/splats310/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 210, in forward
37     return rasterize_gaussians(
38   File "/home/olaf/miniconda3/envs/splats310/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 32, in rasterize_gaussians
39     return _RasterizeGaussians.apply(
40   File "/home/olaf/miniconda3/envs/splats310/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 92, in forward
41     num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
42 RuntimeError: numel: integer multiplication overflow
```

**Comment by LuPaoPao** [comment]
> Hello. I run my custom project where I use GS rasterizer. Sometimes I encounter this problem (it happens with a random interval, usually during the second epoch, nonetheless it happens always).
> 
> Do you have any idea what is the issue here? Any tips?
> 
> ```
> 23 Traceback (most recent call last):
> 24   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/train_cloth_rigid_nonrigid.py", line 321, in <module>
> 25     main()
> 26   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/train_cloth_rigid_nonrigid.py", line 313, in main
> 27     train(
> 28   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/train_cloth_rigid_nonrigid.py", line 182, in train
> 29     losses, data_to_loss = iter_pass(
> 30   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/train_cloth_rigid_nonrigid.py", line 59, in iter_pass
> 31     pred_mask = render_batch(
> 32   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/own_gaussian_utils.py", line 324, in render_batch
> 33     rendered_image, _ = rasterizer(
> 34   File "/home/olaf/miniconda3/envs/splats310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
> 35     return forward_call(*input, **kwargs)
> 36   File "/home/olaf/miniconda3/envs/splats310/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 210, in forward
> 37     return rasterize_gaussians(
> 38   File "/home/olaf/miniconda3/envs/splats310/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 32, in rasterize_gaussians
> 39     return _RasterizeGaussians.apply(
> 40   File "/home/olaf/miniconda3/envs/splats310/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 92, in forward
> 41     num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
> 42 RuntimeError: numel: integer multiplication overflow
> ```
> 
> For clarification. I didn't change the code for the rasterizer, I don't pass shs, just colors_precomp after sigmoid.

Same issues here, can you solve this now?

**Comment by AutonomierLong** [comment]
Hi, same problem here, have you solved your problem?

**Comment by AutonomierLong** [comment]
> > Hello. I run my custom project where I use GS rasterizer. Sometimes I encounter this problem (it happens with a random interval, usually during the second epoch, nonetheless it happens always).
> > Do you have any idea what is the issue here? Any tips?
> > ```
> > 23 Traceback (most recent call last):
> > 24   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/train_cloth_rigid_nonrigid.py", line 321, in <module>
> > 25     main()
> > 26   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/train_cloth_rigid_nonrigid.py", line 313, in main
> > 27     train(
> > 28   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/train_cloth_rigid_nonrigid.py", line 182, in train
> > 29     losses, data_to_loss = iter_pass(
> > 30   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/train_cloth_rigid_nonrigid.py", line 59, in iter_pass
> > 31     pred_mask = render_batch(
> > 32   File "/home/olaf/grzegos/wear_it/human_mesh_work1/torch_scripts/own_gaussian_utils.py", line 324, in render_batch
> > 33     rendered_image, _ = rasterizer(
> > 34   File "/home/olaf/miniconda3/envs/splats310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
> > 35     return forward_call(*input, **kwargs)
> > 36   File "/home/olaf/miniconda3/envs/splats310/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 210, in forward
> > 37     return rasterize_gaussians(
> > 38   File "/home/olaf/miniconda3/envs/splats310/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 32, in rasterize_gaussians
> > 39     return _RasterizeGaussians.apply(
> > 40   File "/home/olaf/miniconda3/envs/splats310/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 92, in forward
> > 41     num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
> > 42 RuntimeError: numel: integer multiplication overflow
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For clarification. I didn't change the code for the rasterizer, I don't pass shs, just colors_precomp after sigmoid.
> 
> Same issues here, can you solve this now?

Have you solved?

**Comment by gwilczynski95** [comment]
Not really, I just came to a conclusion that my net was unstable and had exploding gradients hence the error. After doing gradient clipping I mitigated this problem (worth trying different type of regularization, for me this worked).

**Comment by leejngmn** [comment]
> Not really, I just came to a conclusion that my net was unstable and had exploding gradients hence the error. After doing gradient clipping I mitigated this problem (worth trying different type of regularization, for me this worked).

Could you please explain in detail how to do gradient clipping?

**Comment by gwilczynski95** [comment]
```
for data in dataloader:
    out = model(data["x"])
    loss = loss_fn(out, data["y"])
    optimizer.zero_grad()
    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip_val)
    optimizer.step()
```
Ok. So here's a toy example of how to use clip grad norm (you should use clipping by norm, also you can start with `grad_clip_val=1`).

For GS the output should be the rendered image and data["y"] should be the ground truth image.
