### ISSUE TITLE
AttributeError: module 'typing' has no attribute 'TypedDict'

### ISSUE THREAD

**Issue by wzh506** [graphdeco-inria/gaussian-splatting#859]
I run the train.py and find no errors,but when I try to run render.py,I find :

```
Traceback (most recent call last):
  File "render.py", line 18, in <module>
    import torchvision
  File "/data/wangzhaohui/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets
  File "/data/wangzhaohui/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import KittiFlow, Sintel, FlyingChairs, FlyingThings3D, HD1K
  File "/data/wangzhaohui/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torchvision/datasets/_optical_flow.py", line 13, in <module>
    from .utils import verify_str_arg
  File "/data/wangzhaohui/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 21, in <module>
    import requests
  File "/data/wangzhaohui/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/requests/__init__.py", line 164, in <module>
    from .api import delete, get, head, options, patch, post, put, request
  File "/data/wangzhaohui/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/requests/api.py", line 11, in <module>
    from . import sessions
  File "/data/wangzhaohui/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/requests/sessions.py", line 15, in <module>
    from .adapters import HTTPAdapter
  File "/data/wangzhaohui/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/requests/adapters.py", line 60, in <module>
    from urllib3.contrib.socks import SOCKSProxyManager
  File "/data/wangzhaohui/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/urllib3/contrib/socks.py", line 75, in <module>
    class _TYPE_SOCKS_OPTIONS(typing.TypedDict):
AttributeError: module 'typing' has no attribute 'TypedDict'
```
could someone help me?

**Comment by yannik-p** [comment]
Had the same issue for the last few days. Seems like creating the environment now downloads urllib3 version 2.2.2 where previously it would use 2.2.1. I couldn't actually force that version in the environment.yml file though because of the python version being <3.8. Try adding "- urllib3==2.0.7" to the environment file under "-pip:", seems to have fixed that issue for me.

**Comment by AGiannoutsos** [comment]
For me, it worked when I set `urllib3` to a previous version: `urllib3=2.2.1`. Presumably, there was an update in `urllib` on June 17th three days ago that may have caused the problem.

**Comment by wzh506** [comment]
> For me, it worked when I set `urllib3` to a previous version: `urllib3=2.2.1`. Presumably, there was an update in `urllib` on June 17th three days ago that may have caused the problem.

your answer has fixed my problem ,thank you very much!Hope more see this issue
