### ISSUE TITLE
Failed building wheels for submodules/diff-gaussian-rasterization (WSL2)

### ISSUE THREAD

**Issue by sjeongab** [graphdeco-inria/gaussian-splatting#871]
**Error**
>> pip install ./submodules/diff-gaussian-rasterization
Processing ./submodules/diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff_gaussian_rasterization
  Building wheel for diff_gaussian_rasterization (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [96 lines of output]
      running bdist_wheel
      running build
      running build_py
      copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-37/diff_gaussian_rasterization
      running build_ext
      building 'diff_gaussian_rasterization._C' extension
      Emitting ninja build file /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-37/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/3] /usr/local/cuda-11.7/bin/nvcc  -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/TH -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/cheri/anaconda3/envs/gaussian_splat/include/python3.7m -c -c /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/backward.cu -o /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-37/cuda_rasterizer/backward.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
      FAILED: /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-37/cuda_rasterizer/backward.o
      /usr/local/cuda-11.7/bin/nvcc  -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/TH -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/cheri/anaconda3/envs/gaussian_splat/include/python3.7m -c -c /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/backward.cu -o /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-37/cuda_rasterizer/backward.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
      In file included from /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/backward.cu:12:
      **/home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/backward.h:19:10: fatal error: glm/glm.hpp: No such file or directory
         19 | #include <glm/glm.hpp>**
            |          ^~~~~~~~~~~~~
      compilation terminated.
      [2/3] /usr/local/cuda-11.7/bin/nvcc  -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/TH -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/cheri/anaconda3/envs/gaussian_splat/include/python3.7m -c -c /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/forward.cu -o /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-37/cuda_rasterizer/forward.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
      FAILED: /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-37/cuda_rasterizer/forward.o
      /usr/local/cuda-11.7/bin/nvcc  -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/TH -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/cheri/anaconda3/envs/gaussian_splat/include/python3.7m -c -c /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/forward.cu -o /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-37/cuda_rasterizer/forward.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
      In file included from /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/forward.cu:12:
      **/home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/forward.h:19:10: fatal error: glm/glm.hpp: No such file or directory
         19 | #include <glm/glm.hpp>**
            |          ^~~~~~~~~~~~~
      compilation terminated.
      [3/3] /usr/local/cuda-11.7/bin/nvcc  -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/TH -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/cheri/anaconda3/envs/gaussian_splat/include/python3.7m -c -c /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/rasterizer_impl.cu -o /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-37/cuda_rasterizer/rasterizer_impl.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
      FAILED: /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-37/cuda_rasterizer/rasterizer_impl.o
      /usr/local/cuda-11.7/bin/nvcc  -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/TH -I/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/cheri/anaconda3/envs/gaussian_splat/include/python3.7m -c -c /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/rasterizer_impl.cu -o /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-37/cuda_rasterizer/rasterizer_impl.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
      /home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/cuda_rasterizer/rasterizer_impl.cu:23:10: fatal error: glm/glm.hpp: No such file or directory
         23 | #include <glm/glm.hpp>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1906, in _run_ninja_build
          env=env)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/subprocess.py", line 512, in run
          output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/cheri/gaussian-splatting/submodules/diff-gaussian-rasterization/setup.py", line 32, in <module>
          'build_ext': BuildExtension
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 668, in unix_wrap_ninja_compile
          with_cuda=with_cuda)
        File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1578, in _write_ninja_file_and_compile_objects
          error_prefix='Error compiling objects for extension')
        **File "/home/cheri/anaconda3/envs/gaussian_splat/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build**
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization

**Environment**
WSL2 (Ubuntu 22.04) from Windows11
GPU: NVIDIA GeForce RTX 3070
CPU: 12th Gen Intel(R) Core(TM) i5-12400F
Libraries:
_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=2_gnu
blas=2.16=mkl
brotli-python=1.0.9=py37hd23a5d3_7
bzip2=1.0.8=hd590300_5
ca-certificates=2024.6.2=hbcca054_0
certifi=2024.6.2=pyhd8ed1ab_0
charset-normalizer=3.3.2=pyhd8ed1ab_0
colorama=0.4.6=pyhd8ed1ab_0
cuda-cudart=11.7.99=0
cuda-cupti=11.7.101=0
cuda-libraries=11.7.1=0
cuda-nvrtc=11.7.99=0
cuda-nvtx=11.7.91=0
cuda-runtime=11.7.1=0
cudatoolkit=11.7.1=h4bc3d14_13
ffmpeg=4.3=hf484d3e_0
freetype=2.12.1=h267a509_2
gmp=6.3.0=hac33072_2
gnutls=3.6.13=h85f3911_1
idna=3.7=pyhd8ed1ab_0
intel-openmp=2022.1.0=h9e868ea_3769
jpeg=9e=h0b41bf4_3
lame=3.100=h166bdaf_1003
lcms2=2.14=h6ed2654_0
ld_impl_linux-64=2.40=hf3520f5_7
lerc=4.0.0=h27087fc_0
libblas=3.8.0=16_mkl
libcblas=3.8.0=16_mkl
libcublas=11.10.3.66=0
libcufft=10.7.2.124=h4fbf590_0
libcufile=1.9.1.3=0
libcurand=10.3.5.147=0
libcusolver=11.4.0.1=0
libcusparse=11.7.4.91=0
libdeflate=1.14=h166bdaf_0
libffi=3.4.4=h6a678d5_1
libgcc-ng=14.1.0=h77fa898_0
libgfortran-ng=7.5.0=h14aa051_20
libgfortran4=7.5.0=h14aa051_20
libgomp=14.1.0=h77fa898_0
libiconv=1.17=hd590300_2
liblapack=3.8.0=16_mkl
liblapacke=3.8.0=16_mkl
libnpp=11.7.4.75=0
libnsl=2.0.0=h5eee18b_0
libnvjpeg=11.8.0.2=0
libpng=1.6.43=h2797004_0
libsqlite=3.46.0=hde9e2c9_0
libstdcxx-ng=14.1.0=hc0a3c3a_0
libtiff=4.4.0=h82bc61c_5
libwebp-base=1.4.0=hd590300_0
libxcb=1.13=h7f98852_1004
libzlib=1.2.13=h4ab18f5_6
mkl=2020.2=256
ncurses=6.5=h59595ed_0
nettle=3.6=he412f7d_0
ninja=1.10.2=h06a4308_5
ninja-base=1.10.2=hd09550d_5
numpy=1.21.6=py37h976b520_0
openh264=2.1.1=h780b84a_0
openjpeg=2.5.0=h7d73246_1
openssl=3.0.14=h5eee18b_0
pillow=9.2.0=py37h850a105_2
pip=22.3.1=pyhd8ed1ab_0
plyfile=0.8.1=pyhd8ed1ab_0
pthread-stubs=0.4=h36c2ea0_1001
pysocks=1.7.1=py37h89c1867_5
python=3.7.12=hf930737_100_cpython
python_abi=3.7=2_cp37m
pytorch-cuda=11.7=h778d358_5
pytorch-mutex=1.0=cpu
readline=8.2=h8228510_1
requests=2.32.2=pyhd8ed1ab_0
setuptools=69.0.3=pyhd8ed1ab_0
sqlite=3.46.0=h6d4b2fc_0
tk=8.6.13=noxft_h4845f30_101
torch=1.13.1+cu117=pypi_0
torchaudio=0.13.1=pypi_0
torchvision=0.14.1+cu117=pypi_0
tqdm=4.66.4=pyhd8ed1ab_0
typing_extensions=4.7.1=pyha770c72_0
urllib3=2.2.1=pyhd8ed1ab_0
wheel=0.42.0=pyhd8ed1ab_0
xorg-libxau=1.0.11=hd590300_0
xorg-libxdmcp=1.1.3=h7f98852_0
xz=5.2.6=h166bdaf_0
zlib=1.2.13=h4ab18f5_6
zstd=1.5.6=ha6fb4c9_0

Would you please have a look into this issue? Tried solution [here](https://github.com/graphdeco-inria/gaussian-splatting/issues/865), didn't work.. Do I have to install Visual Studio 2019 for Windows? I don't think it's relevant for WSL2. Thank you.

**Comment by sjeongab** [comment]
Sorry for the false alarm. Solved after installing glm

**Comment by justin4ai** [comment]
Hello, did you manage to solve the problem without ```sudo``` privilege?

**Comment by CDX-Imcui** [comment]
More convenient：git submodule update --init --recursive
Don't have to build and install GLM
