### ISSUE TITLE
Failed installing submodules/diff_gaussian_rasterization and submodules/simple-knn

### ISSUE THREAD

**Issue by skywalker-lt** [graphdeco-inria/gaussian-splatting#901]
**Error description:**
I had this error `subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1` popped up when I was trying to install submodules/diff_gaussian_rasterization and submodules/simple-knn using the following command:

`pip install submodules/diff_gaussian_rasterization`
`pip install submodules/simple-knn`

I tried to reinstall ninja but it didn't work. 

**Full Output**

`      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1814, in _run_ninja_build
          env=env)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\subprocess.py", line 512, in run
          output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Gaussian\gaussian-splatting-main\submodules\simple-knn\setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\install.py", line 78, in run
          return orig.install.run(self)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\install.py", line 697, in run
          self.run_command('build')
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 747, in win_wrap_ninja_compile
          with_cuda=with_cuda)
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1492, in _write_ninja_file_and_compile_objects
          error_prefix='Error compiling objects for extension')
        File "C:\ProgramData\anaconda3\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
°¡ Encountered error while trying to install package.
®t©§> simple_knn
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

**Comment by dek8v5** [comment]
I encountered the same problem, solved it by the following steps:
- git clone the submodules ubder submodules directory:
`git clone https://github.com/graphdeco-inria/diff-gaussian-rasterization.git`
`git clone https://gitlab.inria.fr/bkerbl/simple-knn.git`

- install linglm-dev:
`sudo apt-get install libglm-dev`

then redo the installation.

**Comment by samuelziemian** [comment]
> I encountered the same problem, solved it by the following steps:
> 
> * git clone the submodules ubder submodules directory:
>   `git clone https://github.com/graphdeco-inria/diff-gaussian-rasterization.git`
>   `git clone https://gitlab.inria.fr/bkerbl/simple-knn.git`
> * install linglm-dev:
>   `sudo apt-get install libglm-dev`
> 
> then redo the installation.

i gvet this messega that says that sudo is not recognized as a internal or external command:(gaussian_splatting) C:\Users\samue\gaussian-splatting>sudo apt-get install libglm-dev
'sudo' is not recognized as an internal or external command,
operable program or batch file.
