### ISSUE TITLE
TypeError: __new__() missing 1 required positional argument: 'projmatrix_raw'

### ISSUE THREAD

**Issue by jianchaoci** [graphdeco-inria/gaussian-splatting#924]
I got this error when training the network. I got colmap data set already, it works well. But when start training, I got this error.
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 86, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg)
  File "/home/jianchao/git_opensource_pro/gaussian-splatting/gaussian_renderer/__init__.py", line 37, in render
    raster_settings = GaussianRasterizationSettings(
TypeError: __new__() missing 1 required positional argument: 'projmatrix_raw'

**Comment by jianchaoci** [comment]
Hi I just solved it as I did not use the diff-gaussian-rasterization you provided. Now it works after I reinstall this package.

**Comment by yemiaoxuan** [comment]
> Hi I just solved it as I did not use the diff-gaussian-rasterization you provided. Now it works after I reinstall this package.

I encountered the same issue, but reinstalling did not resolve it. Could you please explain the solution in more detail?

**Comment by choyy** [comment]
> > Hi I just solved it as I did not use the diff-gaussian-rasterization you provided. Now it works after I reinstall this package.
> 
> I encountered the same issue, but reinstalling did not resolve it. Could you please explain the solution in more detail?

Try `pip install submodules/diff-gaussian-rasterization/` in the project dir
