### ISSUE TITLE
Unable to Run train.py on NeRF Synthetic Scene After Latest Update

### ISSUE THREAD

**Issue by Jakub-Szymkowiak** [graphdeco-inria/gaussian-splatting#962]
After the latest update, I'm encountering the following error when trying to run `train.py` on a NeRF Synthetic scene:

```
(gaussian_splatting) /workspace/gaussian-splatting$ python train.py -s /workspace/datasets/nerf_synthetic/ficus
Optimizing 
Output folder: ./output/e8290376-d [30/08 14:12:44]
Tensorboard not available: not logging progress [30/08 14:12:44]
Found transforms_train.json file, assuming Blender data set! [30/08 14:12:44]
Reading Training Transforms [30/08 14:12:44]
Traceback (most recent call last):
  File "train.py", line 252, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "/workspace/gaussian-splatting/scene/__init__.py", line 47, in __init__
    scene_info = sceneLoadTypeCallbacks["Blender"](args.source_path, args.white_background, args.eval)
  File "/workspace/gaussian-splatting/scene/dataset_readers.py", line 270, in readNerfSyntheticInfo
    train_cam_infos = readCamerasFromTransforms(path, "transforms_train.json", white_background, extension)
  File "/workspace/gaussian-splatting/scene/dataset_readers.py", line 264, in readCamerasFromTransforms
    image_path=image_path, image_name=image_name, width=image.size[0], height=image.size[1]))
TypeError: __new__() missing 3 required positional arguments: 'depth_params', 'depth_path', and 'is_test'
```

Looking at [this](https://github.com/graphdeco-inria/gaussian-splatting/blob/c643c864416c5258c76cd9f0eed55203834cbf83/scene/dataset_readers.py#L263) line, it appears to me that indeed these three arguments are missing.

**Comment by MatteoMarengo** [comment]
I have the same issue than you, I would be interested if someone manage to solve this.

**Comment by alanvinx** [comment]
Hi, we are currently working on it, I will post a message once it is resolved in the `dev` branch.

**Comment by alanvinx** [comment]
Hi, this was fixed in the `dev` branch.
