### ISSUE TITLE
Unable to build submodules/diff Gaussian rasterization

### ISSUE THREAD

**Issue by datouzhan** [graphdeco-inria/gaussian-splatting#999]
with
              [
                  K=c10::DispatchKey,
                  V=std::list<c10::impl::AnnotatedKernel,std::allocator<c10::impl::AnnotatedKernel>>
              ]
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "D:\Anaconda\envs\gaussian_splatting\lib\subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
     
      The above exception was the direct cause of the following exception:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "E:\2024\guassiansplat\code\gaussian-splatting\submodules\diff-gaussian-rasterization\setup.py", line 17, in <module>
          setup(
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\command\install.py", line 78, in run
          return orig.install.run(self)
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\install.py", line 697, in run
          self.run_command('build')
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
          self.build_extension(ext)
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\command\build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 815, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "D:\Anaconda\envs\gaussian_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> diff_gaussian_rasterization

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by AsherJingkongChen** [comment]
It might be a little tricky if you are using Python 3.12.

**Comment by datouzhan** [comment]
Thanks for your reply. I reinstalled the python version to 3.8

> It might be a little tricky if you are using Python 3.12.
